#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALMANSURE_WIDGET

#include "Basic.hpp"

#include "ALMANSURE_WIDGET_classes.hpp"
#include "ALMANSURE_WIDGET_parameters.hpp"


namespace SDK
{

// Function ALMANSURE_WIDGET.ALMANSURE_WIDGET_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UALMANSURE_WIDGET_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ALMANSURE_WIDGET_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ALMANSURE_WIDGET.ALMANSURE_WIDGET_C.ExecuteUbergraph_ALMANSURE_WIDGET
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UALMANSURE_WIDGET_C::ExecuteUbergraph_ALMANSURE_WIDGET(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ALMANSURE_WIDGET_C", "ExecuteUbergraph_ALMANSURE_WIDGET");

	Params::ALMANSURE_WIDGET_C_ExecuteUbergraph_ALMANSURE_WIDGET Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

