#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AreYouSureMenu

#include "Basic.hpp"

#include "BP_AreYouSureMenu_classes.hpp"
#include "BP_AreYouSureMenu_parameters.hpp"


namespace SDK
{

// Function BP_AreYouSureMenu.BP_AreYouSureMenu_C.BndEvt__NoButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_AreYouSureMenu_C::BndEvt__NoButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AreYouSureMenu_C", "BndEvt__NoButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AreYouSureMenu.BP_AreYouSureMenu_C.BndEvt__YesButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_AreYouSureMenu_C::BndEvt__YesButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AreYouSureMenu_C", "BndEvt__YesButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AreYouSureMenu.BP_AreYouSureMenu_C.ExecuteUbergraph_BP_AreYouSureMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AreYouSureMenu_C::ExecuteUbergraph_BP_AreYouSureMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AreYouSureMenu_C", "ExecuteUbergraph_BP_AreYouSureMenu");

	Params::BP_AreYouSureMenu_C_ExecuteUbergraph_BP_AreYouSureMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AreYouSureMenu.BP_AreYouSureMenu_C.NoSelected__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UBP_AreYouSureMenu_C::NoSelected__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AreYouSureMenu_C", "NoSelected__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AreYouSureMenu.BP_AreYouSureMenu_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AreYouSureMenu_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AreYouSureMenu_C", "PreConstruct");

	Params::BP_AreYouSureMenu_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AreYouSureMenu.BP_AreYouSureMenu_C.UpdateAreYouSureMenu
// (BlueprintCallable, BlueprintEvent)

void UBP_AreYouSureMenu_C::UpdateAreYouSureMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AreYouSureMenu_C", "UpdateAreYouSureMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AreYouSureMenu.BP_AreYouSureMenu_C.YesSelected__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UBP_AreYouSureMenu_C::YesSelected__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AreYouSureMenu_C", "YesSelected__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

