#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BasicTriangleFloor

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_BasicTriangleFloor.BP_BasicTriangleFloor_C.ExecuteUbergraph_BP_BasicTriangleFloor
// 0x0004 (0x0004 - 0x0000)
struct BP_BasicTriangleFloor_C_ExecuteUbergraph_BP_BasicTriangleFloor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_BasicTriangleFloor_C_ExecuteUbergraph_BP_BasicTriangleFloor) == 0x000004, "Wrong alignment on BP_BasicTriangleFloor_C_ExecuteUbergraph_BP_BasicTriangleFloor");
static_assert(sizeof(BP_BasicTriangleFloor_C_ExecuteUbergraph_BP_BasicTriangleFloor) == 0x000004, "Wrong size on BP_BasicTriangleFloor_C_ExecuteUbergraph_BP_BasicTriangleFloor");
static_assert(offsetof(BP_BasicTriangleFloor_C_ExecuteUbergraph_BP_BasicTriangleFloor, EntryPoint) == 0x000000, "Member 'BP_BasicTriangleFloor_C_ExecuteUbergraph_BP_BasicTriangleFloor::EntryPoint' has a wrong offset!");

}

