#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BasicFoundation

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_BasicFoundation.BP_BasicFoundation_C.ExecuteUbergraph_BP_BasicFoundation
// 0x0004 (0x0004 - 0x0000)
struct BP_BasicFoundation_C_ExecuteUbergraph_BP_BasicFoundation final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_BasicFoundation_C_ExecuteUbergraph_BP_BasicFoundation) == 0x000004, "Wrong alignment on BP_BasicFoundation_C_ExecuteUbergraph_BP_BasicFoundation");
static_assert(sizeof(BP_BasicFoundation_C_ExecuteUbergraph_BP_BasicFoundation) == 0x000004, "Wrong size on BP_BasicFoundation_C_ExecuteUbergraph_BP_BasicFoundation");
static_assert(offsetof(BP_BasicFoundation_C_ExecuteUbergraph_BP_BasicFoundation, EntryPoint) == 0x000000, "Member 'BP_BasicFoundation_C_ExecuteUbergraph_BP_BasicFoundation::EntryPoint' has a wrong offset!");

}

