#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BuildPartName

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_BuildPartName.BP_BuildPartName_C
// 0x0048 (0x02C0 - 0x0278)
class UBP_BuildPartName_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Button_81;                                         // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                CancelButton;                                      // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             CodeMessage;                                       // 0x0290(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ErrorText;                                         // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_166;                                         // 0x02A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                OkButton;                                          // 0x02A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableTextBox*                       TextBox;                                           // 0x02B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          NameError;                                         // 0x02B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__Button_81_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__CancelButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__OkButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TextBox_K2Node_ComponentBoundEvent_0_OnEditableTextBoxCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod);
	void ExecuteUbergraph_BP_BuildPartName(int32 EntryPoint);
	void Reset();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BuildPartName_C">();
	}
	static class UBP_BuildPartName_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BuildPartName_C>();
	}
};
static_assert(alignof(UBP_BuildPartName_C) == 0x000008, "Wrong alignment on UBP_BuildPartName_C");
static_assert(sizeof(UBP_BuildPartName_C) == 0x0002C0, "Wrong size on UBP_BuildPartName_C");
static_assert(offsetof(UBP_BuildPartName_C, UberGraphFrame) == 0x000278, "Member 'UBP_BuildPartName_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_BuildPartName_C, Button_81) == 0x000280, "Member 'UBP_BuildPartName_C::Button_81' has a wrong offset!");
static_assert(offsetof(UBP_BuildPartName_C, CancelButton) == 0x000288, "Member 'UBP_BuildPartName_C::CancelButton' has a wrong offset!");
static_assert(offsetof(UBP_BuildPartName_C, CodeMessage) == 0x000290, "Member 'UBP_BuildPartName_C::CodeMessage' has a wrong offset!");
static_assert(offsetof(UBP_BuildPartName_C, ErrorText) == 0x000298, "Member 'UBP_BuildPartName_C::ErrorText' has a wrong offset!");
static_assert(offsetof(UBP_BuildPartName_C, Image_166) == 0x0002A0, "Member 'UBP_BuildPartName_C::Image_166' has a wrong offset!");
static_assert(offsetof(UBP_BuildPartName_C, OkButton) == 0x0002A8, "Member 'UBP_BuildPartName_C::OkButton' has a wrong offset!");
static_assert(offsetof(UBP_BuildPartName_C, TextBox) == 0x0002B0, "Member 'UBP_BuildPartName_C::TextBox' has a wrong offset!");
static_assert(offsetof(UBP_BuildPartName_C, NameError) == 0x0002B8, "Member 'UBP_BuildPartName_C::NameError' has a wrong offset!");

}

