#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CharacterEquipment

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_CharacterEquipment.BP_CharacterEquipment_C.ExecuteUbergraph_BP_CharacterEquipment
// 0x0028 (0x0028 - 0x0000)
struct BP_CharacterEquipment_C_ExecuteUbergraph_BP_CharacterEquipment final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D89[0x3];                                     // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class UWidget*>                        K2Node_MakeArray_Array;                            // 0x0010(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UBP_PlayerInventory_C*                  CallFunc_GetComponentByClass_ReturnValue;          // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CharacterEquipment_C_ExecuteUbergraph_BP_CharacterEquipment) == 0x000008, "Wrong alignment on BP_CharacterEquipment_C_ExecuteUbergraph_BP_CharacterEquipment");
static_assert(sizeof(BP_CharacterEquipment_C_ExecuteUbergraph_BP_CharacterEquipment) == 0x000028, "Wrong size on BP_CharacterEquipment_C_ExecuteUbergraph_BP_CharacterEquipment");
static_assert(offsetof(BP_CharacterEquipment_C_ExecuteUbergraph_BP_CharacterEquipment, EntryPoint) == 0x000000, "Member 'BP_CharacterEquipment_C_ExecuteUbergraph_BP_CharacterEquipment::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_CharacterEquipment_C_ExecuteUbergraph_BP_CharacterEquipment, K2Node_Event_IsDesignTime) == 0x000004, "Member 'BP_CharacterEquipment_C_ExecuteUbergraph_BP_CharacterEquipment::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(BP_CharacterEquipment_C_ExecuteUbergraph_BP_CharacterEquipment, CallFunc_GetOwningPlayer_ReturnValue) == 0x000008, "Member 'BP_CharacterEquipment_C_ExecuteUbergraph_BP_CharacterEquipment::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CharacterEquipment_C_ExecuteUbergraph_BP_CharacterEquipment, K2Node_MakeArray_Array) == 0x000010, "Member 'BP_CharacterEquipment_C_ExecuteUbergraph_BP_CharacterEquipment::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_CharacterEquipment_C_ExecuteUbergraph_BP_CharacterEquipment, CallFunc_GetComponentByClass_ReturnValue) == 0x000020, "Member 'BP_CharacterEquipment_C_ExecuteUbergraph_BP_CharacterEquipment::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");

// Function BP_CharacterEquipment.BP_CharacterEquipment_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct BP_CharacterEquipment_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CharacterEquipment_C_PreConstruct) == 0x000001, "Wrong alignment on BP_CharacterEquipment_C_PreConstruct");
static_assert(sizeof(BP_CharacterEquipment_C_PreConstruct) == 0x000001, "Wrong size on BP_CharacterEquipment_C_PreConstruct");
static_assert(offsetof(BP_CharacterEquipment_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'BP_CharacterEquipment_C_PreConstruct::IsDesignTime' has a wrong offset!");

}

