#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0xC4 (0x350 - 0x28C)
// BlueprintGeneratedClass BP_CookingComponent.BP_CookingComponent_C
class UBP_CookingComponent_C : public UBP_MasterInventory_C
{
public:
	uint8                                        Pad_5108[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x290(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	enum class E_CookingType                     CookingType;                                       // 0x298(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_5109[0x3];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	int32                                        NumberOfCookingSlots;                              // 0x29C(0x4)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         RequireFuel;                                       // 0x2A0(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_510A[0x3];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	int32                                        NumberOfFuelSlots;                                 // 0x2A4(0x4)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FDataTableRowHandle>           FuelItems;                                         // 0x2A8(0x10)(Edit, BlueprintVisible)
	bool                                         SwitchedOn;                                        // 0x2B8(0x1)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_510B[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	struct FTimerHandle                          FuelTimer;                                         // 0x2C0(0x8)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                          ConvertTimer;                                      // 0x2C8(0x8)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                        DummySlots;                                        // 0x2D0(0x4)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_510C[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TArray<struct FS_CookingSlot>                CookingSlots;                                      // 0x2D8(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  CookingUITitle;                                    // 0x2E8(0x18)(Edit, BlueprintVisible)
	TArray<int32>                                PausedIndexs;                                      // 0x300(0x10)(Edit, BlueprintVisible, Net, DisableEditOnInstance)
	struct FS_InvItem                            ReturnFuelItem;                                    // 0x310(0x30)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	TArray<struct FS_CraftingCost>               FuelStartingItems;                                 // 0x340(0x10)(Edit, BlueprintVisible)

	static class UClass* StaticClass();
	static class UBP_CookingComponent_C* GetDefaultObj();

	void AddStartingItems(bool* Return, bool CallFunc_AddStartingItems_Return);
	void AddStartingFuelItems(const struct FS_InvSlot& SlotL, const struct FS_CraftingCost& StartingItemL, const TArray<struct FS_InvSlot>& FuelSlotsL, bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, bool CallFunc_SGK_InvSlotAmount_ItemValid, int32 CallFunc_SGK_InvSlotAmount_Amount, bool CallFunc_IsFuelItem_IsFuelItem, bool CallFunc_DoesDataTableRowExist_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, class AGameModeBase* CallFunc_GetGameMode_ReturnValue, TScriptInterface<class IBP_SGKGameModeInterface_C> K2Node_DynamicCast_AsBP_SGKGame_Mode_Interface, bool K2Node_DynamicCast_bSuccess, class ABP_GlobalInventoryManager_C* CallFunc_SGK_GetGlobalInventory_GlobalInventory, const struct FS_InvSlot& CallFunc_Array_Get_Item, const struct FS_InvItem& CallFunc_CreateNewItem_NewItem, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_WeightCheck_ExceedsMaxWeight, bool CallFunc_ItemLimitCheck_AllowAdd, int32 CallFunc_ItemLimitCheck_AddCount, int32 CallFunc_ItemLimitCheck_Remaining, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, bool CallFunc_GetFuelSlots_ReturnValue, TArray<struct FS_InvSlot>& CallFunc_GetFuelSlots_FuelSlots, bool CallFunc_SGK_RootSpaceCheck_SlotsBlocked, TArray<struct FS_InvSlot>& CallFunc_SGK_RootSpaceCheck_FoundSlots, const struct FS_CraftingCost& CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1);
	void Add_Burnt_Fuel_Item(const struct FS_CraftingCost& BurnReturnItemL, const struct FS_InvItem& NewItemL, const struct FS_InvSlot& InventorySlotL, bool CallFunc_FreeSlotCheck_ReturnValue, const struct FS_InvSlot& CallFunc_FreeSlotCheck_InvSlot, class AGameModeBase* CallFunc_GetGameMode_ReturnValue, TScriptInterface<class IBP_SGKGameModeInterface_C> K2Node_DynamicCast_AsBP_SGKGame_Mode_Interface, bool K2Node_DynamicCast_bSuccess, class ABP_GlobalInventoryManager_C* CallFunc_SGK_GetGlobalInventory_GlobalInventory, const struct FS_InvItem& CallFunc_CreateNewItem_NewItem, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_SGK_InvSlotAmount_ItemValid, int32 CallFunc_SGK_InvSlotAmount_Amount, class AActor* CallFunc_GetOwner_ReturnValue, const struct FTransform& CallFunc_GetTransform_ReturnValue, const struct FVector& CallFunc_BreakTransform_Location, const struct FRotator& CallFunc_BreakTransform_Rotation, const struct FVector& CallFunc_BreakTransform_Scale, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem, const struct FVector& CallFunc_GetForwardVector_ReturnValue, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, const struct FVector& CallFunc_Multiply_VectorFloat_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue, const struct FTransform& CallFunc_MakeTransform_ReturnValue, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, class AActor* CallFunc_FinishSpawningActor_ReturnValue, class AGameModeBase* CallFunc_GetGameMode_ReturnValue_1, TScriptInterface<class IBP_SGKInteractionInterface_C> K2Node_DynamicCast_AsBP_SGKInteraction_Interface, bool K2Node_DynamicCast_bSuccess_1, TScriptInterface<class IBP_SGKGameModeInterface_C> K2Node_DynamicCast_AsBP_SGKGame_Mode_Interface_1, bool K2Node_DynamicCast_bSuccess_2, bool CallFunc_SGK_DropItem_ReturnValue, class ABP_GlobalInventoryManager_C* CallFunc_SGK_GetGlobalInventory_GlobalInventory_1, const struct FS_InvItem& CallFunc_CreateNewItem_NewItem_1, bool CallFunc_SGK_ItemDetails_ItemFound_1, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails_1, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem_1, bool CallFunc_SGK_ItemDetails_ItemFound_2, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails_2);
	void UnPauseSingleSlot(int32 Index, bool Pause, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UBP_PlayerInventory_C* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue);
	void SaveCookingData(class UBP_SGKSaveGame_C* SaveGame, const struct FS_LevelSaveData& LevelSaveDataL, const class FString& CallFunc_GetCurrentLevelName_ReturnValue, int32 CallFunc_PrepareCookingSaveData_ExtraDataIndex, const struct FS_LevelSaveData& CallFunc_PrepareCookingSaveData_NewLevelSaveData, bool CallFunc_SelectLevelSaveData_SaveFound, const struct FS_LevelSaveData& CallFunc_SelectLevelSaveData_LevelSaveData);
	void LoadComponentData(class UBP_SGKSaveGame_C* SaveGame, bool* LoadComplete, class AActor* CallFunc_GetOwner_ReturnValue, const class FString& CallFunc_GetCurrentLevelName_ReturnValue, const struct FTransform& CallFunc_GetTransform_ReturnValue, bool CallFunc_FindCookingSaveData_SaveFound, const struct FS_CookingSave& CallFunc_FindCookingSaveData_Array_Element);
	void LoadCookingData(struct FS_StorageSave& S_StorageSave, const TArray<struct FS_InvSlot>& FoundSlotsL, const struct FS_InvItem& InvItemL, const struct FS_InvSaveSlot& InvSaveSlotL, const struct FS_StorageSave& CookingSaveDataL, int32 Temp_int_Array_Index_Variable, const struct FS_OtherInvSaves& CallFunc_Array_Get_Item, const struct FS_InvSlot& CallFunc_Array_Get_Item_1, TArray<struct FS_InvSlot>& K2Node_MakeArray_Array, int32 Temp_int_Loop_Counter_Variable, class AGameModeBase* CallFunc_GetGameMode_ReturnValue, TScriptInterface<class IBP_SGKGameModeInterface_C> K2Node_DynamicCast_AsBP_SGKGame_Mode_Interface, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_Add_IntInt_ReturnValue, class ABP_GlobalInventoryManager_C* CallFunc_SGK_GetGlobalInventory_GlobalInventory, bool CallFunc_IsCookingSlot_IsCookingSlot, bool CallFunc_IsValid_ReturnValue, const struct FS_InvSlot& CallFunc_Array_Get_Item_2, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem, int32 CallFunc_SGK_ItemSize_Height, int32 CallFunc_SGK_ItemSize_Width, TArray<struct FS_InvSlot>& CallFunc_SGK_SlotFinder_FoundSlots, class UBP_WeaponInventory_C* K2Node_DynamicCast_AsBP_Weapon_Inventory, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_Array_IsValidIndex_ReturnValue, const struct FS_OtherInvSaves& CallFunc_Array_Get_Item_3, const struct FS_InvItem& CallFunc_CreateNewItem_NewItem, const struct FS_InvItem& K2Node_SetFieldsInStruct_StructOut, TArray<struct FS_InvSlot>& CallFunc_UpdateInvSlots_UpdatedSlots, bool CallFunc_EqualEqual_IntInt_ReturnValue, TArray<struct FS_InvSlot>& CallFunc_UpdateInvSlots_UpdatedSlots_1, bool CallFunc_Array_IsValidIndex_ReturnValue_1, const struct FS_InvSaveSlot& CallFunc_Array_Get_Item_4, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, double K2Node_VariableSet_CurrentWeight_ImplicitCast, double K2Node_VariableSet_CurrentWeight_ImplicitCast_1);
	void SetSwitchedOn();
	void AddReturnedItems(const struct FS_CookingSlot& CookingSlot, const struct FS_InvItem& NewItemL, const struct FS_InvSlot& InventorySlotL, const struct FS_CraftingCost& ArrayElementL, bool CallFunc_FreeSlotCheck_ReturnValue, const struct FS_InvSlot& CallFunc_FreeSlotCheck_InvSlot, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_SGK_ItemCookingRecipe_ReturnValue, const struct FS_CookingRecipe& CallFunc_SGK_ItemCookingRecipe_CookingRecipe, int32 CallFunc_Add_IntInt_ReturnValue, const struct FS_CraftingCost& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class AGameModeBase* CallFunc_GetGameMode_ReturnValue, TScriptInterface<class IBP_SGKGameModeInterface_C> K2Node_DynamicCast_AsBP_SGKGame_Mode_Interface, bool K2Node_DynamicCast_bSuccess, class AGameModeBase* CallFunc_GetGameMode_ReturnValue_1, class ABP_GlobalInventoryManager_C* CallFunc_SGK_GetGlobalInventory_GlobalInventory, TScriptInterface<class IBP_SGKGameModeInterface_C> K2Node_DynamicCast_AsBP_SGKGame_Mode_Interface_1, bool K2Node_DynamicCast_bSuccess_1, class ABP_GlobalInventoryManager_C* CallFunc_SGK_GetGlobalInventory_GlobalInventory_1, const struct FS_InvItem& CallFunc_CreateNewItem_NewItem, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_SGK_InvSlotAmount_ItemValid, int32 CallFunc_SGK_InvSlotAmount_Amount, const struct FS_InvItem& CallFunc_CreateNewItem_NewItem_1, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem_1, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, class AActor* CallFunc_GetOwner_ReturnValue, const struct FTransform& CallFunc_GetTransform_ReturnValue, const struct FVector& CallFunc_BreakTransform_Location, const struct FRotator& CallFunc_BreakTransform_Rotation, const struct FVector& CallFunc_BreakTransform_Scale, const struct FVector& CallFunc_GetForwardVector_ReturnValue, const struct FVector& CallFunc_Multiply_VectorFloat_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue, const struct FTransform& CallFunc_MakeTransform_ReturnValue, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, class AActor* CallFunc_FinishSpawningActor_ReturnValue, TScriptInterface<class IBP_SGKInteractionInterface_C> K2Node_DynamicCast_AsBP_SGKInteraction_Interface, bool K2Node_DynamicCast_bSuccess_2, bool CallFunc_SGK_DropItem_ReturnValue);
	bool FreeSlotCheck(const struct FS_CraftingCost& Item, struct FS_InvSlot* InvSlot, bool ReturnValueL, const struct FS_InvSlot& ArrayElementL, int32 Temp_int_Array_Index_Variable, bool CallFunc_SGK_IsRootSlot_IsRootSlot, int32 CallFunc_SGK_IsRootSlot_RootIndex, bool CallFunc_SGK_InvSlotAmount_ItemValid, int32 CallFunc_SGK_InvSlotAmount_Amount, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem, bool CallFunc_WeightCheck_ExceedsMaxWeight, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, bool CallFunc_SGK_ItemDetails_ItemFound_1, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails_1, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_GetContentsSlots_ReturnValue, TArray<struct FS_InvSlot>& CallFunc_GetContentsSlots_ContentsSlots, const struct FS_InvSlot& CallFunc_Array_Get_Item, bool CallFunc_EqualEqual_NameName_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
	bool SetNewCookingItem(const struct FS_InvSlot& InvSlot, struct FS_CookingSlot* CookingSlot, const struct FS_InvItem& CallFunc_SGK_InvSlotItem_InvItem, bool CallFunc_SGK_ItemCookingRecipe_ReturnValue, const struct FS_CookingRecipe& CallFunc_SGK_ItemCookingRecipe_CookingRecipe, bool CallFunc_Set_Contains_ReturnValue, const struct FS_CookingSlot& CallFunc_Array_Get_Item, const struct FS_InvItem& CallFunc_SGK_InvSlotItem_InvItem_1, const struct FS_CookingSlot& K2Node_MakeStruct_S_CookingSlot);
	void SetNewCookingSlotItem(const struct FS_InvSlot& InvSlot, const struct FS_InvItem& Item, bool SpecialSlot, bool Temp_bool_Variable, int32 Temp_int_Variable, bool Temp_bool_Variable_1, int32 Temp_int_Variable_1, bool Temp_bool_Variable_2, int32 Temp_int_Variable_2, int32 Temp_int_Variable_3, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_1, class UBP_PlayerInventory_C* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, class UBP_PlayerInventory_C* CallFunc_Array_Get_Item_1, const struct FS_InvItem& CallFunc_SGK_InvSlotItem_InvItem, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_SGK_ItemSize_Height, int32 CallFunc_SGK_ItemSize_Width, bool Temp_bool_Variable_3, int32 CallFunc_SGK_ItemSize_Height_1, int32 CallFunc_SGK_ItemSize_Width_1, int32 CallFunc_SGK_ItemSize_Height_2, int32 CallFunc_SGK_ItemSize_Width_2, int32 K2Node_Select_Default, int32 K2Node_Select_Default_1, TArray<struct FS_InvSlot>& CallFunc_SGK_SlotFinder_FoundSlots, const struct FS_InvItem& CallFunc_SGK_InvSlotItem_InvItem_1, TArray<struct FS_InvSlot>& CallFunc_UpdateInvSlots_UpdatedSlots, const struct FS_InvSlot& CallFunc_Array_Get_Item_2, int32 CallFunc_SGK_ItemSize_Height_3, int32 CallFunc_SGK_ItemSize_Width_3, int32 CallFunc_SGK_ItemSize_Height_4, int32 CallFunc_SGK_ItemSize_Width_4, int32 K2Node_Select_Default_2, int32 CallFunc_SGK_ItemSize_Height_5, int32 CallFunc_SGK_ItemSize_Width_5, int32 K2Node_Select_Default_3, bool CallFunc_Greater_IntInt_ReturnValue, TArray<struct FS_InvSlot>& CallFunc_SGK_SlotFinder_FoundSlots_1, TArray<struct FS_InvSlot>& CallFunc_UpdateInvSlots_UpdatedSlots_1, const struct FS_InvSlot& CallFunc_Array_Get_Item_3);
	void MoveCookingItem(const struct FS_InvSlot& ContentElement, const struct FS_InvSlot& CookingSlot, const struct FS_InvItem& CallFunc_SGK_InvSlotItem_InvItem);
	void UpdateCookingTimes(const struct FS_CookingRecipe& RecipeL, int32 IndexL, const struct FS_CookingSlot& ArrayElementL, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, bool CallFunc_Array_Contains_ReturnValue_1, int32 CallFunc_Array_Add_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem, bool CallFunc_SGK_ItemCookingRecipe_ReturnValue, const struct FS_CookingRecipe& CallFunc_SGK_ItemCookingRecipe_CookingRecipe, int32 Temp_int_Array_Index_Variable, const struct FS_InvSlot& CallFunc_Array_Get_Item, int32 Temp_int_Loop_Counter_Variable, const struct FS_InvSlot& CallFunc_Array_Get_Item_1, int32 CallFunc_Add_IntInt_ReturnValue, const struct FS_InvSlot& CallFunc_Array_Get_Item_2, int32 CallFunc_Subtract_IntInt_ReturnValue, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem_1, bool CallFunc_SGK_ItemCookingRecipe_ReturnValue_1, const struct FS_CookingRecipe& CallFunc_SGK_ItemCookingRecipe_CookingRecipe_1, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem_2, const struct FS_CookingSlot& K2Node_MakeStruct_S_CookingSlot, bool CallFunc_SGK_ItemCookingRecipe_ReturnValue_2, const struct FS_CookingRecipe& CallFunc_SGK_ItemCookingRecipe_CookingRecipe_2, const struct FS_InvSlot& CallFunc_Array_Get_Item_3, int32 CallFunc_Subtract_IntInt_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue_2, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem_3, bool CallFunc_SGK_ItemCookingRecipe_ReturnValue_3, const struct FS_CookingRecipe& CallFunc_SGK_ItemCookingRecipe_CookingRecipe_3, const struct FS_CookingSlot& K2Node_MakeStruct_S_CookingSlot_1, int32 CallFunc_Subtract_IntInt_ReturnValue_3, bool CallFunc_Greater_IntInt_ReturnValue_1, double CallFunc_Subtract_DoubleDouble_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue_1, const struct FS_CookingSlot& CallFunc_Array_Get_Item_4, bool CallFunc_Greater_DoubleDouble_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, double CallFunc_Subtract_DoubleDouble_A_ImplicitCast, float K2Node_SetFieldsInStruct_Time_6_51E1F19A4EC9904979CC80B79F2EEE7B_ImplicitCast, double CallFunc_Subtract_DoubleDouble_A_ImplicitCast_1);
	void IsCookingSlot(int32 Index, bool* IsCookingSlot, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool CallFunc_GreaterEqual_IntInt_ReturnValue);
	void RestartPlayerCookingSlot(const struct FS_CookingSlot& CookingSlot, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UBP_PlayerInventory_C* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void ClearCookingItem(const struct FS_InvSlot& InvSlot, struct FS_CookingSlot* CookingSlot, const struct FS_CookingSlot& CallFunc_Array_Get_Item, const struct FS_CookingSlot& K2Node_MakeStruct_S_CookingSlot);
	void StartPlayerCookingSlot(const struct FS_CookingSlot& CookingSlot, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UBP_PlayerInventory_C* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void UpdateCookingItems(const struct FS_InvSlot& ContentsElementL, const struct FS_CookingSlot& CookingElementL, const struct FS_InvSlot& ArrayElementL, const struct FS_InvSlot& CallFunc_Array_Get_Item, bool CallFunc_SetNewCookingItem_ReturnValue, const struct FS_CookingSlot& CallFunc_SetNewCookingItem_CookingSlot, bool CallFunc_GetContentsSlots_ReturnValue, TArray<struct FS_InvSlot>& CallFunc_GetContentsSlots_ContentsSlots, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable_1, bool CallFunc_SGK_InvSlotAmount_ItemValid, int32 CallFunc_SGK_InvSlotAmount_Amount, bool CallFunc_SGK_ItemCookingRecipe_ReturnValue, const struct FS_CookingRecipe& CallFunc_SGK_ItemCookingRecipe_CookingRecipe, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_Set_Contains_ReturnValue, int32 Temp_int_Array_Index_Variable_1, bool Temp_bool_True_if_break_was_hit_Variable, const struct FS_InvSlot& CallFunc_Array_Get_Item_1, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, const struct FS_CookingSlot& CallFunc_ClearCookingItem_CookingSlot, bool CallFunc_Array_IsValidIndex_ReturnValue, bool CallFunc_SetNewCookingItem_ReturnValue_1, const struct FS_CookingSlot& CallFunc_SetNewCookingItem_CookingSlot_1, bool CallFunc_SGK_InvSlotAmount_ItemValid_1, int32 CallFunc_SGK_InvSlotAmount_Amount_1, bool CallFunc_SGK_InvSlotAmount_ItemValid_2, int32 CallFunc_SGK_InvSlotAmount_Amount_2, const struct FS_CookingSlot& K2Node_MakeStruct_S_CookingSlot, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_EqualEqual_NameName_ReturnValue, const struct FS_CookingSlot& CallFunc_Array_Get_Item_2, bool CallFunc_GetCookingInvSlots_ReturnValue, TArray<struct FS_InvSlot>& CallFunc_GetCookingInvSlots_CookingSlots, const struct FS_InvSlot& CallFunc_Array_Get_Item_3, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1);
	void PauseAllPlayerCookingSlots(int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UBP_PlayerInventory_C* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue);
	void ResumeAllPlayerCookingSlots(class UBP_PlayerInventory_C* UsingPlayerL, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, bool CallFunc_IsValid_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, const struct FS_CookingSlot& CallFunc_Array_Get_Item, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class UBP_PlayerInventory_C* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1);
	bool GetCookingInvSlots(TArray<struct FS_InvSlot>* CookingSlots, const TArray<struct FS_InvSlot>& CookingSlotsL, int32 ArrayIndexL, const struct FS_InvSlot& ArrayElementL, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, const struct FS_InvSlot& CallFunc_Array_Get_Item, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_3);
	bool GetContentsSlots(TArray<struct FS_InvSlot>* ContentsSlots, const TArray<struct FS_InvSlot>& ContentsSlotsL, int32 ArrayIndexL, const struct FS_InvSlot& ArrayElementL, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool Temp_bool_Variable, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_2, int32 CallFunc_Subtract_IntInt_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue_4, int32 CallFunc_Subtract_IntInt_ReturnValue_5, int32 K2Node_Select_Default, bool CallFunc_LessEqual_IntInt_ReturnValue);
	bool GetFuelSlots(TArray<struct FS_InvSlot>* FuelSlots, const TArray<struct FS_InvSlot>& FuelSlotsL, int32 ArrayIndexL, int32 LastIndexL, int32 StartIndexL, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue_3, int32 CallFunc_Subtract_IntInt_ReturnValue_4, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 CallFunc_Subtract_IntInt_ReturnValue_5, int32 CallFunc_Add_IntInt_ReturnValue_3, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_6, int32 CallFunc_Add_IntInt_ReturnValue_4, int32 CallFunc_Subtract_IntInt_ReturnValue_7, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_5, bool CallFunc_Greater_IntInt_ReturnValue, const struct FS_InvSlot& CallFunc_Array_Get_Item, int32 CallFunc_Array_Add_ReturnValue);
	void IsFuelItem(class FName ItemId, bool* IsFuelItem, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, const struct FDataTableRowHandle& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_NameName_ReturnValue);
	void IsIndexFuelSlot(int32 Index, bool* IsFuelSlot, int32 SlotsL, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_2, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 CallFunc_Subtract_IntInt_ReturnValue_3);
	bool UpdateFuelBurn(bool ReturnValueL, bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_K2_IsValidTimerHandle_ReturnValue, bool CallFunc_GetFuelSlots_ReturnValue, TArray<struct FS_InvSlot>& CallFunc_GetFuelSlots_FuelSlots, const struct FS_InvSlot& CallFunc_Array_Get_Item, bool CallFunc_SGK_InvSlotAmount_ItemValid, int32 CallFunc_SGK_InvSlotAmount_Amount, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
	void BurnFuel(bool ReturnValueL, const struct FS_InvSlot& ArrayElementL, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, const struct FS_InvItem& CallFunc_SGK_InvSlotItem_InvItem, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, bool Temp_bool_True_if_break_was_hit_Variable, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_SGK_InvSlotAmount_ItemValid, int32 CallFunc_SGK_InvSlotAmount_Amount, bool CallFunc_SGK_InvSlotAmount_ItemValid_1, int32 CallFunc_SGK_InvSlotAmount_Amount_1, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_GetFuelSlots_ReturnValue, TArray<struct FS_InvSlot>& CallFunc_GetFuelSlots_FuelSlots, const struct FS_InvSlot& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, double CallFunc_ServerBurnFuel_Time_ImplicitCast);
	void ConstructContainsSlots(int32 ExtraSlotsL, int32 IndexL, int32 Bop, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem, int32 Temp_int_Variable, int32 Temp_int_Variable_1, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem_1, int32 Temp_int_Variable_2, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem_2, int32 Temp_int_Variable_3, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 Temp_int_Variable_4, int32 CallFunc_Add_IntInt_ReturnValue_3, bool Temp_bool_Variable, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue_2, int32 CallFunc_Subtract_IntInt_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_4, int32 CallFunc_Add_IntInt_ReturnValue_5, int32 Temp_int_Variable_5, int32 CallFunc_Subtract_IntInt_ReturnValue_4, int32 CallFunc_Add_IntInt_ReturnValue_6, int32 CallFunc_Add_IntInt_ReturnValue_7, bool CallFunc_LessEqual_IntInt_ReturnValue_1, const struct FS_InvSlot& K2Node_MakeStruct_S_InvSlot, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem_3, int32 CallFunc_Add_IntInt_ReturnValue_8, int32 CallFunc_Subtract_IntInt_ReturnValue_5, bool CallFunc_LessEqual_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_9, const struct FS_InvSlot& K2Node_MakeStruct_S_InvSlot_1, int32 Temp_int_Variable_6, const struct FS_InvSlot& K2Node_MakeStruct_S_InvSlot_2, int32 CallFunc_Add_IntInt_ReturnValue_10, float CallFunc_Conv_IntToFloat_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_11, float CallFunc_Conv_IntToFloat_ReturnValue_1, double CallFunc_FMod_Remainder, int32 CallFunc_FMod_ReturnValue, int32 CallFunc_FTrunc_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_6, int32 CallFunc_Subtract_IntInt_ReturnValue_7, bool CallFunc_Greater_DoubleDouble_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_8, int32 CallFunc_Subtract_IntInt_ReturnValue_9, int32 CallFunc_Add_IntInt_ReturnValue_12, const struct FS_InvSlot& K2Node_MakeStruct_S_InvSlot_3, int32 CallFunc_Subtract_IntInt_ReturnValue_10, int32 K2Node_Select_Default, bool CallFunc_LessEqual_IntInt_ReturnValue_3, double CallFunc_FMod_Divisor_ImplicitCast, double CallFunc_FMod_Dividend_ImplicitCast);
	void ConstructCookingSlots(int32 Temp_int_Variable, const struct FS_CookingSlot& K2Node_MakeStruct_S_CookingSlot, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue);
	void ServerConvertTimerCheck();
	void ReceiveBeginPlay();
	void ConstructSlots();
	void SaveComponentData(class UBP_SGKSaveGame_C* SaveGame);
	void LoadInventoryData(struct FS_StorageSave& S_StorageSave);
	void SGK_ItemMovedInInventory();
	void ServerBurnFuel(double Time);
	void TurnOn();
	void ClientResumeAllConvertSlots();
	void ClientPauseAllCookingSlotTimer();
	void ServerPauseBurnFuel();
	void ServerStartFuelBurn();
	void ServerStopBurningFuel();
	void SGK_ToggleComponent();
	void SGK_UpdateSpecialSlot(const struct FS_InvSlot& InvSlot);
	void ExecuteUbergraph_BP_CookingComponent(int32 EntryPoint, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, const struct FTimerHandle& CallFunc_K2_SetTimerDelegate_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, class UBP_SGKSaveGame_C* K2Node_Event_SaveGame, const struct FS_StorageSave& K2Node_Event_S_StorageSave, int32 Temp_int_Array_Index_Variable, double K2Node_CustomEvent_Time, const struct FTimerHandle& CallFunc_K2_SetTimer_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_1, class AActor* CallFunc_GetOwner_ReturnValue_2, TScriptInterface<class IBP_SGKInteractionInterface_C> K2Node_DynamicCast_AsBP_SGKInteraction_Interface, bool K2Node_DynamicCast_bSuccess, TScriptInterface<class IBP_SGKInteractionInterface_C> K2Node_DynamicCast_AsBP_SGKInteraction_Interface_1, bool K2Node_DynamicCast_bSuccess_1, class AActor* CallFunc_GetOwner_ReturnValue_3, TScriptInterface<class IBP_SGKInteractionInterface_C> K2Node_DynamicCast_AsBP_SGKInteraction_Interface_2, bool K2Node_DynamicCast_bSuccess_2, bool CallFunc_UpdateFuelBurn_ReturnValue, bool CallFunc_K2_IsValidTimerHandle_ReturnValue, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, const struct FS_InvSlot& K2Node_Event_InvSlot, class UBP_PlayerInventory_C* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_IsCookingSlot_IsCookingSlot, float CallFunc_K2_SetTimer_Time_ImplicitCast);
};

}


