#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DestroyInterface

#include "Basic.hpp"

#include "BP_DestroyInterface_classes.hpp"
#include "BP_DestroyInterface_parameters.hpp"


namespace SDK
{

// Function BP_DestroyInterface.BP_DestroyInterface_C.ActorRef
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_MasterBuildPart_C*            BuildPartRef                                           (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void IBP_DestroyInterface_C::ActorRef(class ABP_MasterBuildPart_C** BuildPartRef)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DestroyInterface_C", "ActorRef");

	Params::BP_DestroyInterface_C_ActorRef Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (BuildPartRef != nullptr)
		*BuildPartRef = Parms.BuildPartRef;
}


// Function BP_DestroyInterface.BP_DestroyInterface_C.DestroyDetonate
// (Public, BlueprintCallable, BlueprintEvent)

void IBP_DestroyInterface_C::DestroyDetonate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DestroyInterface_C", "DestroyDetonate");

	UObject::ProcessEvent(Func, nullptr);
}

}

