#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FL_PMM_Savegame

#include "Basic.hpp"

#include "BP_FL_PMM_Savegame_classes.hpp"
#include "BP_FL_PMM_Savegame_parameters.hpp"


namespace SDK
{

// Function BP_FL_PMM_Savegame.BP_FL_PMM_Savegame_C.GetSavegameSlot
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class FString                           Savegame_Slot                                          (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UBP_FL_PMM_Savegame_C::GetSavegameSlot(class UObject* __WorldContext, class FString* Savegame_Slot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_FL_PMM_Savegame_C", "GetSavegameSlot");

	Params::BP_FL_PMM_Savegame_C_GetSavegameSlot Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (Savegame_Slot != nullptr)
		*Savegame_Slot = std::move(Parms.Savegame_Slot);
}


// Function BP_FL_PMM_Savegame.BP_FL_PMM_Savegame_C.PMM_DoesSaveGameExist
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UBP_FL_PMM_Savegame_C::PMM_DoesSaveGameExist(class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_FL_PMM_Savegame_C", "PMM_DoesSaveGameExist");

	Params::BP_FL_PMM_Savegame_C_PMM_DoesSaveGameExist Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_FL_PMM_Savegame.BP_FL_PMM_Savegame_C.PMM_GetSaveGameObject
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UBP_PMM_Savegame_C*               ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class UBP_PMM_Savegame_C* UBP_FL_PMM_Savegame_C::PMM_GetSaveGameObject(class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_FL_PMM_Savegame_C", "PMM_GetSaveGameObject");

	Params::BP_FL_PMM_Savegame_C_PMM_GetSaveGameObject Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_FL_PMM_Savegame.BP_FL_PMM_Savegame_C.PMM_LoadGame
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UBP_PMM_Savegame_C*               AsBP_PMM_Savegame                                      (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_FL_PMM_Savegame_C::PMM_LoadGame(class UObject* __WorldContext, class UBP_PMM_Savegame_C** AsBP_PMM_Savegame)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_FL_PMM_Savegame_C", "PMM_LoadGame");

	Params::BP_FL_PMM_Savegame_C_PMM_LoadGame Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (AsBP_PMM_Savegame != nullptr)
		*AsBP_PMM_Savegame = Parms.AsBP_PMM_Savegame;
}


// Function BP_FL_PMM_Savegame.BP_FL_PMM_Savegame_C.PMM_SaveGame
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBP_PMM_Savegame_C*               SaveGameObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UBP_FL_PMM_Savegame_C::PMM_SaveGame(class UBP_PMM_Savegame_C* SaveGameObject, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_FL_PMM_Savegame_C", "PMM_SaveGame");

	Params::BP_FL_PMM_Savegame_C_PMM_SaveGame Parms{};

	Parms.SaveGameObject = SaveGameObject;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_FL_PMM_Savegame.BP_FL_PMM_Savegame_C.Save_Settings_Language
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Settings_Language                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UBP_FL_PMM_Savegame_C::Save_Settings_Language(const class FString& Settings_Language, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_FL_PMM_Savegame_C", "Save_Settings_Language");

	Params::BP_FL_PMM_Savegame_C_Save_Settings_Language Parms{};

	Parms.Settings_Language = std::move(Settings_Language);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

