#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GearOptionsMenu

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"
#include "S_ContainerDetails_structs.hpp"
#include "S_EquipmentSlotID_structs.hpp"


namespace SDK::Params
{

// Function BP_GearOptionsMenu.BP_GearOptionsMenu_C.ExecuteUbergraph_BP_GearOptionsMenu
// 0x00C0 (0x00C0 - 0x0000)
struct BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SGK_ItemContainerDetails_ItemFound;       // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_530A[0x6];                                     // 0x000A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FS_ContainerDetails                    CallFunc_SGK_ItemContainerDetails_ItemContainerDetails; // 0x0010(0x0070)(ContainsInstancedReference, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0081(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0082(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_530B[0x5];                                     // 0x0083(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_PlayerInventory_C*                  CallFunc_GetComponentByClass_ReturnValue;          // 0x0090(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_1;                           // 0x009A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_530C[0x5];                                     // 0x009B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FS_EquipmentSlotID                     K2Node_MakeStruct_S_EquipmentSlotID;               // 0x00A0(0x0010)(ZeroConstructor, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FS_EquipmentSlotID                     K2Node_MakeStruct_S_EquipmentSlotID_1;             // 0x00B0(0x0010)(ZeroConstructor, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
};
static_assert(alignof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu) == 0x000008, "Wrong alignment on BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu");
static_assert(sizeof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu) == 0x0000C0, "Wrong size on BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, EntryPoint) == 0x000000, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, Temp_bool_Variable) == 0x000004, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, Temp_bool_Variable_1) == 0x000005, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, Temp_byte_Variable) == 0x000006, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, Temp_byte_Variable_1) == 0x000007, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, Temp_byte_Variable_2) == 0x000008, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, CallFunc_SGK_ItemContainerDetails_ItemFound) == 0x000009, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::CallFunc_SGK_ItemContainerDetails_ItemFound' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, CallFunc_SGK_ItemContainerDetails_ItemContainerDetails) == 0x000010, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::CallFunc_SGK_ItemContainerDetails_ItemContainerDetails' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000080, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, CallFunc_BooleanAND_ReturnValue) == 0x000081, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, K2Node_Select_Default) == 0x000082, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, CallFunc_GetOwningPlayer_ReturnValue) == 0x000088, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, CallFunc_GetComponentByClass_ReturnValue) == 0x000090, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, CallFunc_IsValid_ReturnValue) == 0x000098, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, Temp_byte_Variable_3) == 0x000099, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, K2Node_Select_Default_1) == 0x00009A, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, K2Node_MakeStruct_S_EquipmentSlotID) == 0x0000A0, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::K2Node_MakeStruct_S_EquipmentSlotID' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu, K2Node_MakeStruct_S_EquipmentSlotID_1) == 0x0000B0, "Member 'BP_GearOptionsMenu_C_ExecuteUbergraph_BP_GearOptionsMenu::K2Node_MakeStruct_S_EquipmentSlotID_1' has a wrong offset!");

// Function BP_GearOptionsMenu.BP_GearOptionsMenu_C.OnMouseButtonDown
// 0x0248 (0x0248 - 0x0000)
struct BP_GearOptionsMenu_C_OnMouseButtonDown final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FPointerEvent                          MouseEvent;                                        // 0x0040(0x0098)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FEventReply                            ReturnValue;                                       // 0x00D8(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x0190(0x00B8)()
};
static_assert(alignof(BP_GearOptionsMenu_C_OnMouseButtonDown) == 0x000008, "Wrong alignment on BP_GearOptionsMenu_C_OnMouseButtonDown");
static_assert(sizeof(BP_GearOptionsMenu_C_OnMouseButtonDown) == 0x000248, "Wrong size on BP_GearOptionsMenu_C_OnMouseButtonDown");
static_assert(offsetof(BP_GearOptionsMenu_C_OnMouseButtonDown, MyGeometry) == 0x000000, "Member 'BP_GearOptionsMenu_C_OnMouseButtonDown::MyGeometry' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_OnMouseButtonDown, MouseEvent) == 0x000040, "Member 'BP_GearOptionsMenu_C_OnMouseButtonDown::MouseEvent' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_OnMouseButtonDown, ReturnValue) == 0x0000D8, "Member 'BP_GearOptionsMenu_C_OnMouseButtonDown::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GearOptionsMenu_C_OnMouseButtonDown, CallFunc_Handled_ReturnValue) == 0x000190, "Member 'BP_GearOptionsMenu_C_OnMouseButtonDown::CallFunc_Handled_ReturnValue' has a wrong offset!");

}

