#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InventoryGrid_11

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_InventoryGrid_11.BP_InventoryGrid_11_C.ExecuteUbergraph_BP_InventoryGrid_11
// 0x0028 (0x0028 - 0x0000)
struct BP_InventoryGrid_11_C_ExecuteUbergraph_BP_InventoryGrid_11 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5869[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UBP_InventoryCell_C*>            K2Node_MakeArray_Array;                            // 0x0008(0x0010)(ReferenceParm, ContainsInstancedReference)
	TArray<class UBP_InventoryItemIcon_C*>        K2Node_MakeArray_Array_1;                          // 0x0018(0x0010)(ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(BP_InventoryGrid_11_C_ExecuteUbergraph_BP_InventoryGrid_11) == 0x000008, "Wrong alignment on BP_InventoryGrid_11_C_ExecuteUbergraph_BP_InventoryGrid_11");
static_assert(sizeof(BP_InventoryGrid_11_C_ExecuteUbergraph_BP_InventoryGrid_11) == 0x000028, "Wrong size on BP_InventoryGrid_11_C_ExecuteUbergraph_BP_InventoryGrid_11");
static_assert(offsetof(BP_InventoryGrid_11_C_ExecuteUbergraph_BP_InventoryGrid_11, EntryPoint) == 0x000000, "Member 'BP_InventoryGrid_11_C_ExecuteUbergraph_BP_InventoryGrid_11::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_InventoryGrid_11_C_ExecuteUbergraph_BP_InventoryGrid_11, K2Node_MakeArray_Array) == 0x000008, "Member 'BP_InventoryGrid_11_C_ExecuteUbergraph_BP_InventoryGrid_11::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_InventoryGrid_11_C_ExecuteUbergraph_BP_InventoryGrid_11, K2Node_MakeArray_Array_1) == 0x000018, "Member 'BP_InventoryGrid_11_C_ExecuteUbergraph_BP_InventoryGrid_11::K2Node_MakeArray_Array_1' has a wrong offset!");

}

