#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InventoryGrid

#include "Basic.hpp"

#include "BP_InventoryGrid_classes.hpp"
#include "BP_InventoryGrid_parameters.hpp"


namespace SDK
{

// Function BP_InventoryGrid.BP_InventoryGrid_C.ClearInvGrid
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_InventoryGrid_C::ClearInvGrid()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InventoryGrid_C", "ClearInvGrid");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InventoryGrid.BP_InventoryGrid_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_InventoryGrid_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InventoryGrid_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InventoryGrid.BP_InventoryGrid_C.ConstructInvGrid
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Preview                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_InventoryGrid_C::ConstructInvGrid(bool Preview)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InventoryGrid_C", "ConstructInvGrid");

	Params::BP_InventoryGrid_C_ConstructInvGrid Parms{};

	Parms.Preview = Preview;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InventoryGrid.BP_InventoryGrid_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_InventoryGrid_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InventoryGrid_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InventoryGrid.BP_InventoryGrid_C.ExecuteUbergraph_BP_InventoryGrid
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_InventoryGrid_C::ExecuteUbergraph_BP_InventoryGrid(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InventoryGrid_C", "ExecuteUbergraph_BP_InventoryGrid");

	Params::BP_InventoryGrid_C_ExecuteUbergraph_BP_InventoryGrid Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InventoryGrid.BP_InventoryGrid_C.GetCellCount
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   InventoryCells                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_InventoryGrid_C::GetCellCount(int32* InventoryCells)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InventoryGrid_C", "GetCellCount");

	Params::BP_InventoryGrid_C_GetCellCount Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (InventoryCells != nullptr)
		*InventoryCells = Parms.InventoryCells;
}


// Function BP_InventoryGrid.BP_InventoryGrid_C.GetInvColumns
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Columns                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_InventoryGrid_C::GetInvColumns(int32* Columns)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InventoryGrid_C", "GetInvColumns");

	Params::BP_InventoryGrid_C_GetInvColumns Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Columns != nullptr)
		*Columns = Parms.Columns;
}


// Function BP_InventoryGrid.BP_InventoryGrid_C.SGK CellSlots
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UBP_InventoryCell_C*>      Cells                                                  (Parm, OutParm, ContainsInstancedReference)

void UBP_InventoryGrid_C::SGK_CellSlots(TArray<class UBP_InventoryCell_C*>* Cells)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InventoryGrid_C", "SGK CellSlots");

	Params::BP_InventoryGrid_C_SGK_CellSlots Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Cells != nullptr)
		*Cells = std::move(Parms.Cells);
}


// Function BP_InventoryGrid.BP_InventoryGrid_C.SGK ConstructGrid
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBP_MasterInventory_C*            Param_GridInventory                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBP_InventoryGrid_C::SGK_ConstructGrid(class UBP_MasterInventory_C* Param_GridInventory)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InventoryGrid_C", "SGK ConstructGrid");

	Params::BP_InventoryGrid_C_SGK_ConstructGrid Parms{};

	Parms.Param_GridInventory = Param_GridInventory;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InventoryGrid.BP_InventoryGrid_C.SGK InvItemSlots
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UBP_InventoryItemIcon_C*>  ItemInvWidgets                                         (Parm, OutParm, ContainsInstancedReference)

void UBP_InventoryGrid_C::SGK_InvItemSlots(TArray<class UBP_InventoryItemIcon_C*>* ItemInvWidgets)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InventoryGrid_C", "SGK InvItemSlots");

	Params::BP_InventoryGrid_C_SGK_InvItemSlots Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ItemInvWidgets != nullptr)
		*ItemInvWidgets = std::move(Parms.ItemInvWidgets);
}

}

