#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MultiplayerMenu

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "BP_MasterMenuPanel_classes.hpp"
#include "Engine_structs.hpp"
#include "E_WidgetToggleType_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_MultiplayerMenu.BP_MultiplayerMenu_C
// 0x0128 (0x0428 - 0x0300)
class UBP_MultiplayerMenu_C final : public UBP_MasterMenuPanel_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_MultiplayerMenu_C;               // 0x0300(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                Backround;                                         // 0x0308(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_MenuButton_C*                       BP_WidgetToggleButton;                             // 0x0310(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_MenuButton_C*                       BP_WidgetToggleButton_2;                           // 0x0318(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_MenuButton_C*                       BP_WidgetToggleButton_149;                         // 0x0320(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Subtitle;                                          // 0x0328(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Title;                                             // 0x0330(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FLinearColor                           BackroundColor;                                    // 0x0338(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   TitleText;                                         // 0x0348(0x0018)(Edit, BlueprintVisible)
	class FText                                   SubtitleText;                                      // 0x0360(0x0018)(Edit, BlueprintVisible)
	struct FSlateFontInfo                         TitleFont;                                         // 0x0378(0x0058)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FSlateFontInfo                         SubtitleFont;                                      // 0x03D0(0x0058)(Edit, BlueprintVisible, HasGetValueTypeHash)

public:
	void BindOnClicked(E_WidgetToggleType WidgetToggleType);
	void Construct();
	void ExecuteUbergraph_BP_MultiplayerMenu(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MultiplayerMenu_C">();
	}
	static class UBP_MultiplayerMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MultiplayerMenu_C>();
	}
};
static_assert(alignof(UBP_MultiplayerMenu_C) == 0x000008, "Wrong alignment on UBP_MultiplayerMenu_C");
static_assert(sizeof(UBP_MultiplayerMenu_C) == 0x000428, "Wrong size on UBP_MultiplayerMenu_C");
static_assert(offsetof(UBP_MultiplayerMenu_C, UberGraphFrame_BP_MultiplayerMenu_C) == 0x000300, "Member 'UBP_MultiplayerMenu_C::UberGraphFrame_BP_MultiplayerMenu_C' has a wrong offset!");
static_assert(offsetof(UBP_MultiplayerMenu_C, Backround) == 0x000308, "Member 'UBP_MultiplayerMenu_C::Backround' has a wrong offset!");
static_assert(offsetof(UBP_MultiplayerMenu_C, BP_WidgetToggleButton) == 0x000310, "Member 'UBP_MultiplayerMenu_C::BP_WidgetToggleButton' has a wrong offset!");
static_assert(offsetof(UBP_MultiplayerMenu_C, BP_WidgetToggleButton_2) == 0x000318, "Member 'UBP_MultiplayerMenu_C::BP_WidgetToggleButton_2' has a wrong offset!");
static_assert(offsetof(UBP_MultiplayerMenu_C, BP_WidgetToggleButton_149) == 0x000320, "Member 'UBP_MultiplayerMenu_C::BP_WidgetToggleButton_149' has a wrong offset!");
static_assert(offsetof(UBP_MultiplayerMenu_C, Subtitle) == 0x000328, "Member 'UBP_MultiplayerMenu_C::Subtitle' has a wrong offset!");
static_assert(offsetof(UBP_MultiplayerMenu_C, Title) == 0x000330, "Member 'UBP_MultiplayerMenu_C::Title' has a wrong offset!");
static_assert(offsetof(UBP_MultiplayerMenu_C, BackroundColor) == 0x000338, "Member 'UBP_MultiplayerMenu_C::BackroundColor' has a wrong offset!");
static_assert(offsetof(UBP_MultiplayerMenu_C, TitleText) == 0x000348, "Member 'UBP_MultiplayerMenu_C::TitleText' has a wrong offset!");
static_assert(offsetof(UBP_MultiplayerMenu_C, SubtitleText) == 0x000360, "Member 'UBP_MultiplayerMenu_C::SubtitleText' has a wrong offset!");
static_assert(offsetof(UBP_MultiplayerMenu_C, TitleFont) == 0x000378, "Member 'UBP_MultiplayerMenu_C::TitleFont' has a wrong offset!");
static_assert(offsetof(UBP_MultiplayerMenu_C, SubtitleFont) == 0x0003D0, "Member 'UBP_MultiplayerMenu_C::SubtitleFont' has a wrong offset!");

}

