#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MasterMeleeWeapon

#include "Basic.hpp"

#include "BP_MasterMeleeWeapon_classes.hpp"
#include "BP_MasterMeleeWeapon_parameters.hpp"


namespace SDK
{

// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.ExecuteUbergraph_BP_MasterMeleeWeapon
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MasterMeleeWeapon_C::ExecuteUbergraph_BP_MasterMeleeWeapon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "ExecuteUbergraph_BP_MasterMeleeWeapon");

	Params::BP_MasterMeleeWeapon_C_ExecuteUbergraph_BP_MasterMeleeWeapon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.MulticastMeleeAttackMontage
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   AnimIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MasterMeleeWeapon_C::MulticastMeleeAttackMontage(int32 AnimIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "MulticastMeleeAttackMontage");

	Params::BP_MasterMeleeWeapon_C_MulticastMeleeAttackMontage Parms{};

	Parms.AnimIndex = AnimIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.OnBlendOut_1830005C47917F94146466A299473C2F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MasterMeleeWeapon_C::OnBlendOut_1830005C47917F94146466A299473C2F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "OnBlendOut_1830005C47917F94146466A299473C2F");

	Params::BP_MasterMeleeWeapon_C_OnBlendOut_1830005C47917F94146466A299473C2F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.OnBlendOut_F410FBF64DC7B024F21B25AE37B2912E
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MasterMeleeWeapon_C::OnBlendOut_F410FBF64DC7B024F21B25AE37B2912E(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "OnBlendOut_F410FBF64DC7B024F21B25AE37B2912E");

	Params::BP_MasterMeleeWeapon_C_OnBlendOut_F410FBF64DC7B024F21B25AE37B2912E Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.OnCompleted_1830005C47917F94146466A299473C2F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MasterMeleeWeapon_C::OnCompleted_1830005C47917F94146466A299473C2F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "OnCompleted_1830005C47917F94146466A299473C2F");

	Params::BP_MasterMeleeWeapon_C_OnCompleted_1830005C47917F94146466A299473C2F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.OnCompleted_F410FBF64DC7B024F21B25AE37B2912E
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MasterMeleeWeapon_C::OnCompleted_F410FBF64DC7B024F21B25AE37B2912E(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "OnCompleted_F410FBF64DC7B024F21B25AE37B2912E");

	Params::BP_MasterMeleeWeapon_C_OnCompleted_F410FBF64DC7B024F21B25AE37B2912E Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.OnInterrupted_1830005C47917F94146466A299473C2F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MasterMeleeWeapon_C::OnInterrupted_1830005C47917F94146466A299473C2F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "OnInterrupted_1830005C47917F94146466A299473C2F");

	Params::BP_MasterMeleeWeapon_C_OnInterrupted_1830005C47917F94146466A299473C2F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.OnInterrupted_F410FBF64DC7B024F21B25AE37B2912E
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MasterMeleeWeapon_C::OnInterrupted_F410FBF64DC7B024F21B25AE37B2912E(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "OnInterrupted_F410FBF64DC7B024F21B25AE37B2912E");

	Params::BP_MasterMeleeWeapon_C_OnInterrupted_F410FBF64DC7B024F21B25AE37B2912E Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.OnNotifyBegin_1830005C47917F94146466A299473C2F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MasterMeleeWeapon_C::OnNotifyBegin_1830005C47917F94146466A299473C2F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "OnNotifyBegin_1830005C47917F94146466A299473C2F");

	Params::BP_MasterMeleeWeapon_C_OnNotifyBegin_1830005C47917F94146466A299473C2F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.OnNotifyBegin_F410FBF64DC7B024F21B25AE37B2912E
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MasterMeleeWeapon_C::OnNotifyBegin_F410FBF64DC7B024F21B25AE37B2912E(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "OnNotifyBegin_F410FBF64DC7B024F21B25AE37B2912E");

	Params::BP_MasterMeleeWeapon_C_OnNotifyBegin_F410FBF64DC7B024F21B25AE37B2912E Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.OnNotifyEnd_1830005C47917F94146466A299473C2F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MasterMeleeWeapon_C::OnNotifyEnd_1830005C47917F94146466A299473C2F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "OnNotifyEnd_1830005C47917F94146466A299473C2F");

	Params::BP_MasterMeleeWeapon_C_OnNotifyEnd_1830005C47917F94146466A299473C2F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.OnNotifyEnd_F410FBF64DC7B024F21B25AE37B2912E
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MasterMeleeWeapon_C::OnNotifyEnd_F410FBF64DC7B024F21B25AE37B2912E(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "OnNotifyEnd_F410FBF64DC7B024F21B25AE37B2912E");

	Params::BP_MasterMeleeWeapon_C_OnNotifyEnd_F410FBF64DC7B024F21B25AE37B2912E Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.RandomMeleeAttackAnimation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAnimMontage*                     AttackAnimation                                        (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_MasterMeleeWeapon_C::RandomMeleeAttackAnimation(class UAnimMontage** AttackAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "RandomMeleeAttackAnimation");

	Params::BP_MasterMeleeWeapon_C_RandomMeleeAttackAnimation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AttackAnimation != nullptr)
		*AttackAnimation = Parms.AttackAnimation;
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.ResetSwing
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_MasterMeleeWeapon_C::ResetSwing()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "ResetSwing");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.SGK MeleeCollisionToggle
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    TraceOn                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MasterMeleeWeapon_C::SGK_MeleeCollisionToggle(bool TraceOn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "SGK MeleeCollisionToggle");

	Params::BP_MasterMeleeWeapon_C_SGK_MeleeCollisionToggle Parms{};

	Parms.TraceOn = TraceOn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.SGK ResetHoldable
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_MasterMeleeWeapon_C::SGK_ResetHoldable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "SGK ResetHoldable");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.SGK ServerPrimaryAction
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    KeyDown                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MasterMeleeWeapon_C::SGK_ServerPrimaryAction(bool KeyDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "SGK ServerPrimaryAction");

	Params::BP_MasterMeleeWeapon_C_SGK_ServerPrimaryAction Parms{};

	Parms.KeyDown = KeyDown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MasterMeleeWeapon.BP_MasterMeleeWeapon_C.SweepTrace
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_MasterMeleeWeapon_C::SweepTrace()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterMeleeWeapon_C", "SweepTrace");

	UObject::ProcessEvent(Func, nullptr);
}

}

