#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_P1911MagazineAttach

#include "Basic.hpp"

#include "BP_MasterAttachment_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_P1911MagazineAttach.BP_P1911MagazineAttach_C
// 0x0008 (0x0378 - 0x0370)
class ABP_P1911MagazineAttach_C final : public ABP_MasterAttachment_C
{
public:
	class UStaticMeshComponent*                   Magazine;                                          // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_P1911MagazineAttach_C">();
	}
	static class ABP_P1911MagazineAttach_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_P1911MagazineAttach_C>();
	}
};
static_assert(alignof(ABP_P1911MagazineAttach_C) == 0x000008, "Wrong alignment on ABP_P1911MagazineAttach_C");
static_assert(sizeof(ABP_P1911MagazineAttach_C) == 0x000378, "Wrong size on ABP_P1911MagazineAttach_C");
static_assert(offsetof(ABP_P1911MagazineAttach_C, Magazine) == 0x000370, "Member 'ABP_P1911MagazineAttach_C::Magazine' has a wrong offset!");

}

