#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_QuickSlotsPanel

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_QuickSlotsPanel.BP_QuickSlotsPanel_C
// 0x0078 (0x02F0 - 0x0278)
class UBP_QuickSlotsPanel_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image;                                             // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_131;                                         // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         QSPanelHorizontalBox;                              // 0x0290(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PlayerInventory_C*                  PlayerInventory;                                   // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           BackroundColor;                                    // 0x02A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              QuickSlotSize;                                     // 0x02B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        WidthPadding;                                      // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         QuickSlots__PreviewOnly_;                          // 0x02C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5696[0x4];                                     // 0x02CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 QuickSlotKeyBindPrefex;                            // 0x02D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, AdvancedDisplay, HasGetValueTypeHash)
	TArray<class UBP_QuickSlot_C*>                QuickSlots;                                        // 0x02E0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)

public:
	void AddQuickSlots(int32 AddAmount);
	void Construct();
	void ConstructQuickSlots();
	void ExecuteUbergraph_BP_QuickSlotsPanel(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void RemoveQuickSlots(int32 Remove_Amount);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_QuickSlotsPanel_C">();
	}
	static class UBP_QuickSlotsPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_QuickSlotsPanel_C>();
	}
};
static_assert(alignof(UBP_QuickSlotsPanel_C) == 0x000008, "Wrong alignment on UBP_QuickSlotsPanel_C");
static_assert(sizeof(UBP_QuickSlotsPanel_C) == 0x0002F0, "Wrong size on UBP_QuickSlotsPanel_C");
static_assert(offsetof(UBP_QuickSlotsPanel_C, UberGraphFrame) == 0x000278, "Member 'UBP_QuickSlotsPanel_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_QuickSlotsPanel_C, Image) == 0x000280, "Member 'UBP_QuickSlotsPanel_C::Image' has a wrong offset!");
static_assert(offsetof(UBP_QuickSlotsPanel_C, Image_131) == 0x000288, "Member 'UBP_QuickSlotsPanel_C::Image_131' has a wrong offset!");
static_assert(offsetof(UBP_QuickSlotsPanel_C, QSPanelHorizontalBox) == 0x000290, "Member 'UBP_QuickSlotsPanel_C::QSPanelHorizontalBox' has a wrong offset!");
static_assert(offsetof(UBP_QuickSlotsPanel_C, PlayerInventory) == 0x000298, "Member 'UBP_QuickSlotsPanel_C::PlayerInventory' has a wrong offset!");
static_assert(offsetof(UBP_QuickSlotsPanel_C, BackroundColor) == 0x0002A0, "Member 'UBP_QuickSlotsPanel_C::BackroundColor' has a wrong offset!");
static_assert(offsetof(UBP_QuickSlotsPanel_C, QuickSlotSize) == 0x0002B0, "Member 'UBP_QuickSlotsPanel_C::QuickSlotSize' has a wrong offset!");
static_assert(offsetof(UBP_QuickSlotsPanel_C, WidthPadding) == 0x0002C0, "Member 'UBP_QuickSlotsPanel_C::WidthPadding' has a wrong offset!");
static_assert(offsetof(UBP_QuickSlotsPanel_C, QuickSlots__PreviewOnly_) == 0x0002C8, "Member 'UBP_QuickSlotsPanel_C::QuickSlots__PreviewOnly_' has a wrong offset!");
static_assert(offsetof(UBP_QuickSlotsPanel_C, QuickSlotKeyBindPrefex) == 0x0002D0, "Member 'UBP_QuickSlotsPanel_C::QuickSlotKeyBindPrefex' has a wrong offset!");
static_assert(offsetof(UBP_QuickSlotsPanel_C, QuickSlots) == 0x0002E0, "Member 'UBP_QuickSlotsPanel_C::QuickSlots' has a wrong offset!");

}

