#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x28 (0x2B8 - 0x290)
// BlueprintGeneratedClass BP_ResourceManager.BP_ResourceManager_C
class ABP_ResourceManager_C : public AActor
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x290(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                       DefaultSceneRoot;                                  // 0x298(0x8)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	enum class EDrawDebugTrace                   GetInstanceTraceVisibility;                        // 0x2A0(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_45C1[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TArray<struct FVector>                       RemovedInstances;                                  // 0x2A8(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)

	static class UClass* StaticClass();
	static class ABP_ResourceManager_C* GetDefaultObj();

	void LoadResourceSaves(class UBP_SGKSaveGame_C* SaveGame, int32 ResourceAmountL, class ABP_MasterResource_C* NewResourceL, class UBP_MasterResourceComponent_C* ResourceInstanceL, int32 Temp_int_Array_Index_Variable, bool CallFunc_IsStandalone_ReturnValue, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_SetStaticMesh_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, const class FString& CallFunc_GetCurrentLevelName_ReturnValue, bool CallFunc_FindResourceSaveData_SaveFound, TArray<struct FS_ResourcesSaves>& CallFunc_FindResourceSaveData_RemovedResources, const struct FS_ResourcesSaves& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, const struct FTransform& CallFunc_MakeTransform_ReturnValue, int32 CallFunc_Array_AddUnique_ReturnValue, bool CallFunc_GetInstanceAtTransform_ReturnValue, class UBP_MasterResourceComponent_C* CallFunc_GetInstanceAtTransform_ResourceInstance, int32 CallFunc_GetInstanceAtTransform_InstanceIndex, const struct FTransform& CallFunc_GetInstanceTransform_OutInstanceTransform, bool CallFunc_GetInstanceTransform_ReturnValue, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, class ABP_MasterResource_C* CallFunc_FinishSpawningActor_ReturnValue);
	void ReplaceInstance(class UFoliageInstancedStaticMeshComponent* FoliageInstance, int32 InstanceIndex, bool Interacted, class UBP_PlayerInventory_C* PlayerInventory, bool ResourceEmptyL, class ABP_MasterResource_C* ResourceL, const struct FTransform& InstanceTransformL, class ABP_MasterInteractableResource_C* K2Node_DynamicCast_AsBP_Master_Interactable_Resource, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue, const struct FVector& CallFunc_BreakTransform_Location, const struct FRotator& CallFunc_BreakTransform_Rotation, const struct FVector& CallFunc_BreakTransform_Scale, int32 CallFunc_Array_AddUnique_ReturnValue, const struct FTransform& CallFunc_GetInstanceTransform_OutInstanceTransform, bool CallFunc_GetInstanceTransform_ReturnValue, class UClass* CallFunc_GetObjectClass_ReturnValue, class ABP_MasterMeleeWeapon_C* K2Node_DynamicCast_AsBP_Master_Melee_Weapon, bool K2Node_DynamicCast_bSuccess_1, const struct FS_MinMax& CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, bool CallFunc_CollectResource_ResourceDepleted, int32 CallFunc_RandomIntegerInRange_ReturnValue, bool CallFunc_CollectResource_ResourceDepleted_1, bool CallFunc_SetStaticMesh_ReturnValue, class UBP_MasterResourceComponent_C* K2Node_DynamicCast_AsBP_Master_Resource_Component, bool K2Node_DynamicCast_bSuccess_2, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, class ABP_MasterResource_C* CallFunc_FinishSpawningActor_ReturnValue);
	bool GetInstanceAtTransform(const struct FTransform& Transform, class UStaticMesh* StaticMesh, class UBP_MasterResourceComponent_C** ResourceInstance, int32* InstanceIndex, bool Temp_bool_True_if_break_was_hit_Variable, const struct FVector& CallFunc_BreakTransform_Location, const struct FRotator& CallFunc_BreakTransform_Rotation, const struct FVector& CallFunc_BreakTransform_Scale, const struct FVector& CallFunc_Add_VectorVector_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Array_Index_Variable, const struct FVector& CallFunc_BreakTransform_Location_1, const struct FRotator& CallFunc_BreakTransform_Rotation_1, const struct FVector& CallFunc_BreakTransform_Scale_1, bool CallFunc_IsValid_ReturnValue, TArray<enum class EObjectTypeQuery>& K2Node_MakeArray_Array, TArray<class AActor*>& Temp_object_Variable, int32 Temp_int_Loop_Counter_Variable, TArray<struct FHitResult>& CallFunc_BoxTraceMultiForObjects_OutHits, bool CallFunc_BoxTraceMultiForObjects_ReturnValue, const struct FHitResult& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_BreakHitResult_bBlockingHit, bool CallFunc_BreakHitResult_bInitialOverlap, float CallFunc_BreakHitResult_Time, float CallFunc_BreakHitResult_Distance, const struct FVector& CallFunc_BreakHitResult_Location, const struct FVector& CallFunc_BreakHitResult_ImpactPoint, const struct FVector& CallFunc_BreakHitResult_Normal, const struct FVector& CallFunc_BreakHitResult_ImpactNormal, class UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, class AActor* CallFunc_BreakHitResult_HitActor, class UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, class FName CallFunc_BreakHitResult_HitBoneName, class FName CallFunc_BreakHitResult_BoneName, int32 CallFunc_BreakHitResult_HitItem, int32 CallFunc_BreakHitResult_ElementIndex, int32 CallFunc_BreakHitResult_FaceIndex, const struct FVector& CallFunc_BreakHitResult_TraceStart, const struct FVector& CallFunc_BreakHitResult_TraceEnd, bool CallFunc_Less_IntInt_ReturnValue, class UBP_MasterResourceComponent_C* K2Node_DynamicCast_AsBP_Master_Resource_Component, bool K2Node_DynamicCast_bSuccess, bool CallFunc_BooleanAND_ReturnValue, const struct FTransform& CallFunc_GetInstanceTransform_OutInstanceTransform, bool CallFunc_GetInstanceTransform_ReturnValue, const struct FVector& CallFunc_BreakTransform_Location_2, const struct FRotator& CallFunc_BreakTransform_Rotation_2, const struct FVector& CallFunc_BreakTransform_Scale_2, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_EqualEqual_VectorVector_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
	void RemoveInstance(const struct FTransform& Transform, class UStaticMesh* StaticMesh, int32 ResourceIndexL, class UBP_MasterResourceComponent_C* ResouceInstanceL, bool CallFunc_GetInstanceAtTransform_ReturnValue, class UBP_MasterResourceComponent_C* CallFunc_GetInstanceAtTransform_ResourceInstance, int32 CallFunc_GetInstanceAtTransform_InstanceIndex, bool CallFunc_RemoveInstance_ReturnValue, int32 CallFunc_GetInstanceCount_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue);
	void LoadResources(class UBP_SGKSaveGame_C* SaveGame);
	void ReceiveBeginPlay();
	void MulticastLoadSave(TArray<struct FVector>& Resource);
	void MulticastRemoveInstance(const struct FTransform& InstanceTransform, class UStaticMesh* StaticMesh, bool ResourceDepleted);
	void ExecuteUbergraph_BP_ResourceManager(int32 EntryPoint, const struct FTransform& K2Node_CustomEvent_InstanceTransform, class UStaticMesh* K2Node_CustomEvent_StaticMesh, bool K2Node_CustomEvent_ResourceDepleted, int32 Temp_int_Array_Index_Variable, class UBP_SGKSaveGame_C* K2Node_CustomEvent_SaveGame, int32 Temp_int_Loop_Counter_Variable, TArray<struct FVector>& K2Node_CustomEvent_Resource, const struct FVector& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, const struct FTransform& CallFunc_MakeTransform_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
};

}


