#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x50 (0x2C8 - 0x278)
// WidgetBlueprintGeneratedClass BP_ScalerSetting.BP_ScalerSetting_C
class UBP_ScalerSetting_C : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x278(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                               BackButton;                                        // 0x280(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                               NextButton;                                        // 0x288(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                            ScalerText;                                        // 0x290(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                        Selected;                                          // 0x298(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_3B66[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TArray<struct FS_Scaler>                     ScalerNames;                                       // 0x2A0(0x10)(Edit, BlueprintVisible)
	enum class E_ScalerSetting                   ScalerSettingType;                                 // 0x2B0(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         AutoApply;                                         // 0x2B1(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_3B67[0x6];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	FMulticastInlineDelegateProperty_            ValueChanged;                                      // 0x2B8(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

	static class UClass* StaticClass();
	static class UBP_ScalerSetting_C* GetDefaultObj();

	void NextOption(const struct FS_Scaler& CallFunc_CurrentSelection_Output, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_Array_IsValidIndex_ReturnValue);
	double CurrentSettingValue(enum class EWindowMode Temp_byte_Variable, double Temp_real_Variable, double Temp_real_Variable_1, double Temp_real_Variable_2, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, float CallFunc_Conv_IntToFloat_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_1, int32 CallFunc_GetShadowQuality_ReturnValue, bool CallFunc_IsVSyncEnabled_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue_1, float CallFunc_Conv_BoolToFloat_ReturnValue, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_2, enum class EWindowMode CallFunc_GetFullscreenMode_ReturnValue, const struct FS_Scaler& CallFunc_Array_Get_Item, double K2Node_Select_Default, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_3, float CallFunc_GetFrameRateLimit_ReturnValue, bool CallFunc_EqualEqual_DoubleDouble_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_4, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_5, int32 CallFunc_GetFoliageQuality_ReturnValue, int32 CallFunc_GetAudioQualityLevel_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue_2, float CallFunc_Conv_IntToFloat_ReturnValue_3, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_6, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_7, int32 CallFunc_GetVisualEffectQuality_ReturnValue, int32 CallFunc_GetPostProcessingQuality_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue_4, float CallFunc_Conv_IntToFloat_ReturnValue_5, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_8, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_9, int32 CallFunc_GetViewDistanceQuality_ReturnValue, int32 CallFunc_GetAntiAliasingQuality_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue_6, float CallFunc_Conv_IntToFloat_ReturnValue_7, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_10, int32 CallFunc_GetTextureQuality_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue_8, double K2Node_FunctionResult_ReturnValue_ImplicitCast, double K2Node_FunctionResult_ReturnValue_ImplicitCast_1, double K2Node_FunctionResult_ReturnValue_ImplicitCast_2, double K2Node_FunctionResult_ReturnValue_ImplicitCast_3, double K2Node_FunctionResult_ReturnValue_ImplicitCast_4, double K2Node_FunctionResult_ReturnValue_ImplicitCast_5, double K2Node_FunctionResult_ReturnValue_ImplicitCast_6, double K2Node_FunctionResult_ReturnValue_ImplicitCast_7, double K2Node_FunctionResult_ReturnValue_ImplicitCast_8, double K2Node_FunctionResult_ReturnValue_ImplicitCast_9, double CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast, double CallFunc_EqualEqual_DoubleDouble_B_ImplicitCast);
	void ResetSelection(const struct FS_Scaler& CallFunc_CurrentSelection_Output, double CallFunc_CurrentSettingValue_ReturnValue, int32 CallFunc_FTrunc_ReturnValue);
	void ChangeSettingValue(int32 Temp_int_Variable, enum class EWindowMode Temp_byte_Variable, enum class EWindowMode Temp_byte_Variable_1, enum class EWindowMode Temp_byte_Variable_2, const struct FS_Scaler& CallFunc_CurrentSelection_Output, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue, int32 CallFunc_FFloor_ReturnValue, const struct FS_Scaler& CallFunc_CurrentSelection_Output_1, const struct FS_Scaler& CallFunc_CurrentSelection_Output_2, int32 CallFunc_FTrunc_ReturnValue, int32 CallFunc_FFloor_ReturnValue_1, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_1, bool CallFunc_Conv_IntToBool_ReturnValue, const struct FS_Scaler& CallFunc_CurrentSelection_Output_3, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_2, int32 CallFunc_FFloor_ReturnValue_2, const struct FS_Scaler& CallFunc_CurrentSelection_Output_4, enum class EWindowMode K2Node_Select_Default, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_3, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_4, const struct FS_Scaler& CallFunc_CurrentSelection_Output_5, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_5, const struct FS_Scaler& CallFunc_CurrentSelection_Output_6, int32 CallFunc_FTrunc_ReturnValue_1, int32 CallFunc_FTrunc_ReturnValue_2, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_6, const struct FS_Scaler& CallFunc_CurrentSelection_Output_7, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_7, int32 CallFunc_FTrunc_ReturnValue_3, const struct FS_Scaler& CallFunc_CurrentSelection_Output_8, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_8, int32 CallFunc_FTrunc_ReturnValue_4, const struct FS_Scaler& CallFunc_CurrentSelection_Output_9, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_9, int32 CallFunc_FTrunc_ReturnValue_5, const struct FS_Scaler& CallFunc_CurrentSelection_Output_10, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_10, int32 CallFunc_FTrunc_ReturnValue_6, const struct FS_Scaler& CallFunc_CurrentSelection_Output_11, class UGameUserSettings* CallFunc_GetGameUserSettings_ReturnValue_11, int32 CallFunc_FTrunc_ReturnValue_7, bool K2Node_SwitchEnum_CmpSuccess, double CallFunc_FFloor_A_ImplicitCast, double CallFunc_FTrunc_A_ImplicitCast, double CallFunc_FFloor_A_ImplicitCast_1, double CallFunc_FFloor_A_ImplicitCast_2, double CallFunc_FTrunc_A_ImplicitCast_1, double CallFunc_FTrunc_A_ImplicitCast_2, double CallFunc_FTrunc_A_ImplicitCast_3, double CallFunc_FTrunc_A_ImplicitCast_4, double CallFunc_FTrunc_A_ImplicitCast_5, double CallFunc_FTrunc_A_ImplicitCast_6, double CallFunc_FTrunc_A_ImplicitCast_7);
	void CurrentSelection(struct FS_Scaler* Output, bool CallFunc_Array_IsValidIndex_ReturnValue, const struct FS_Scaler& CallFunc_Array_Get_Item);
	void PreviousOption(const struct FS_Scaler& CallFunc_CurrentSelection_Output, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue_2, bool CallFunc_Array_IsValidIndex_ReturnValue);
	void BndEvt__BackButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__NextButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void Construct();
	void ExecuteUbergraph_BP_ScalerSetting(int32 EntryPoint);
	void ValueChanged__DelegateSignature(int32 Value);
};

}


