#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SettingsMenu

#include "Basic.hpp"

#include "BP_SettingsMenu_classes.hpp"
#include "BP_SettingsMenu_parameters.hpp"


namespace SDK
{

// Function BP_SettingsMenu.BP_SettingsMenu_C.BindOnClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// E_WidgetToggleType                      WidgetToggleType                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SettingsMenu_C::BindOnClicked(E_WidgetToggleType WidgetToggleType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SettingsMenu_C", "BindOnClicked");

	Params::BP_SettingsMenu_C_BindOnClicked Parms{};

	Parms.WidgetToggleType = WidgetToggleType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SettingsMenu.BP_SettingsMenu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_SettingsMenu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SettingsMenu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SettingsMenu.BP_SettingsMenu_C.ExecuteUbergraph_BP_SettingsMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SettingsMenu_C::ExecuteUbergraph_BP_SettingsMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SettingsMenu_C", "ExecuteUbergraph_BP_SettingsMenu");

	Params::BP_SettingsMenu_C_ExecuteUbergraph_BP_SettingsMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SettingsMenu.BP_SettingsMenu_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SettingsMenu_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SettingsMenu_C", "PreConstruct");

	Params::BP_SettingsMenu_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

