#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SGKSettingsSaveData

#include "Basic.hpp"

#include "BP_SGKSettingsSaveData_classes.hpp"
#include "BP_SGKSettingsSaveData_parameters.hpp"


namespace SDK
{

// Function BP_SGKSettingsSaveData.BP_SGKSettingsSaveData_C.ExecuteUbergraph_BP_SGKSettingsSaveData
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SGKSettingsSaveData_C::ExecuteUbergraph_BP_SGKSettingsSaveData(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SGKSettingsSaveData_C", "ExecuteUbergraph_BP_SGKSettingsSaveData");

	Params::BP_SGKSettingsSaveData_C_ExecuteUbergraph_BP_SGKSettingsSaveData Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SGKSettingsSaveData.BP_SGKSettingsSaveData_C.SaveSettings
// (BlueprintCallable, BlueprintEvent)

void UBP_SGKSettingsSaveData_C::SaveSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SGKSettingsSaveData_C", "SaveSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SGKSettingsSaveData.BP_SGKSettingsSaveData_C.SettingsChanged__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBP_SGKSettingsSaveData_C*        SGKSettings                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_SGKSettingsSaveData_C::SettingsChanged__DelegateSignature(class UBP_SGKSettingsSaveData_C* SGKSettings)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SGKSettingsSaveData_C", "SettingsChanged__DelegateSignature");

	Params::BP_SGKSettingsSaveData_C_SettingsChanged__DelegateSignature Parms{};

	Parms.SGKSettings = SGKSettings;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SGKSettingsSaveData.BP_SGKSettingsSaveData_C.UpdateAudioSettings
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FS_AudioSave                     Audio                                                  (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SGKSettingsSaveData_C::UpdateAudioSettings(const struct FS_AudioSave& Audio)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SGKSettingsSaveData_C", "UpdateAudioSettings");

	Params::BP_SGKSettingsSaveData_C_UpdateAudioSettings Parms{};

	Parms.Audio = std::move(Audio);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SGKSettingsSaveData.BP_SGKSettingsSaveData_C.UpdateGameSettings
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FS_GameSettings                  Game                                                   (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SGKSettingsSaveData_C::UpdateGameSettings(const struct FS_GameSettings& Game)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SGKSettingsSaveData_C", "UpdateGameSettings");

	Params::BP_SGKSettingsSaveData_C_UpdateGameSettings Parms{};

	Parms.Game = std::move(Game);

	UObject::ProcessEvent(Func, &Parms);
}

}

