#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x70 (0x350 - 0x2E0)
// BlueprintGeneratedClass BP_SGKMenuGameState.BP_SGKMenuGameState_C
class ABP_SGKMenuGameState_C : public AGameStateBase
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x2E0(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                       DefaultSceneRoot;                                  // 0x2E8(0x8)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class FString                                MapName;                                           // 0x2F0(0x10)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                ServerName;                                        // 0x300(0x10)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	TArray<class ABP_SGKMenuController_C*>       Seals;                                             // 0x310(0x10)(Edit, BlueprintVisible, Net, DisableEditOnTemplate, DisableEditOnInstance)
	TArray<class ABP_SGKMenuController_C*>       Insurgents;                                        // 0x320(0x10)(Edit, BlueprintVisible, Net, DisableEditOnTemplate, DisableEditOnInstance)
	TArray<class ABP_SGKMenuController_C*>       ReadyList;                                         // 0x330(0x10)(Edit, BlueprintVisible, Net, DisableEditOnTemplate, DisableEditOnInstance)
	bool                                         IsStartingMatch;                                   // 0x340(0x1)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_522B[0x3];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	int32                                        Countdown;                                         // 0x344(0x4)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                          StartTimer;                                        // 0x348(0x8)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class ABP_SGKMenuGameState_C* GetDefaultObj();

	void ForcePlayerReady(class ABP_SGKMenuController_C* Object, int32 CallFunc_Array_Add_ReturnValue, bool CallFunc_Array_Contains_ReturnValue);
	void ForcePlayerReadyState(int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class APlayerState* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class ABP_SGKMenuController_C* K2Node_DynamicCast_AsBP_SGKMenu_Controller, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_Array_Add_ReturnValue);
	void RemovePlayer(class ABP_SGKMenuController_C* Controller, int32 CallFunc_FindPlayerIndex_index, bool CallFunc_FindPlayerIndex_sucess, int32 CallFunc_FindPlayerIndex_index_1, bool CallFunc_FindPlayerIndex_sucess_1, int32 CallFunc_FindPlayerIndex_index_2, bool CallFunc_FindPlayerIndex_sucess_2);
	void FindPlayerIndex(TArray<class ABP_SGKMenuController_C*>& Array, class ABP_SGKMenuController_C* Controller, int32* Index, bool* Sucess, int32 Result, int32 CallFunc_Array_Length_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable, class ABP_SGKMenuController_C* CallFunc_Array_Get_Item, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue);
	void F_Set_Player_Lodout(int32 Lodout, class APlayerController* Controller, class UClass* Result, class ABP_SGKMenuController_C* K2Node_DynamicCast_AsBP_SGKMenu_Controller, bool K2Node_DynamicCast_bSuccess, bool K2Node_SwitchInteger_CmpSuccess, bool K2Node_SwitchInteger_CmpSuccess_1, bool K2Node_SwitchInteger_CmpSuccess_2, bool K2Node_SwitchInteger_CmpSuccess_3, bool K2Node_SwitchInteger_CmpSuccess_4, bool K2Node_SwitchInteger_CmpSuccess_5, bool K2Node_SwitchInteger_CmpSuccess_6, bool K2Node_SwitchInteger_CmpSuccess_7, bool K2Node_SwitchInteger_CmpSuccess_8, bool K2Node_SwitchInteger_CmpSuccess_9, bool K2Node_SwitchInteger_CmpSuccess_10, bool K2Node_SwitchInteger_CmpSuccess_11, bool K2Node_SwitchInteger_CmpSuccess_12, bool K2Node_SwitchInteger_CmpSuccess_13, bool K2Node_SwitchInteger_CmpSuccess_14, bool K2Node_SwitchInteger_CmpSuccess_15, bool K2Node_SwitchInteger_CmpSuccess_16, bool K2Node_SwitchInteger_CmpSuccess_17, bool K2Node_SwitchInteger_CmpSuccess_18, bool K2Node_SwitchInteger_CmpSuccess_19, bool K2Node_SwitchInteger_CmpSuccess_20, bool K2Node_SwitchInteger_CmpSuccess_21, bool K2Node_SwitchInteger_CmpSuccess_22, bool K2Node_SwitchInteger_CmpSuccess_23, bool K2Node_SwitchInteger_CmpSuccess_24, bool K2Node_SwitchInteger_CmpSuccess_25, bool K2Node_SwitchInteger_CmpSuccess_26, bool K2Node_SwitchInteger_CmpSuccess_27, bool K2Node_SwitchInteger_CmpSuccess_28, bool K2Node_SwitchInteger_CmpSuccess_29, bool K2Node_SwitchInteger_CmpSuccess_30, bool K2Node_SwitchInteger_CmpSuccess_31, bool K2Node_SwitchInteger_CmpSuccess_32, bool K2Node_SwitchInteger_CmpSuccess_33, bool K2Node_SwitchInteger_CmpSuccess_34, bool K2Node_SwitchInteger_CmpSuccess_35, bool K2Node_SwitchInteger_CmpSuccess_36, bool K2Node_SwitchInteger_CmpSuccess_37, bool K2Node_SwitchString_CmpSuccess, int32 CallFunc_FindPlayerIndex_index, bool CallFunc_FindPlayerIndex_sucess, bool K2Node_SwitchString_CmpSuccess_1);
	void Remove_Lobby_Screen_for_All_Players(int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class APlayerState* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue, class ABP_SGKMenuController_C* K2Node_DynamicCast_AsBP_SGKMenu_Controller, bool K2Node_DynamicCast_bSuccess);
	void CheckIfAllPlayersAreReady(int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue, bool CallFunc_NotEqual_IntInt_ReturnValue);
	void SwitchTeams(class ABP_SGKMenuController_C*& ItemToFind, int32 CallFunc_FindPlayerIndex_index, bool CallFunc_FindPlayerIndex_sucess);
	void TogglePlayerReady(class ABP_SGKMenuController_C*& ItemToFind, int32 CallFunc_FindPlayerIndex_index, bool CallFunc_FindPlayerIndex_sucess);
	void RemovePlayerFromReadyList(class ABP_SGKMenuController_C*& NewItem, int32 CallFunc_FindPlayerIndex_index, bool CallFunc_FindPlayerIndex_sucess);
	void AddPlayerToReadyList(class ABP_SGKMenuController_C*& NewItem, int32 CallFunc_Array_Add_ReturnValue);
	void Update_Lobby_for_All_Clients(const TArray<int32>& Ranks, const TArray<bool>& Ready, const TArray<enum class EPeak53Teams>& Team, const TArray<class FName>& Names, bool Temp_bool_Variable, bool Temp_bool_Variable_1, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable_2, enum class EPeak53Teams Temp_byte_Variable, enum class EPeak53Teams Temp_byte_Variable_1, enum class EPeak53Teams CallFunc_Array_Get_Item, const class FString& CallFunc_Conv_BoolToString_ReturnValue, const class FString& CallFunc_GetEnumeratorUserFriendlyName_ReturnValue, class FName CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Add_ReturnValue, const class FString& CallFunc_Conv_NameToString_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, int32 CallFunc_Array_Add_ReturnValue_1, const class FString& CallFunc_Concat_StrStr_ReturnValue_2, const class FString& CallFunc_Concat_StrStr_ReturnValue_3, const class FString& CallFunc_Concat_StrStr_ReturnValue_4, int32 CallFunc_Array_Add_ReturnValue_2, int32 CallFunc_Array_Add_ReturnValue_3, int32 Temp_int_Loop_Counter_Variable_2, class APlayerState* CallFunc_Array_Get_Item_2, int32 CallFunc_Array_Length_ReturnValue_1, class APeak53PlayerState_C* K2Node_DynamicCast_AsPeak_53Player_State, bool K2Node_DynamicCast_bSuccess, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue_4, class APlayerController* CallFunc_GetPlayerController_ReturnValue, const class FString& CallFunc_GetPlayerName_ReturnValue, class ABP_SGKMenuController_C* K2Node_DynamicCast_AsBP_SGKMenu_Controller, bool K2Node_DynamicCast_bSuccess_1, class FName CallFunc_Conv_StringToName_ReturnValue, int32 CallFunc_FindPlayerIndex_index, bool CallFunc_FindPlayerIndex_sucess, int32 CallFunc_Array_AddUnique_ReturnValue, int32 CallFunc_FindPlayerIndex_index_1, bool CallFunc_FindPlayerIndex_sucess_1, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_2, class APlayerState* CallFunc_Array_Get_Item_3, bool CallFunc_Less_IntInt_ReturnValue_2, class APlayerController* CallFunc_GetPlayerController_ReturnValue_1, class ABP_SGKMenuController_C* K2Node_DynamicCast_AsBP_SGKMenu_Controller_1, bool K2Node_DynamicCast_bSuccess_2);
	void AddToInsurgents(class ABP_SGKMenuController_C*& NewItem, int32 CallFunc_FindPlayerIndex_index, bool CallFunc_FindPlayerIndex_sucess, int32 CallFunc_Array_AddUnique_ReturnValue);
	void AddToSeals(class ABP_SGKMenuController_C*& Player, int32 CallFunc_FindPlayerIndex_index, bool CallFunc_FindPlayerIndex_sucess, int32 CallFunc_Array_AddUnique_ReturnValue);
	void AutoTeam(class ABP_SGKMenuController_C*& Player, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_GreaterEqual_IntInt_ReturnValue);
	void SetServerMapName(const class FString& MapName);
	void SetServerName(const class FString& ServerName);
	void AllPlayersReady();
	void CustomEvent();
	void ExecuteUbergraph_BP_SGKMenuGameState(int32 EntryPoint, class UGameInstance* CallFunc_GetGameInstance_ReturnValue, class UBP_SGKGameInstance_C* K2Node_DynamicCast_AsBP_SGKGame_Instance, bool K2Node_DynamicCast_bSuccess, bool Temp_bool_Has_Been_Initd_Variable, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, const struct FTimerHandle& CallFunc_K2_SetTimerDelegate_ReturnValue, bool Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, const class FString& K2Node_CustomEvent_MapName, const class FString& K2Node_CustomEvent_ServerName, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, const class FString& CallFunc_Concat_StrStr_ReturnValue_2, class APlayerController* CallFunc_GetPlayerController_ReturnValue, bool Temp_bool_IsClosed_Variable, class APlayerState* CallFunc_Array_Get_Item, class APlayerController* CallFunc_GetPlayerController_ReturnValue_1, class ABP_SGKMenuController_C* K2Node_DynamicCast_AsBP_SGKMenu_Controller, bool K2Node_DynamicCast_bSuccess_1, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
};

}


