#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0xA8 (0x338 - 0x290)
// BlueprintGeneratedClass BP_StaticMasterItem.BP_StaticMasterItem_C
class ABP_StaticMasterItem_C : public AActor
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x290(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                  StaticMesh;                                        // 0x298(0x8)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FDataTableRowHandle                   Item;                                              // 0x2A0(0x10)(Edit, BlueprintVisible, NoDestructor)
	int32                                        ItemAmount;                                        // 0x2B0(0x4)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         RefreshItem;                                       // 0x2B4(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         AddStartingItems;                                  // 0x2B5(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         UseDroppedItemDestroyTimer;                        // 0x2B6(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_453E[0x1];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	double                                       DropDestroyTime;                                   // 0x2B8(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FS_InvItem                            InvItem;                                           // 0x2C0(0x30)(Edit, BlueprintVisible, Net, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	bool                                         Spawned;                                           // 0x2F0(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                         Dropped;                                           // 0x2F1(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                         SaveGameLoaded;                                    // 0x2F2(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_453F[0x5];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	struct FS_InvItem                            TempItem;                                          // 0x2F8(0x30)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	class ABP_SaveSystem_C*                      SaveGame;                                          // 0x328(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UStaticMesh*                           Mesh;                                              // 0x330(0x8)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, RepNotify, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class ABP_StaticMasterItem_C* GetDefaultObj();

	void SGK_GetVerifiedPlayers(TArray<class FText>* VerifiedPlayers);
	bool SGK_UpdateCode(class FText Code);
	bool SGK_VerifyPlayer(class FText Text);
	void SGK_CodeCheck(class FText Code, bool* CodeAccepted);
	void SGK_Mesh(class UPrimitiveComponent** Mesh);
	void SGK_ItemAmount(int32* Amount);
	bool SGK_EndInteraction(class UBP_PlayerInventory_C* PlayerInventory);
	void SGK_InvItem(bool* IsItem, struct FS_InvItem* InvItem, const struct FS_InvItem& CombineItemsL);
	bool SGK_DropItem(const struct FS_InvItem& InvItem, bool Dropped, bool Spawned, bool SaveLoaded, const struct FS_InvItem& ItemL, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, const struct FTimerHandle& CallFunc_K2_SetTimerDelegate_ReturnValue, bool CallFunc_IsStandalone_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsStandalone_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, bool CallFunc_BooleanOR_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue_2, float CallFunc_K2_SetTimerDelegate_Time_ImplicitCast);
	void SGK_InteractName(class FText* InteractName, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails);
	void SGK_PossibleActions(class UBP_PlayerInventory_C* PlayerInventory, bool* ActionsFound, TArray<struct FS_WorldAction>* PossibleActions, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue);
	void SGK_AllowInteraction(bool* AllowInteraction);
	bool SGK_Interact(class UBP_PlayerInventory_C* PlayerInventory, enum class E_WorldActions Action);
	void OnRep_Mesh(bool CallFunc_SetStaticMesh_ReturnValue);
	void ItemDecay(const struct FS_DecayDetails& DecayDetailsL, class AGameModeBase* CallFunc_GetGameMode_ReturnValue, TScriptInterface<class IBP_SGKGameModeInterface_C> K2Node_DynamicCast_AsBP_SGKGame_Mode_Interface, bool K2Node_DynamicCast_bSuccess, class ABP_GlobalInventoryManager_C* CallFunc_SGK_GetGlobalInventory_GlobalInventory, bool CallFunc_IsValid_ReturnValue, class AGameModeBase* CallFunc_GetGameMode_ReturnValue_1, class APawn* CallFunc_GetInstigator_ReturnValue, TScriptInterface<class IBP_SGKGameModeInterface_C> K2Node_DynamicCast_AsBP_SGKGame_Mode_Interface_1, bool K2Node_DynamicCast_bSuccess_1, class AActor* CallFunc_GetOwner_ReturnValue, class ABP_GlobalInventoryManager_C* CallFunc_SGK_GetGlobalInventory_GlobalInventory_1, const struct FTransform& CallFunc_GetTransform_ReturnValue, class AGameModeBase* CallFunc_GetGameMode_ReturnValue_2, TScriptInterface<class IBP_SGKGameModeInterface_C> K2Node_DynamicCast_AsBP_SGKGame_Mode_Interface_2, bool K2Node_DynamicCast_bSuccess_2, class ABP_GlobalInventoryManager_C* CallFunc_SGK_GetGlobalInventory_GlobalInventory_2, const struct FS_InvItem& CallFunc_CreateNewItem_NewItem, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, bool CallFunc_SGK_ItemDetails_ItemFound_1, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails_1, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, class AActor* CallFunc_FinishSpawningActor_ReturnValue, TScriptInterface<class IBP_SGKInteractionInterface_C> K2Node_DynamicCast_AsBP_SGKInteraction_Interface, bool K2Node_DynamicCast_bSuccess_3, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_SGK_DropItem_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_SGK_ItemDetails_ItemFound_2, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails_2, bool CallFunc_SGK_DurabilityDetails_ItemFound, const struct FS_DurabilityDetails& CallFunc_SGK_DurabilityDetails_DurabilityDetails, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Format_ReturnValue, const class FString& CallFunc_Conv_TextToString_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
	bool ActionCheck(TArray<struct FS_WorldAction>& ItemActons, enum class E_WorldActions ActionType, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, const struct FS_WorldAction& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue);
	void ItemOffsets(const struct FS_ItemDetails& ItemDetailsL, const struct FTransform& CallFunc_MakeTransform_ReturnValue, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, bool CallFunc_EqualEqual_TransformTransform_ReturnValue, const struct FVector& CallFunc_BreakTransform_Location, const struct FRotator& CallFunc_BreakTransform_Rotation, const struct FVector& CallFunc_BreakTransform_Scale, bool CallFunc_K2_SetActorRotation_ReturnValue, bool CallFunc_SGK_ItemDetails_ItemFound_1, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails_1, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue, const struct FHitResult& CallFunc_K2_SetActorLocation_SweepHitResult, bool CallFunc_K2_SetActorLocation_ReturnValue);
	void InteractActions(class UBP_PlayerInventory_C* PlayerInventory, enum class E_WorldActions Action, int32 StartAmountL, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, bool CallFunc_SGK_ItemDetails_ItemFound_1, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails_1, bool CallFunc_ActionCheck_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_SGK_ItemDetails_ItemFound_2, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails_2, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_2, bool CallFunc_InAction_InAction, bool CallFunc_IsStandalone_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess);
	void Hold(class UBP_PlayerInventory_C* PlayerInventory, bool CallFunc_AttemptToPickupHold_ItemHeld, bool CallFunc_AttemptToPickupHold_ItemAdded);
	void Learn(class UBP_PlayerInventory_C* PlayerInventory, bool CallFunc_SGK_ItemRecipeDetails_ItemFound, const struct FS_RecipeDetails& CallFunc_SGK_ItemRecipeDetails_ItemRecipeDetails, bool CallFunc_LearnAllItemRecipes_RecipeLearnt);
	void Consume(class UBP_PlayerInventory_C* PlayerInventory, const struct FS_InvItem& ConsumedItemL, class AGameModeBase* CallFunc_GetGameMode_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, TScriptInterface<class IBP_SGKGameModeInterface_C> K2Node_DynamicCast_AsBP_SGKGame_Mode_Interface, bool K2Node_DynamicCast_bSuccess, const struct FTransform& CallFunc_MakeTransform_ReturnValue, class ABP_GlobalInventoryManager_C* CallFunc_SGK_GetGlobalInventory_GlobalInventory, bool CallFunc_SGK_ItemConsumableDetails_ItemFound, const struct FS_ConsumableDetails& CallFunc_SGK_ItemConsumableDetails_ItemDetails, const struct FS_InvItem& CallFunc_CreateNewItem_NewItem, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, class AActor* CallFunc_FinishSpawningActor_ReturnValue, TScriptInterface<class IBP_SGKInteractionInterface_C> K2Node_DynamicCast_AsBP_SGKInteraction_Interface, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_SGK_DropItem_ReturnValue, bool CallFunc_SGK_ItemConsumableDetails_ItemFound_1, const struct FS_ConsumableDetails& CallFunc_SGK_ItemConsumableDetails_ItemDetails_1, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue_1, bool CallFunc_ConsumeItem_Consumed, bool CallFunc_Greater_IntInt_ReturnValue_2, bool CallFunc_UpdateItemUseAmount_ItemEmpty, const struct FS_InvItem& CallFunc_UpdateItemUseAmount_ItemOut);
	void Open(class UBP_PlayerInventory_C* PlayerInventory, bool CallFunc_IsValid_ReturnValue);
	void EquipWeapon(class UBP_PlayerInventory_C* PlayerInventory, bool CallFunc_IsValid_ReturnValue, bool CallFunc_AttemptToEquipWeapon_WeaponEquipped, enum class E_WeaponSlots CallFunc_AttemptToEquipWeapon_ItemWeaponSlot);
	void EquipClothing(class UBP_PlayerInventory_C* PlayerInventory, bool CallFunc_IsValid_ReturnValue, bool CallFunc_AttemptToEquipItem_ItemEquipped);
	void Pickup(class UBP_PlayerInventory_C* PlayerInventory, int32 StartAmountL, bool CallFunc_IsValid_ReturnValue, TScriptInterface<class IBP_SGKInventoryInterface_C> CallFunc_SGK_ItemSound_self_CastInput, TScriptInterface<class IBP_SGKInventoryInterface_C> CallFunc_SGK_ItemSound_self_CastInput_1, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_AttemptToAddItem_RemainingItem, const struct FS_InvItem& CallFunc_AttemptToAddItem_RemainingInvItem, const struct FS_InvSlotID& CallFunc_AttemptToAddItem_NewItemSlot);
	void Interact(class UBP_PlayerInventory_C* PlayerInventory);
	void UserConstructionScript(bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, bool CallFunc_SGK_ItemDetails_ItemFound_1, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails_1, bool CallFunc_SetStaticMesh_ReturnValue, bool CallFunc_SetStaticMesh_ReturnValue_1, bool CallFunc_NotEqual_NameName_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_BooleanOR_ReturnValue_1);
	void SGK_SetVerifiedPlayers(TArray<class FText>& VerifiedPlayers);
	void SGK_TurnedOnEffect(bool TurnedOn);
	void Reset();
	void SGK_PlayerOutProximity();
	void SGK_PlayerInProximity();
	void CreateItem(class ABP_GlobalInventoryManager_C* InventoryManager);
	void SaveNotValid();
	void LoadItem(class UBP_SGKSaveGame_C* SaveGame);
	void ReceiveBeginPlay();
	void DropDestroyTimer();
	void SGKSave(class UBP_SGKSaveGame_C* Save);
	void ExecuteUbergraph_BP_StaticMasterItem(int32 EntryPoint, TArray<class AActor*>& Temp_object_Variable, bool K2Node_Event_TurnedOn, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, TArray<enum class EObjectTypeQuery>& K2Node_MakeArray_Array, TArray<class AActor*>& CallFunc_SphereOverlapActors_OutActors, bool CallFunc_SphereOverlapActors_ReturnValue, bool CallFunc_IsValid_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, bool Temp_bool_Has_Been_Initd_Variable, class ABP_GlobalInventoryManager_C* K2Node_CustomEvent_InventoryManager, bool CallFunc_IsValid_ReturnValue_1, double CallFunc_RandomFloatInRange_ReturnValue, bool CallFunc_SGK_DurabilityDetails_ItemFound, const struct FS_DurabilityDetails& CallFunc_SGK_DurabilityDetails_DurabilityDetails, const struct FTimerHandle& CallFunc_K2_SetTimer_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, TArray<class FText>& K2Node_Event_VerifiedPlayers, bool CallFunc_IsStandalone_ReturnValue, bool CallFunc_IsStandalone_ReturnValue_1, class AActor* CallFunc_GetOwner_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_3, const struct FS_InvItem& CallFunc_CreateNewItem_NewItem, bool Temp_bool_IsClosed_Variable, int32 CallFunc_Array_AddUnique_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, class UBP_SGKSaveGame_C* K2Node_CustomEvent_SaveGame, class AGameModeBase* CallFunc_GetGameMode_ReturnValue, TScriptInterface<class IBP_SGKGameModeInterface_C> K2Node_DynamicCast_AsBP_SGKGame_Mode_Interface, bool K2Node_DynamicCast_bSuccess, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, class ABP_SaveSystem_C* CallFunc_SGK_GetSaveGame_SaveGame, class AGameModeBase* CallFunc_GetGameMode_ReturnValue_1, TScriptInterface<class IBP_SGKGameModeInterface_C> K2Node_DynamicCast_AsBP_SGKGame_Mode_Interface_1, bool K2Node_DynamicCast_bSuccess_1, TScriptInterface<class IBP_SGKGameModeInterface_C> K2Node_DynamicCast_AsBP_SGKGame_Mode_Interface_2, bool K2Node_DynamicCast_bSuccess_2, class UBP_GameModeInitComponent_C* CallFunc_SGK_GetInitComponent_InitComponent, class ABP_GlobalInventoryManager_C* CallFunc_SGK_GetGlobalInventory_GlobalInventory, bool CallFunc_IsValid_ReturnValue_4, bool CallFunc_IsValid_ReturnValue_5, class UBP_SGKSaveGame_C* K2Node_Event_Save, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, const class FString& CallFunc_GetCurrentLevelName_ReturnValue, const struct FTransform& CallFunc_GetTransform_ReturnValue, bool CallFunc_IsValid_ReturnValue_6, float CallFunc_Delay_Duration_ImplicitCast);
};

}


