#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ScalerSetting

#include "Basic.hpp"

#include "BP_ScalerSetting_classes.hpp"
#include "BP_ScalerSetting_parameters.hpp"


namespace SDK
{

// Function BP_ScalerSetting.BP_ScalerSetting_C.BndEvt__BackButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_ScalerSetting_C::BndEvt__BackButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScalerSetting_C", "BndEvt__BackButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ScalerSetting.BP_ScalerSetting_C.BndEvt__NextButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_ScalerSetting_C::BndEvt__NextButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScalerSetting_C", "BndEvt__NextButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ScalerSetting.BP_ScalerSetting_C.ChangeSettingValue
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_ScalerSetting_C::ChangeSettingValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScalerSetting_C", "ChangeSettingValue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ScalerSetting.BP_ScalerSetting_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_ScalerSetting_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScalerSetting_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ScalerSetting.BP_ScalerSetting_C.CurrentSelection
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FS_Scaler                        Output                                                 (Parm, OutParm, HasGetValueTypeHash)

void UBP_ScalerSetting_C::CurrentSelection(struct FS_Scaler* Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScalerSetting_C", "CurrentSelection");

	Params::BP_ScalerSetting_C_CurrentSelection Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = std::move(Parms.Output);
}


// Function BP_ScalerSetting.BP_ScalerSetting_C.CurrentSettingValue
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

double UBP_ScalerSetting_C::CurrentSettingValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScalerSetting_C", "CurrentSettingValue");

	Params::BP_ScalerSetting_C_CurrentSettingValue Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_ScalerSetting.BP_ScalerSetting_C.ExecuteUbergraph_BP_ScalerSetting
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ScalerSetting_C::ExecuteUbergraph_BP_ScalerSetting(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScalerSetting_C", "ExecuteUbergraph_BP_ScalerSetting");

	Params::BP_ScalerSetting_C_ExecuteUbergraph_BP_ScalerSetting Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ScalerSetting.BP_ScalerSetting_C.NextOption
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_ScalerSetting_C::NextOption()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScalerSetting_C", "NextOption");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ScalerSetting.BP_ScalerSetting_C.PreviousOption
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_ScalerSetting_C::PreviousOption()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScalerSetting_C", "PreviousOption");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ScalerSetting.BP_ScalerSetting_C.ResetSelection
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_ScalerSetting_C::ResetSelection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScalerSetting_C", "ResetSelection");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ScalerSetting.BP_ScalerSetting_C.ValueChanged__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ScalerSetting_C::ValueChanged__DelegateSignature(int32 Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScalerSetting_C", "ValueChanged__DelegateSignature");

	Params::BP_ScalerSetting_C_ValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}

}

