#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StoneTriangleFoundation

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_StoneTriangleFoundation.BP_StoneTriangleFoundation_C.ExecuteUbergraph_BP_StoneTriangleFoundation
// 0x0004 (0x0004 - 0x0000)
struct BP_StoneTriangleFoundation_C_ExecuteUbergraph_BP_StoneTriangleFoundation final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_StoneTriangleFoundation_C_ExecuteUbergraph_BP_StoneTriangleFoundation) == 0x000004, "Wrong alignment on BP_StoneTriangleFoundation_C_ExecuteUbergraph_BP_StoneTriangleFoundation");
static_assert(sizeof(BP_StoneTriangleFoundation_C_ExecuteUbergraph_BP_StoneTriangleFoundation) == 0x000004, "Wrong size on BP_StoneTriangleFoundation_C_ExecuteUbergraph_BP_StoneTriangleFoundation");
static_assert(offsetof(BP_StoneTriangleFoundation_C_ExecuteUbergraph_BP_StoneTriangleFoundation, EntryPoint) == 0x000000, "Member 'BP_StoneTriangleFoundation_C_ExecuteUbergraph_BP_StoneTriangleFoundation::EntryPoint' has a wrong offset!");

}

