#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x25F (0x500 - 0x2A1)
// BlueprintGeneratedClass BP_WeaponInventory.BP_WeaponInventory_C
class UBP_WeaponInventory_C : public UBP_MasterItemInventory_C
{
public:
	uint8                                        Pad_386D[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x2A8(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	struct FS_AttachmentSlot                     MagazineItem;                                      // 0x2B0(0x48)(Edit, BlueprintVisible, Net, DisableEditOnInstance, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FS_AttachmentSlot                     SightItem;                                         // 0x2F8(0x48)(Edit, BlueprintVisible, Net, DisableEditOnInstance, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FS_AttachmentSlot                     UnderbarrelItem;                                   // 0x340(0x48)(Edit, BlueprintVisible, Net, DisableEditOnInstance, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FS_AttachmentSlot                     StockItem;                                         // 0x388(0x48)(Edit, BlueprintVisible, Net, DisableEditOnInstance, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FS_AttachmentSlot                     MuzzleItem;                                        // 0x3D0(0x48)(Edit, BlueprintVisible, Net, DisableEditOnInstance, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FS_AttachmentSlot                     HandguardItem;                                     // 0x418(0x48)(Edit, BlueprintVisible, Net, DisableEditOnInstance, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FS_AttachmentSlot                     TriggerItem;                                       // 0x460(0x48)(Edit, BlueprintVisible, Net, DisableEditOnInstance, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FS_AttachmentSlot                     FrontGripItem;                                     // 0x4A8(0x48)(Edit, BlueprintVisible, Net, DisableEditOnInstance, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	enum class E_FireModes                       WeaponFireMode;                                    // 0x4F0(0x1)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_386F[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class ABP_MasterWeapon_C*                    Weapon;                                            // 0x4F8(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class UBP_WeaponInventory_C* GetDefaultObj();

	void AddAttachmentUsingPlayers(class UBP_MasterInventory_C* ContainerL, int32 Temp_int_Variable, bool CallFunc_IsValid_ReturnValue, uint8 CallFunc_Conv_IntToByte_ReturnValue, uint8 CallFunc_GetValidValue_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_SelectAttachmentItem_IsValid, const struct FS_AttachmentSlot& CallFunc_SelectAttachmentItem_ReturnValue, class UBP_PlayerInventory_C* K2Node_DynamicCast_AsBP_Player_Inventory, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_MakeLiteralInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue, class UBP_PlayerInventory_C* K2Node_DynamicCast_AsBP_Player_Inventory_1, bool K2Node_DynamicCast_bSuccess_1, int32 CallFunc_Array_AddUnique_ReturnValue, int32 CallFunc_Array_AddUnique_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_2);
	void ReplicateContainingInventories(bool Replicate, int32 Temp_int_Variable, uint8 CallFunc_Conv_IntToByte_ReturnValue, uint8 CallFunc_GetValidValue_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_SelectAttachmentItem_IsValid, const struct FS_AttachmentSlot& CallFunc_SelectAttachmentItem_ReturnValue, int32 CallFunc_MakeLiteralInt_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue);
	bool AmmoTypeCheck(const struct FS_InvItem& Item, TArray<struct FDataTableRowHandle>& Temp_struct_Variable, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, const struct FS_InvItem& CallFunc_SGK_SelfItem_SelfItem, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, class UClass* K2Node_ClassDynamicCast_AsBP_Master_Range_Weapon, bool K2Node_ClassDynamicCast_bSuccess, int32 CallFunc_Array_Length_ReturnValue, const struct FDataTableRowHandle& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_NameName_ReturnValue);
	void ChamberRoundFromMag(class UBP_MasterInventory_C* MagInvL, const struct FS_InvSlot& AmmoItemL, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue, const struct FS_InvItem& CallFunc_SGK_SelfItem_SelfItem, bool CallFunc_SGK_ItemHoldableDetails_ItemFound, const struct FS_HoldableDetails& CallFunc_SGK_ItemHoldableDetails_ItemHoldableDetails, class UClass* K2Node_ClassDynamicCast_AsBP_Master_Range_Weapon, bool K2Node_ClassDynamicCast_bSuccess, bool CallFunc_IsValidClass_ReturnValue, bool CallFunc_AddItem_RemainingItem, const struct FS_InvItem& CallFunc_AddItem_RemainingInvItem, const struct FS_InvSlotID& CallFunc_AddItem_NewItemSlot, bool CallFunc_RemoveItemAmount_ItemRemoved, bool CallFunc_SelectAttachmentItem_IsValid, const struct FS_AttachmentSlot& CallFunc_SelectAttachmentItem_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue, const struct FS_InvSlot& CallFunc_Array_Get_Item, const struct FS_InvItem& CallFunc_SGK_InvSlotItem_InvItem, bool CallFunc_SGK_IsRootSlot_IsRootSlot, int32 CallFunc_SGK_IsRootSlot_RootIndex, bool CallFunc_AmmoTypeCheck_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, int32 CallFunc_Max_ReturnValue);
	int32 TotalAmmo(bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
	void TotalMaxAmmo(int32* MaxAmmo, int32 MaxAmmoL, class UClass* RangeWeaponL, const struct FS_InvItem& CallFunc_SGK_SelfItem_SelfItem, bool CallFunc_SGK_GetItemRangeClass_ReturnValue, class UClass* CallFunc_SGK_GetItemRangeClass_RangeWeapon, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
	bool NextRound(struct FS_InvSlot* Item, const struct FS_InvSlot& AmmoItemL, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool CallFunc_GreaterEqual_IntInt_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue_1, const struct FS_InvItem& CallFunc_SGK_InvSlotItem_InvItem, bool CallFunc_AmmoTypeCheck_ReturnValue, bool CallFunc_IsValid_ReturnValue, const struct FS_InvSlot& CallFunc_Array_Get_Item, bool CallFunc_Greater_IntInt_ReturnValue_2, bool CallFunc_SGK_IsRootSlot_IsRootSlot, int32 CallFunc_SGK_IsRootSlot_RootIndex, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_2, int32 CallFunc_Max_ReturnValue, const struct FS_InvItem& CallFunc_SGK_InvSlotItem_InvItem_1, bool CallFunc_Greater_IntInt_ReturnValue_3, bool CallFunc_AmmoTypeCheck_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_1, const struct FS_InvSlot& CallFunc_Array_Get_Item_1, int32 CallFunc_Subtract_IntInt_ReturnValue_3, int32 CallFunc_Max_ReturnValue_1, bool CallFunc_SGK_IsRootSlot_IsRootSlot_1, int32 CallFunc_SGK_IsRootSlot_RootIndex_1);
	struct FS_AttachmentSlot SelectAttachmentItem(enum class E_AttachmentType Attachment, bool* IsValid, enum class E_AttachmentType Temp_byte_Variable, const struct FS_AttachmentSlot& Temp_struct_Variable, const struct FS_AttachmentSlot& K2Node_Select_Default, bool CallFunc_Greater_IntInt_ReturnValue);
	void UpdateAllAttachments(TArray<struct FS_AttachmentSlot>& Attachments, const struct FS_AttachmentSlot& NewAttachmentL, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, const struct FS_AttachmentSlot& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess, int32 CallFunc_Add_IntInt_ReturnValue);
	void AddWeaponAttachment(const struct FS_InvItem& InvItem, bool PlayAnim, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, bool CallFunc_IsValid_ReturnValue, bool CallFunc_SGK_ItemDetails_ItemFound_1, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails_1, class ABP_MasterAttachment_C* CallFunc_AddNewAttachment_NewAttachment, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_SGK_ItemDetails_ItemFound_2, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails_2);
	void UpdateAllClientAttachments(const TArray<struct FS_AttachmentSlot>& AttachmentsL, int32 Temp_int_Array_Index_Variable, int32 CallFunc_MakeLiteralInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 Temp_int_Variable, uint8 CallFunc_Conv_IntToByte_ReturnValue, uint8 CallFunc_GetValidValue_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_SelectAttachmentItem_IsValid, const struct FS_AttachmentSlot& CallFunc_SelectAttachmentItem_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, int32 Temp_int_Loop_Counter_Variable, class UBP_PlayerInventory_C* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1);
	void RemoveAttachment(enum class E_AttachmentType Attachment, class ABP_MasterAttachment_C* AttachmentL, bool CallFunc_SelectAttachmentItem_IsValid, const struct FS_AttachmentSlot& CallFunc_SelectAttachmentItem_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 Temp_int_Array_Index_Variable, bool CallFunc_IsValid_ReturnValue_1, class ABP_MasterRangeWeapon_C* K2Node_DynamicCast_AsBP_Master_Range_Weapon, bool K2Node_DynamicCast_bSuccess, bool CallFunc_EqualEqual_ByteByte_ReturnValue, int32 Temp_int_Loop_Counter_Variable, class UBP_PlayerInventory_C* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
	void LoadSavedAttachments(TArray<struct FS_AttachmentSaveSlot>& Attachments, TArray<struct FS_OtherInvSaves>& OtherInventorys, const struct FS_InvItem& NewItemL, const struct FS_AttachmentSaveSlot& AttachmentSaveSlotL, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, const struct FS_AttachmentSaveSlot& CallFunc_Array_Get_Item, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem, bool CallFunc_Greater_IntInt_ReturnValue, class AGameModeBase* CallFunc_GetGameMode_ReturnValue, TScriptInterface<class IBP_SGKGameModeInterface_C> K2Node_DynamicCast_AsBP_SGKGame_Mode_Interface, bool K2Node_DynamicCast_bSuccess, class ABP_GlobalInventoryManager_C* CallFunc_SGK_GetGlobalInventory_GlobalInventory, const struct FS_OtherInvSaves& CallFunc_Array_Get_Item_1, const struct FS_OtherInvSaves& CallFunc_Array_Get_Item_2, const struct FS_InvItem& CallFunc_CreateNewItem_NewItem, bool CallFunc_IsValid_ReturnValue, double K2Node_VariableSet_CurrentWeight_ImplicitCast);
	void AddDefaultAttachments(const struct FDataTableRowHandle& ArrayElementL, const struct FS_ItemDetails& AttachmentItemDetailsL, class UClass* SelfWeaponClassL, const struct FS_ItemDetails& SelfItemDetailsL, TSet<enum class E_AttachmentType> Temp_byte_Variable, TArray<class UClass*>& Temp_class_Variable, TArray<struct FDataTableRowHandle>& Temp_struct_Variable, bool CallFunc_IsValidClass_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, class UClass* K2Node_ClassDynamicCast_AsBP_Master_Weapon, bool K2Node_ClassDynamicCast_bSuccess, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, const struct FDataTableRowHandle& CallFunc_Array_Get_Item, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, const struct FS_InvItem& CallFunc_SGK_SelfItem_SelfItem, class AGameModeBase* CallFunc_GetGameMode_ReturnValue, bool CallFunc_SGK_ItemDetails_ItemFound_1, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails_1, TScriptInterface<class IBP_SGKGameModeInterface_C> K2Node_DynamicCast_AsBP_SGKGame_Mode_Interface, bool K2Node_DynamicCast_bSuccess, class ABP_GlobalInventoryManager_C* CallFunc_SGK_GetGlobalInventory_GlobalInventory, bool CallFunc_Set_Contains_ReturnValue, const struct FS_InvItem& CallFunc_CreateNewItem_NewItem, bool CallFunc_Array_Contains_ReturnValue);
	void CreateAllAttachments(int32 Temp_int_Variable, uint8 CallFunc_Conv_IntToByte_ReturnValue, uint8 CallFunc_GetValidValue_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_SelectAttachmentItem_IsValid, const struct FS_AttachmentSlot& CallFunc_SelectAttachmentItem_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_SGK_ItemDetails_ItemFound, const struct FS_ItemDetails& CallFunc_SGK_ItemDetails_ItemDetails, int32 CallFunc_MakeLiteralInt_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, class ABP_MasterAttachment_C* CallFunc_AddNewAttachment_NewAttachment);
	void UpdateAttachmentItem(enum class E_AttachmentType AttachmentType, const struct FS_InvItem& AttachmentItem, class ABP_MasterAttachment_C* Attachment, const struct FS_InvSlot& AmmoItemL, const struct FS_AttachmentSlot& AttachmentL, bool CallFunc_SelectAttachmentItem_IsValid, const struct FS_AttachmentSlot& CallFunc_SelectAttachmentItem_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess, const struct FS_AttachmentSlot& K2Node_SetFieldsInStruct_StructOut);
	void SGK_UpdateAllAttachments();
	void MulticastUpdateAttachmentItem(enum class E_AttachmentType Attachment, const struct FS_InvItem& Item, class ABP_MasterAttachment_C* Actor);
	void ServerAddWeaponAttachment(const struct FS_InvItem& AttachmentItem, bool AnimationSocket);
	void SGK_LoadWeaponAttachments(bool Visible);
	void UpdateAttachmentUsingPlayers();
	void SGK_RemoveAttachment(enum class E_AttachmentType Attachment);
	void SGK_ShowAttachments();
	void SGK_DestroyWeaponAttachments();
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_WeaponInventory(int32 EntryPoint, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, uint8 CallFunc_Conv_IntToByte_ReturnValue, uint8 CallFunc_GetEnumeratorValueFromIndex_ReturnValue, int32 CallFunc_Conv_ByteToInt_ReturnValue, TSet<enum class E_FireModes> Temp_byte_Variable, int32 Temp_int_Variable_1, uint8 CallFunc_Conv_IntToByte_ReturnValue_1, uint8 CallFunc_GetValidValue_ReturnValue, int32 Temp_int_Variable_2, int32 CallFunc_MakeLiteralInt_ReturnValue, uint8 CallFunc_Conv_IntToByte_ReturnValue_2, int32 CallFunc_Subtract_IntInt_ReturnValue, uint8 CallFunc_GetValidValue_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_SelectAttachmentItem_IsValid, const struct FS_AttachmentSlot& CallFunc_SelectAttachmentItem_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_IsValid_ReturnValue, enum class E_AttachmentType K2Node_CustomEvent_Attachment, const struct FS_InvItem& K2Node_CustomEvent_Item, class ABP_MasterAttachment_C* K2Node_CustomEvent_Actor, const struct FS_InvItem& K2Node_CustomEvent_AttachmentItem, bool K2Node_CustomEvent_AnimationSocket, bool K2Node_Event_Visible, enum class E_AttachmentType K2Node_Event_Attachment, int32 Temp_int_Variable_3, uint8 CallFunc_Conv_IntToByte_ReturnValue_3, uint8 CallFunc_GetValidValue_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_2, bool CallFunc_SelectAttachmentItem_IsValid_1, const struct FS_AttachmentSlot& CallFunc_SelectAttachmentItem_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_IsServer_ReturnValue, bool CallFunc_IsStandalone_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, int32 CallFunc_MakeLiteralInt_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_2, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue_1, class APlayerController* CallFunc_GetPlayerController_ReturnValue, class UBP_PlayerInventory_C* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsDedicatedServer_ReturnValue, const struct FS_WeaponSlot& CallFunc_SelectedWeaponSlot_ReturnValue, bool CallFunc_IsValid_ReturnValue_3, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, int32 CallFunc_MakeLiteralInt_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue, const struct FS_InvItem& K2Node_MakeStruct_S_InvItem, bool CallFunc_SGK_ItemHoldableDetails_ItemFound, const struct FS_HoldableDetails& CallFunc_SGK_ItemHoldableDetails_ItemHoldableDetails, bool CallFunc_IsServer_ReturnValue_1, class UClass* K2Node_ClassDynamicCast_AsBP_Master_Range_Weapon, bool K2Node_ClassDynamicCast_bSuccess, TArray<enum class E_FireModes>& CallFunc_Set_ToArray_Result, enum class E_FireModes CallFunc_Array_Get_Item);
};

}


