#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CW_Icon

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass CW_Icon.CW_Icon_C
// 0x0060 (0x02D8 - 0x0278)
class UCW_Icon_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 BackPlate;                                         // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Gradient;                                          // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x0290(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class URetainerBox*                           RetainerBox_62;                                    // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FLinearColor                           BackPlateColor;                                    // 0x02A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FLinearColor                           IconColor;                                         // 0x02B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FLinearColor                           GradientColor;                                     // 0x02C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UTexture2D*                             IconImage;                                         // 0x02D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void PreConstruct(bool IsDesignTime);
	struct FLinearColor GetColorAndOpacity();
	struct FSlateBrush GetBrush();
	struct FLinearColor Get_Gradient_ColorAndOpacity();
	struct FLinearColor Get_BackPlate_ColorAndOpacity();
	void ExecuteUbergraph_CW_Icon(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CW_Icon_C">();
	}
	static class UCW_Icon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCW_Icon_C>();
	}
};
static_assert(alignof(UCW_Icon_C) == 0x000008, "Wrong alignment on UCW_Icon_C");
static_assert(sizeof(UCW_Icon_C) == 0x0002D8, "Wrong size on UCW_Icon_C");
static_assert(offsetof(UCW_Icon_C, UberGraphFrame) == 0x000278, "Member 'UCW_Icon_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UCW_Icon_C, BackPlate) == 0x000280, "Member 'UCW_Icon_C::BackPlate' has a wrong offset!");
static_assert(offsetof(UCW_Icon_C, Gradient) == 0x000288, "Member 'UCW_Icon_C::Gradient' has a wrong offset!");
static_assert(offsetof(UCW_Icon_C, Image) == 0x000290, "Member 'UCW_Icon_C::Image' has a wrong offset!");
static_assert(offsetof(UCW_Icon_C, RetainerBox_62) == 0x000298, "Member 'UCW_Icon_C::RetainerBox_62' has a wrong offset!");
static_assert(offsetof(UCW_Icon_C, BackPlateColor) == 0x0002A0, "Member 'UCW_Icon_C::BackPlateColor' has a wrong offset!");
static_assert(offsetof(UCW_Icon_C, IconColor) == 0x0002B0, "Member 'UCW_Icon_C::IconColor' has a wrong offset!");
static_assert(offsetof(UCW_Icon_C, GradientColor) == 0x0002C0, "Member 'UCW_Icon_C::GradientColor' has a wrong offset!");
static_assert(offsetof(UCW_Icon_C, IconImage) == 0x0002D0, "Member 'UCW_Icon_C::IconImage' has a wrong offset!");

}

