#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_WeaponSlots

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_WeaponSlots.E_WeaponSlots
// NumValues: 0x0004
enum class E_WeaponSlots : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	E_MAX                                    = 3,
};

}

