#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_WorldActions

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_WorldActions.E_WorldActions
// NumValues: 0x000C
enum class E_WorldActions : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator8                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator2                           = 3,
	NewEnumerator3                           = 4,
	NewEnumerator4                           = 5,
	NewEnumerator5                           = 6,
	NewEnumerator6                           = 7,
	NewEnumerator7                           = 8,
	NewEnumerator9                           = 9,
	NewEnumerator10                          = 10,
	E_MAX                                    = 11,
};

}

