#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EWeaponCategories

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EWeaponCategories.EWeaponCategories
// NumValues: 0x0005
enum class EWeaponCategories : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	EWeaponCategories_MAX                    = 4,
};

}

