#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FL_GlobalRank

#include "Basic.hpp"

#include "FL_GlobalRank_classes.hpp"
#include "FL_GlobalRank_parameters.hpp"


namespace SDK
{

// Function FL_GlobalRank.FL_GlobalRank_C.GetGlobalRankInformation
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    Sucess                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FS_GlobalRank                    ResultRankInformation                                  (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UFL_GlobalRank_C::GetGlobalRankInformation(int32 Value, class UObject* __WorldContext, bool* Sucess, struct FS_GlobalRank* ResultRankInformation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("FL_GlobalRank_C", "GetGlobalRankInformation");

	Params::FL_GlobalRank_C_GetGlobalRankInformation Parms{};

	Parms.Value = Value;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (Sucess != nullptr)
		*Sucess = Parms.Sucess;

	if (ResultRankInformation != nullptr)
		*ResultRankInformation = std::move(Parms.ResultRankInformation);
}

}

