#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MinimapInternal_BackgroundMouseCapture

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MinimapInternal_BackgroundMouseCapture.MinimapInternal_BackgroundMouseCapture_C
// 0x0068 (0x02E0 - 0x0278)
class UMinimapInternal_BackgroundMouseCapture_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          MouseDownStarted;                                  // 0x0280(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          MouseDragStarted;                                  // 0x0281(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3536[0x6];                                     // 0x0282(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              MouseDownPos;                                      // 0x0288(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        MouseDownTime;                                     // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        MouseMoveThreshold;                                // 0x02A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             OnMouseClick;                                      // 0x02A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnBoxSelect;                                       // 0x02B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          MouseDown_IsLeft;                                  // 0x02C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          MouseDown_IsShift;                                 // 0x02C9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          MouseDown_IsCtrl;                                  // 0x02CA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bEnableBoxSelect;                                  // 0x02CB(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           BoxSelectColor;                                    // 0x02CC(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_MinimapInternal_BackgroundMouseCapture(int32 EntryPoint);
	void OnBoxSelect__DelegateSignature(const struct FVector2D& StartUV, const struct FVector2D& EndUV, bool IsLeftMouseButton, bool IsShiftSelect, bool IsCtrlSelect);
	void OnBoxSelect_Event_0(const struct FVector2D& StartUV, const struct FVector2D& EndUV, bool IsLeftMouseButton, bool IsShiftSelect, bool IsCtrlSelect);
	struct FEventReply OnMouseButtonDoubleClick(const struct FGeometry& InMyGeometry, const struct FPointerEvent& InMouseEvent);
	struct FEventReply OnMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	struct FEventReply OnMouseButtonUp(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void OnMouseClick__DelegateSignature(const struct FVector2D& UV, bool IsLeftMouseButton);
	void OnMouseLeave(const struct FPointerEvent& MouseEvent);
	struct FEventReply OnMouseMove(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void Start_Drag(const struct FGeometry& MapGeo, const struct FVector2D& StartPos, const struct FVector2D& StartOffset, bool IsLeftMouseButton, bool IsShiftSelect, bool IsCtrlSelect);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MinimapInternal_BackgroundMouseCapture_C">();
	}
	static class UMinimapInternal_BackgroundMouseCapture_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMinimapInternal_BackgroundMouseCapture_C>();
	}
};
static_assert(alignof(UMinimapInternal_BackgroundMouseCapture_C) == 0x000008, "Wrong alignment on UMinimapInternal_BackgroundMouseCapture_C");
static_assert(sizeof(UMinimapInternal_BackgroundMouseCapture_C) == 0x0002E0, "Wrong size on UMinimapInternal_BackgroundMouseCapture_C");
static_assert(offsetof(UMinimapInternal_BackgroundMouseCapture_C, UberGraphFrame) == 0x000278, "Member 'UMinimapInternal_BackgroundMouseCapture_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_BackgroundMouseCapture_C, MouseDownStarted) == 0x000280, "Member 'UMinimapInternal_BackgroundMouseCapture_C::MouseDownStarted' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_BackgroundMouseCapture_C, MouseDragStarted) == 0x000281, "Member 'UMinimapInternal_BackgroundMouseCapture_C::MouseDragStarted' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_BackgroundMouseCapture_C, MouseDownPos) == 0x000288, "Member 'UMinimapInternal_BackgroundMouseCapture_C::MouseDownPos' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_BackgroundMouseCapture_C, MouseDownTime) == 0x000298, "Member 'UMinimapInternal_BackgroundMouseCapture_C::MouseDownTime' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_BackgroundMouseCapture_C, MouseMoveThreshold) == 0x0002A0, "Member 'UMinimapInternal_BackgroundMouseCapture_C::MouseMoveThreshold' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_BackgroundMouseCapture_C, OnMouseClick) == 0x0002A8, "Member 'UMinimapInternal_BackgroundMouseCapture_C::OnMouseClick' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_BackgroundMouseCapture_C, OnBoxSelect) == 0x0002B8, "Member 'UMinimapInternal_BackgroundMouseCapture_C::OnBoxSelect' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_BackgroundMouseCapture_C, MouseDown_IsLeft) == 0x0002C8, "Member 'UMinimapInternal_BackgroundMouseCapture_C::MouseDown_IsLeft' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_BackgroundMouseCapture_C, MouseDown_IsShift) == 0x0002C9, "Member 'UMinimapInternal_BackgroundMouseCapture_C::MouseDown_IsShift' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_BackgroundMouseCapture_C, MouseDown_IsCtrl) == 0x0002CA, "Member 'UMinimapInternal_BackgroundMouseCapture_C::MouseDown_IsCtrl' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_BackgroundMouseCapture_C, bEnableBoxSelect) == 0x0002CB, "Member 'UMinimapInternal_BackgroundMouseCapture_C::bEnableBoxSelect' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_BackgroundMouseCapture_C, BoxSelectColor) == 0x0002CC, "Member 'UMinimapInternal_BackgroundMouseCapture_C::BoxSelectColor' has a wrong offset!");

}

