#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MinimapInternal_Fog

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MinimapInternal_Fog.MinimapInternal_Fog_C
// 0x0030 (0x02A8 - 0x0278)
class UMinimapInternal_Fog_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_Fog;                                         // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMapViewComponent*                      MapViewComp;                                       // 0x0288(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class AMapFog*                                MapFog;                                            // 0x0290(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               FogMatInst;                                        // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        StartTime;                                         // 0x02A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Construct();
	void Destruct();
	void ExecuteUbergraph_MinimapInternal_Fog(int32 EntryPoint);
	void OnEndPlay(class AActor* Actor, EEndPlayReason EndPlayReason);
	void OnMapFogMaterialChanged_Event_0(class AMapFog* Param_MapFog);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void TickFog();
	void UpdateMaterial();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MinimapInternal_Fog_C">();
	}
	static class UMinimapInternal_Fog_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMinimapInternal_Fog_C>();
	}
};
static_assert(alignof(UMinimapInternal_Fog_C) == 0x000008, "Wrong alignment on UMinimapInternal_Fog_C");
static_assert(sizeof(UMinimapInternal_Fog_C) == 0x0002A8, "Wrong size on UMinimapInternal_Fog_C");
static_assert(offsetof(UMinimapInternal_Fog_C, UberGraphFrame) == 0x000278, "Member 'UMinimapInternal_Fog_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_Fog_C, Image_Fog) == 0x000280, "Member 'UMinimapInternal_Fog_C::Image_Fog' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_Fog_C, MapViewComp) == 0x000288, "Member 'UMinimapInternal_Fog_C::MapViewComp' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_Fog_C, MapFog) == 0x000290, "Member 'UMinimapInternal_Fog_C::MapFog' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_Fog_C, FogMatInst) == 0x000298, "Member 'UMinimapInternal_Fog_C::FogMatInst' has a wrong offset!");
static_assert(offsetof(UMinimapInternal_Fog_C, StartTime) == 0x0002A0, "Member 'UMinimapInternal_Fog_C::StartTime' has a wrong offset!");

}

