#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Peak53Teams

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum Peak53Teams.Peak53Teams
// NumValues: 0x0004
enum class EPeak53Teams : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	Peak53Teams_MAX                          = 3,
};

}

