#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_ControlsSave

#include "Basic.hpp"

#include "InputCore_structs.hpp"


namespace SDK
{

// UserDefinedStruct S_ControlsSave.S_ControlsSave
// 0x0050 (0x0050 - 0x0000)
struct FS_ControlsSave final
{
public:
	TSoftObjectPtr<class UInputMappingContext>    MappingContext_14_DA01F9074C94EB7F9BEB5F84A2A80D3E; // 0x0000(0x0030)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TArray<class FName>                           KeyNames_12_7FCBF14F470DC875E838FEAF46FE54E1;      // 0x0030(0x0010)(Edit, BlueprintVisible)
	TArray<struct FKey>                           KeyMappings_13_0C0EFF6E4C858516556E00832838C730;   // 0x0040(0x0010)(Edit, BlueprintVisible)
};
static_assert(alignof(FS_ControlsSave) == 0x000008, "Wrong alignment on FS_ControlsSave");
static_assert(sizeof(FS_ControlsSave) == 0x000050, "Wrong size on FS_ControlsSave");
static_assert(offsetof(FS_ControlsSave, MappingContext_14_DA01F9074C94EB7F9BEB5F84A2A80D3E) == 0x000000, "Member 'FS_ControlsSave::MappingContext_14_DA01F9074C94EB7F9BEB5F84A2A80D3E' has a wrong offset!");
static_assert(offsetof(FS_ControlsSave, KeyNames_12_7FCBF14F470DC875E838FEAF46FE54E1) == 0x000030, "Member 'FS_ControlsSave::KeyNames_12_7FCBF14F470DC875E838FEAF46FE54E1' has a wrong offset!");
static_assert(offsetof(FS_ControlsSave, KeyMappings_13_0C0EFF6E4C858516556E00832838C730) == 0x000040, "Member 'FS_ControlsSave::KeyMappings_13_0C0EFF6E4C858516556E00832838C730' has a wrong offset!");

}

