#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_ItemSpawnerSave

#include "Basic.hpp"

#include "S_MasterItemSave_structs.hpp"


namespace SDK
{

// UserDefinedStruct S_ItemSpawnerSave.S_ItemSpawnerSave
// 0x0098 (0x0098 - 0x0000)
struct FS_ItemSpawnerSave final
{
public:
	class ABP_MasterItemSpawner_C*                ItemSpawner_13_397861C6497928D5F5ACF6BE5F4FD544;   // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	struct FS_MasterItemSave                      Item_5_8DB163AF452230FC685D7D96EB5A9630;           // 0x0008(0x0090)(Edit, BlueprintVisible, ContainsInstancedReference, HasGetValueTypeHash)
};
static_assert(alignof(FS_ItemSpawnerSave) == 0x000008, "Wrong alignment on FS_ItemSpawnerSave");
static_assert(sizeof(FS_ItemSpawnerSave) == 0x000098, "Wrong size on FS_ItemSpawnerSave");
static_assert(offsetof(FS_ItemSpawnerSave, ItemSpawner_13_397861C6497928D5F5ACF6BE5F4FD544) == 0x000000, "Member 'FS_ItemSpawnerSave::ItemSpawner_13_397861C6497928D5F5ACF6BE5F4FD544' has a wrong offset!");
static_assert(offsetof(FS_ItemSpawnerSave, Item_5_8DB163AF452230FC685D7D96EB5A9630) == 0x000008, "Member 'FS_ItemSpawnerSave::Item_5_8DB163AF452230FC685D7D96EB5A9630' has a wrong offset!");

}

