#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ScopeWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ScopeWidget.ScopeWidget_C
// 0x0018 (0x0290 - 0x0278)
class UScopeWidget_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Background;                                        // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Text;                                              // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();
	void DT_Event(class FName RowName);
	void ExecuteUbergraph_ScopeWidget(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ScopeWidget_C">();
	}
	static class UScopeWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScopeWidget_C>();
	}
};
static_assert(alignof(UScopeWidget_C) == 0x000008, "Wrong alignment on UScopeWidget_C");
static_assert(sizeof(UScopeWidget_C) == 0x000290, "Wrong size on UScopeWidget_C");
static_assert(offsetof(UScopeWidget_C, UberGraphFrame) == 0x000278, "Member 'UScopeWidget_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UScopeWidget_C, Background) == 0x000280, "Member 'UScopeWidget_C::Background' has a wrong offset!");
static_assert(offsetof(UScopeWidget_C, Text) == 0x000288, "Member 'UScopeWidget_C::Text' has a wrong offset!");

}

