#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MainMenu

#include "Basic.hpp"

#include "E_MenuCameras_structs.hpp"


namespace SDK::Params
{

// Function W_MainMenu.W_MainMenu_C.Get_TitleWindow_Text
// 0x0040 (0x0040 - 0x0000)
struct W_MainMenu_C_Get_TitleWindow_Text final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class FString                                 CallFunc_GetEnumeratorUserFriendlyName_ReturnValue; // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0028(0x0018)()
};
static_assert(alignof(W_MainMenu_C_Get_TitleWindow_Text) == 0x000008, "Wrong alignment on W_MainMenu_C_Get_TitleWindow_Text");
static_assert(sizeof(W_MainMenu_C_Get_TitleWindow_Text) == 0x000040, "Wrong size on W_MainMenu_C_Get_TitleWindow_Text");
static_assert(offsetof(W_MainMenu_C_Get_TitleWindow_Text, ReturnValue) == 0x000000, "Member 'W_MainMenu_C_Get_TitleWindow_Text::ReturnValue' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_Get_TitleWindow_Text, CallFunc_GetEnumeratorUserFriendlyName_ReturnValue) == 0x000018, "Member 'W_MainMenu_C_Get_TitleWindow_Text::CallFunc_GetEnumeratorUserFriendlyName_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_Get_TitleWindow_Text, CallFunc_Conv_StringToText_ReturnValue) == 0x000028, "Member 'W_MainMenu_C_Get_TitleWindow_Text::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");

// Function W_MainMenu.W_MainMenu_C.ExecuteUbergraph_W_MainMenu
// 0x0110 (0x0110 - 0x0000)
struct W_MainMenu_C_ExecuteUbergraph_W_MainMenu final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	E_MenuCameras                                 Temp_byte_Variable;                                // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5897[0x3];                                     // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UCommonActivatableWidget>   Temp_class_Variable;                               // 0x0018(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TSubclassOf<class UCommonActivatableWidget>   Temp_class_Variable_1;                             // 0x0020(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TSubclassOf<class UCommonActivatableWidget>   Temp_class_Variable_2;                             // 0x0028(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TSubclassOf<class UCommonActivatableWidget>   Temp_class_Variable_3;                             // 0x0030(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TSubclassOf<class UCommonActivatableWidget>   Temp_class_Variable_4;                             // 0x0038(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TSubclassOf<class UCommonActivatableWidget>   Temp_class_Variable_5;                             // 0x0040(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TSubclassOf<class UCommonActivatableWidget>   Temp_class_Variable_6;                             // 0x0048(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TSubclassOf<class UCommonActivatableWidget>   Temp_class_Variable_7;                             // 0x0050(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TSubclassOf<class UCommonActivatableWidget>   Temp_class_Variable_8;                             // 0x0058(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TSubclassOf<class UCommonActivatableWidget>   Temp_class_Variable_9;                             // 0x0060(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TSubclassOf<class UCommonActivatableWidget>   Temp_class_Variable_10;                            // 0x0068(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5898[0x7];                                     // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UCommonActivatableWidget>   Temp_class_Variable_11;                            // 0x0078(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TSubclassOf<class UCommonActivatableWidget>   Temp_class_Variable_12;                            // 0x0080(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5899[0x7];                                     // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UCommonActivatableWidget>   Temp_class_Variable_13;                            // 0x0090(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TSubclassOf<class UCommonActivatableWidget>   Temp_class_Variable_14;                            // 0x0098(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_CreatePlayAnimationProxyObject_Result;    // 0x00A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimationPlayCallbackProxy*      CallFunc_CreatePlayAnimationProxyObject_ReturnValue; // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_MenuCameras                                 K2Node_CustomEvent_MenuCamera;                     // 0x00B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_589A[0x6];                                     // 0x00B2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetCurrentLevelName_ReturnValue;          // 0x00B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UCommonActivatableWidget*               CallFunc_GetActiveWidget_ReturnValue;              // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Contains_ReturnValue;                     // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_589B[0x7];                                     // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UCommonActivatableWidget>   K2Node_Select_Default;                             // 0x00D8(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TSubclassOf<class UCommonActivatableWidget>   K2Node_Select_Default_1;                           // 0x00E0(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TSubclassOf<class UCommonActivatableWidget>   K2Node_Select_Default_2;                           // 0x00F0(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UBP_SGKGameInstance_C*                  K2Node_DynamicCast_AsBP_SGKGame_Instance;          // 0x00F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_589C[0x7];                                     // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonActivatableWidget*               CallFunc_BP_AddWidget_ReturnValue;                 // 0x0108(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu) == 0x000008, "Wrong alignment on W_MainMenu_C_ExecuteUbergraph_W_MainMenu");
static_assert(sizeof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu) == 0x000110, "Wrong size on W_MainMenu_C_ExecuteUbergraph_W_MainMenu");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, EntryPoint) == 0x000000, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_byte_Variable) == 0x000014, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_class_Variable) == 0x000018, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_class_Variable' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_class_Variable_1) == 0x000020, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_class_Variable_1' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_class_Variable_2) == 0x000028, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_class_Variable_2' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_class_Variable_3) == 0x000030, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_class_Variable_3' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_class_Variable_4) == 0x000038, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_class_Variable_4' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_class_Variable_5) == 0x000040, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_class_Variable_5' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_class_Variable_6) == 0x000048, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_class_Variable_6' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_class_Variable_7) == 0x000050, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_class_Variable_7' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_class_Variable_8) == 0x000058, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_class_Variable_8' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_class_Variable_9) == 0x000060, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_class_Variable_9' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_class_Variable_10) == 0x000068, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_class_Variable_10' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_bool_Variable) == 0x000070, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_class_Variable_11) == 0x000078, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_class_Variable_11' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_class_Variable_12) == 0x000080, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_class_Variable_12' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_bool_Variable_1) == 0x000088, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_class_Variable_13) == 0x000090, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_class_Variable_13' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, Temp_class_Variable_14) == 0x000098, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::Temp_class_Variable_14' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, CallFunc_CreatePlayAnimationProxyObject_Result) == 0x0000A0, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::CallFunc_CreatePlayAnimationProxyObject_Result' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, CallFunc_CreatePlayAnimationProxyObject_ReturnValue) == 0x0000A8, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::CallFunc_CreatePlayAnimationProxyObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, CallFunc_IsValid_ReturnValue) == 0x0000B0, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, K2Node_CustomEvent_MenuCamera) == 0x0000B1, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::K2Node_CustomEvent_MenuCamera' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, CallFunc_GetCurrentLevelName_ReturnValue) == 0x0000B8, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::CallFunc_GetCurrentLevelName_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, CallFunc_GetActiveWidget_ReturnValue) == 0x0000C8, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::CallFunc_GetActiveWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, CallFunc_Contains_ReturnValue) == 0x0000D0, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::CallFunc_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, K2Node_Select_Default) == 0x0000D8, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, K2Node_Select_Default_1) == 0x0000E0, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, CallFunc_GetGameInstance_ReturnValue) == 0x0000E8, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, K2Node_Select_Default_2) == 0x0000F0, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, K2Node_DynamicCast_AsBP_SGKGame_Instance) == 0x0000F8, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::K2Node_DynamicCast_AsBP_SGKGame_Instance' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, K2Node_DynamicCast_bSuccess) == 0x000100, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(W_MainMenu_C_ExecuteUbergraph_W_MainMenu, CallFunc_BP_AddWidget_ReturnValue) == 0x000108, "Member 'W_MainMenu_C_ExecuteUbergraph_W_MainMenu::CallFunc_BP_AddWidget_ReturnValue' has a wrong offset!");

// Function W_MainMenu.W_MainMenu_C.ButtonClicked_Event
// 0x0001 (0x0001 - 0x0000)
struct W_MainMenu_C_ButtonClicked_Event final
{
public:
	E_MenuCameras                                 MenuCamera;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_MainMenu_C_ButtonClicked_Event) == 0x000001, "Wrong alignment on W_MainMenu_C_ButtonClicked_Event");
static_assert(sizeof(W_MainMenu_C_ButtonClicked_Event) == 0x000001, "Wrong size on W_MainMenu_C_ButtonClicked_Event");
static_assert(offsetof(W_MainMenu_C_ButtonClicked_Event, MenuCamera) == 0x000000, "Member 'W_MainMenu_C_ButtonClicked_Event::MenuCamera' has a wrong offset!");

}

