#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Menu_INK

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "W_WindowBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_Menu_INK.W_Menu_INK_C
// 0x00D8 (0x04B0 - 0x03D8)
class UW_Menu_INK_C final : public UW_WindowBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Button_0;                                          // 0x03E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_CreateSession;                              // 0x03E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_0;                                   // 0x03F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x03F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_1;                                           // 0x0400(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_2;                                           // 0x0408(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_53;                                          // 0x0410(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_77;                                          // 0x0418(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_Text_Button_C*                      InkClothing;                                       // 0x0420(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                InkOutfit;                                         // 0x0428(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_Text_Button_C*                      InkOutfits;                                        // 0x0430(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_Text_Button_C*                      Loadouts;                                          // 0x0438(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCW_MenuButton_C*                       Lobby_1;                                           // 0x0440(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_Text_Button_C*                      Menu;                                              // 0x0448(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_Text_Button_C*                      P53Clothing;                                       // 0x0450(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                P53outfit;                                         // 0x0458(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_Text_Button_C*                      P53Outfits;                                        // 0x0460(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_Text_Button_C*                      Quit;                                              // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCW_MenuButton_C*                       Store_3;                                           // 0x0470(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCW_MenuButton_C*                       Store_5;                                           // 0x0478(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_Text_Button_C*                      WB_Text_Button_2;                                  // 0x0480(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_Text_Button_C*                      WB_Text_Button_6;                                  // 0x0488(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_Menu_INK_create_server_C*            W_create_server;                                   // 0x0490(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Update_Sound_Cue;                                  // 0x0498(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	float                                         Duration;                                          // 0x04A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_56AA[0x4];                                     // 0x04A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           TimerRef;                                          // 0x04A8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__W_Menu_INK_Button_0_K2Node_ComponentBoundEvent_9_OnButtonPressedEvent__DelegateSignature();
	void BndEvt__W_Menu_INK_Button_CreateSession_1_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__W_Menu_INK_Button_CreateSession_2_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__W_Menu_INK_Button_CreateSession_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__W_Menu_INK_Lobby_1_K2Node_ComponentBoundEvent_6_ButtonPressed__DelegateSignature();
	void BndEvt__W_Menu_INK_p53Clothing_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_Menu_INK_Store_3_K2Node_ComponentBoundEvent_3_ButtonPressed__DelegateSignature();
	void BndEvt__W_Menu_INK_WB_Text_Button_1_K2Node_ComponentBoundEvent_19_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_Menu_INK_WB_Text_Button_2_K2Node_ComponentBoundEvent_12_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_Menu_INK_WB_Text_Button_3_K2Node_ComponentBoundEvent_17_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_Menu_INK_WB_Text_Button_4_K2Node_ComponentBoundEvent_15_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_Menu_INK_WB_Text_Button_5_K2Node_ComponentBoundEvent_14_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_Menu_INK_WB_Text_Button_6_K2Node_ComponentBoundEvent_13_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_Menu_INK_WB_Text_Button_7_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__W_Menu_INK_WB_Text_Button_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BP_OnActivated();
	void CloseCreateServerWidget();
	void Construct();
	void Destruct();
	void ExecuteUbergraph_W_Menu_INK(int32 EntryPoint);
	void StartTimer();
	void TimerLogic();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_Menu_INK_C">();
	}
	static class UW_Menu_INK_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_Menu_INK_C>();
	}
};
static_assert(alignof(UW_Menu_INK_C) == 0x000008, "Wrong alignment on UW_Menu_INK_C");
static_assert(sizeof(UW_Menu_INK_C) == 0x0004B0, "Wrong size on UW_Menu_INK_C");
static_assert(offsetof(UW_Menu_INK_C, UberGraphFrame) == 0x0003D8, "Member 'UW_Menu_INK_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, Button_0) == 0x0003E0, "Member 'UW_Menu_INK_C::Button_0' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, Button_CreateSession) == 0x0003E8, "Member 'UW_Menu_INK_C::Button_CreateSession' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, HorizontalBox_0) == 0x0003F0, "Member 'UW_Menu_INK_C::HorizontalBox_0' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, Image) == 0x0003F8, "Member 'UW_Menu_INK_C::Image' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, Image_1) == 0x000400, "Member 'UW_Menu_INK_C::Image_1' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, Image_2) == 0x000408, "Member 'UW_Menu_INK_C::Image_2' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, Image_53) == 0x000410, "Member 'UW_Menu_INK_C::Image_53' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, Image_77) == 0x000418, "Member 'UW_Menu_INK_C::Image_77' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, InkClothing) == 0x000420, "Member 'UW_Menu_INK_C::InkClothing' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, InkOutfit) == 0x000428, "Member 'UW_Menu_INK_C::InkOutfit' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, InkOutfits) == 0x000430, "Member 'UW_Menu_INK_C::InkOutfits' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, Loadouts) == 0x000438, "Member 'UW_Menu_INK_C::Loadouts' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, Lobby_1) == 0x000440, "Member 'UW_Menu_INK_C::Lobby_1' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, Menu) == 0x000448, "Member 'UW_Menu_INK_C::Menu' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, P53Clothing) == 0x000450, "Member 'UW_Menu_INK_C::P53Clothing' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, P53outfit) == 0x000458, "Member 'UW_Menu_INK_C::P53outfit' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, P53Outfits) == 0x000460, "Member 'UW_Menu_INK_C::P53Outfits' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, Quit) == 0x000468, "Member 'UW_Menu_INK_C::Quit' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, Store_3) == 0x000470, "Member 'UW_Menu_INK_C::Store_3' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, Store_5) == 0x000478, "Member 'UW_Menu_INK_C::Store_5' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, WB_Text_Button_2) == 0x000480, "Member 'UW_Menu_INK_C::WB_Text_Button_2' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, WB_Text_Button_6) == 0x000488, "Member 'UW_Menu_INK_C::WB_Text_Button_6' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, W_create_server) == 0x000490, "Member 'UW_Menu_INK_C::W_create_server' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, Update_Sound_Cue) == 0x000498, "Member 'UW_Menu_INK_C::Update_Sound_Cue' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, Duration) == 0x0004A0, "Member 'UW_Menu_INK_C::Duration' has a wrong offset!");
static_assert(offsetof(UW_Menu_INK_C, TimerRef) == 0x0004A8, "Member 'UW_Menu_INK_C::TimerRef' has a wrong offset!");

}

