#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_Child_Credits

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function WB_Child_Credits.WB_Child_Credits_C.AddChildToScrollBox
// 0x0018 (0x0018 - 0x0000)
struct WB_Child_Credits_C_AddChildToScrollBox final
{
public:
	class UWidget*                                Content;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Child_Credits_C_AddChildToScrollBox) == 0x000008, "Wrong alignment on WB_Child_Credits_C_AddChildToScrollBox");
static_assert(sizeof(WB_Child_Credits_C_AddChildToScrollBox) == 0x000018, "Wrong size on WB_Child_Credits_C_AddChildToScrollBox");
static_assert(offsetof(WB_Child_Credits_C_AddChildToScrollBox, Content) == 0x000000, "Member 'WB_Child_Credits_C_AddChildToScrollBox::Content' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_AddChildToScrollBox, ReturnValue) == 0x000008, "Member 'WB_Child_Credits_C_AddChildToScrollBox::ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_AddChildToScrollBox, CallFunc_AddChild_ReturnValue) == 0x000010, "Member 'WB_Child_Credits_C_AddChildToScrollBox::CallFunc_AddChild_ReturnValue' has a wrong offset!");

// Function WB_Child_Credits.WB_Child_Credits_C.CreateAndAddCommonText
// 0x0048 (0x0048 - 0x0000)
struct WB_Child_Credits_C_CreateAndAddCommonText final
{
public:
	TSubclassOf<class UCommonTextStyle>           Style;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class FText                                   InText;                                            // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FMargin                                InPadding;                                         // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	class UCommonTextBlock*                       CallFunc_SpawnObject_ReturnValue;                  // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UScrollBoxSlot*                         CallFunc_SlotAsScrollBoxSlot_ReturnValue;          // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChildToScrollBox_ReturnValue;          // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Child_Credits_C_CreateAndAddCommonText) == 0x000008, "Wrong alignment on WB_Child_Credits_C_CreateAndAddCommonText");
static_assert(sizeof(WB_Child_Credits_C_CreateAndAddCommonText) == 0x000048, "Wrong size on WB_Child_Credits_C_CreateAndAddCommonText");
static_assert(offsetof(WB_Child_Credits_C_CreateAndAddCommonText, Style) == 0x000000, "Member 'WB_Child_Credits_C_CreateAndAddCommonText::Style' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_CreateAndAddCommonText, InText) == 0x000008, "Member 'WB_Child_Credits_C_CreateAndAddCommonText::InText' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_CreateAndAddCommonText, InPadding) == 0x000020, "Member 'WB_Child_Credits_C_CreateAndAddCommonText::InPadding' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_CreateAndAddCommonText, CallFunc_SpawnObject_ReturnValue) == 0x000030, "Member 'WB_Child_Credits_C_CreateAndAddCommonText::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_CreateAndAddCommonText, CallFunc_SlotAsScrollBoxSlot_ReturnValue) == 0x000038, "Member 'WB_Child_Credits_C_CreateAndAddCommonText::CallFunc_SlotAsScrollBoxSlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_CreateAndAddCommonText, CallFunc_AddChildToScrollBox_ReturnValue) == 0x000040, "Member 'WB_Child_Credits_C_CreateAndAddCommonText::CallFunc_AddChildToScrollBox_ReturnValue' has a wrong offset!");

// Function WB_Child_Credits.WB_Child_Credits_C.ExecuteUbergraph_WB_Child_Credits
// 0x0168 (0x0168 - 0x0000)
struct WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FMargin                                K2Node_MakeStruct_Margin;                          // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FMargin                                K2Node_MakeStruct_Margin_1;                        // 0x0014(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bUsingGamepad;                        // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A67[0x6];                                     // 0x0032(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0038(0x0040)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetScrollOffsetOfEnd_ReturnValue;         // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_MapRangeClamped_ReturnValue;              // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_MapRangeClamped_ReturnValue_1;            // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Finterpolate_ReturnValue;                 // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A68[0x6];                                     // 0x009A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class USpacer*                                CallFunc_SpawnObject_ReturnValue;                  // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChildToScrollBox_ReturnValue;          // 0x00A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x00B0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USpacer*                                CallFunc_SpawnObject_ReturnValue_1;                // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChildToScrollBox_ReturnValue_1;        // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue_1;               // 0x00D0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A69[0x7];                                     // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FName>                           CallFunc_Map_Keys_Keys;                            // 0x00E8(0x0010)(ReferenceParm)
	class FName                                   CallFunc_Array_Get_Item;                           // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A6A[0x4];                                     // 0x0104(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_NameToText_ReturnValue;              // 0x0108(0x0018)()
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A6B[0x7];                                     // 0x0121(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Map_Find_Value;                           // 0x0128(0x0018)()
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A6C[0x7];                                     // 0x0141(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_MapRangeClamped_OutRangeB_ImplicitCast;   // 0x0148(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScrollOffset_NewScrollOffset_ImplicitCast; // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A6D[0x4];                                     // 0x0154(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_MakeVector2D_Y_ImplicitCast;              // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_MakeVector2D_Y_ImplicitCast_1;            // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits) == 0x000008, "Wrong alignment on WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits");
static_assert(sizeof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits) == 0x000168, "Wrong size on WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, EntryPoint) == 0x000000, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::EntryPoint' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, K2Node_MakeStruct_Margin) == 0x000004, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::K2Node_MakeStruct_Margin' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, K2Node_MakeStruct_Margin_1) == 0x000014, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::K2Node_MakeStruct_Margin_1' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, Temp_int_Array_Index_Variable) == 0x000024, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, Temp_int_Loop_Counter_Variable) == 0x000028, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_Add_IntInt_ReturnValue) == 0x00002C, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, K2Node_Event_bUsingGamepad) == 0x000030, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::K2Node_Event_bUsingGamepad' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, K2Node_Event_IsDesignTime) == 0x000031, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, K2Node_Event_MyGeometry) == 0x000038, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, K2Node_Event_InDeltaTime) == 0x000078, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_GetScrollOffsetOfEnd_ReturnValue) == 0x00007C, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_GetScrollOffsetOfEnd_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_MapRangeClamped_ReturnValue) == 0x000080, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_MapRangeClamped_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_MapRangeClamped_ReturnValue_1) == 0x000088, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_MapRangeClamped_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_Finterpolate_ReturnValue) == 0x000090, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_Finterpolate_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, Temp_bool_Has_Been_Initd_Variable) == 0x000098, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_GreaterEqual_DoubleDouble_ReturnValue) == 0x000099, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_GreaterEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_SpawnObject_ReturnValue) == 0x0000A0, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_AddChildToScrollBox_ReturnValue) == 0x0000A8, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_AddChildToScrollBox_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_MakeVector2D_ReturnValue) == 0x0000B0, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_SpawnObject_ReturnValue_1) == 0x0000C0, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_SpawnObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_AddChildToScrollBox_ReturnValue_1) == 0x0000C8, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_AddChildToScrollBox_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_MakeVector2D_ReturnValue_1) == 0x0000D0, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_MakeVector2D_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, Temp_bool_IsClosed_Variable) == 0x0000E0, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_Map_Keys_Keys) == 0x0000E8, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_Map_Keys_Keys' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_Array_Get_Item) == 0x0000F8, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_Array_Length_ReturnValue) == 0x000100, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_Conv_NameToText_ReturnValue) == 0x000108, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_Conv_NameToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_Less_IntInt_ReturnValue) == 0x000120, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_Map_Find_Value) == 0x000128, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_Map_Find_ReturnValue) == 0x000140, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_MapRangeClamped_OutRangeB_ImplicitCast) == 0x000148, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_MapRangeClamped_OutRangeB_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_SetScrollOffset_NewScrollOffset_ImplicitCast) == 0x000150, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_SetScrollOffset_NewScrollOffset_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_MakeVector2D_Y_ImplicitCast) == 0x000158, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_MakeVector2D_Y_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits, CallFunc_MakeVector2D_Y_ImplicitCast_1) == 0x000160, "Member 'WB_Child_Credits_C_ExecuteUbergraph_WB_Child_Credits::CallFunc_MakeVector2D_Y_ImplicitCast_1' has a wrong offset!");

// Function WB_Child_Credits.WB_Child_Credits_C.OnInputMethodChanged
// 0x0001 (0x0001 - 0x0000)
struct WB_Child_Credits_C_OnInputMethodChanged final
{
public:
	bool                                          Param_bUsingGamepad;                               // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Child_Credits_C_OnInputMethodChanged) == 0x000001, "Wrong alignment on WB_Child_Credits_C_OnInputMethodChanged");
static_assert(sizeof(WB_Child_Credits_C_OnInputMethodChanged) == 0x000001, "Wrong size on WB_Child_Credits_C_OnInputMethodChanged");
static_assert(offsetof(WB_Child_Credits_C_OnInputMethodChanged, Param_bUsingGamepad) == 0x000000, "Member 'WB_Child_Credits_C_OnInputMethodChanged::Param_bUsingGamepad' has a wrong offset!");

// Function WB_Child_Credits.WB_Child_Credits_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WB_Child_Credits_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Child_Credits_C_PreConstruct) == 0x000001, "Wrong alignment on WB_Child_Credits_C_PreConstruct");
static_assert(sizeof(WB_Child_Credits_C_PreConstruct) == 0x000001, "Wrong size on WB_Child_Credits_C_PreConstruct");
static_assert(offsetof(WB_Child_Credits_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WB_Child_Credits_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WB_Child_Credits.WB_Child_Credits_C.SetScrollOffset
// 0x0004 (0x0004 - 0x0000)
struct WB_Child_Credits_C_SetScrollOffset final
{
public:
	float                                         NewScrollOffset;                                   // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Child_Credits_C_SetScrollOffset) == 0x000004, "Wrong alignment on WB_Child_Credits_C_SetScrollOffset");
static_assert(sizeof(WB_Child_Credits_C_SetScrollOffset) == 0x000004, "Wrong size on WB_Child_Credits_C_SetScrollOffset");
static_assert(offsetof(WB_Child_Credits_C_SetScrollOffset, NewScrollOffset) == 0x000000, "Member 'WB_Child_Credits_C_SetScrollOffset::NewScrollOffset' has a wrong offset!");

// Function WB_Child_Credits.WB_Child_Credits_C.Tick
// 0x0048 (0x0048 - 0x0000)
struct WB_Child_Credits_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0040(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Child_Credits_C_Tick) == 0x000008, "Wrong alignment on WB_Child_Credits_C_Tick");
static_assert(sizeof(WB_Child_Credits_C_Tick) == 0x000048, "Wrong size on WB_Child_Credits_C_Tick");
static_assert(offsetof(WB_Child_Credits_C_Tick, MyGeometry) == 0x000000, "Member 'WB_Child_Credits_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(WB_Child_Credits_C_Tick, InDeltaTime) == 0x000040, "Member 'WB_Child_Credits_C_Tick::InDeltaTime' has a wrong offset!");

}

