#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_EquipmetScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"
#include "ST_LoadoutData_structs.hpp"
#include "E_EquipmentSlots_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_EquipmetScreen.WB_EquipmetScreen_C
// 0x02D0 (0x0548 - 0x0278)
class UWB_EquipmetScreen_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Button_8ody_next;                                  // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_8ody_prev;                                  // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Backpack;                                   // 0x0290(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_backpack_next;                              // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_backpack_prev;                              // 0x02A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Body;                                       // 0x02A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Boots;                                      // 0x02B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Boots_next;                                 // 0x02B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Boots_prev;                                 // 0x02C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_CLOSEMENU;                                  // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Face;                                       // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_face_next;                                  // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_face_prev;                                  // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Gloves;                                     // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Gloves_next;                                // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Gloves_prev;                                // 0x02F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Helmet_2;                                   // 0x0300(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Helmet_next;                                // 0x0308(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Helmet_prev;                                // 0x0310(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_kneepad_next;                               // 0x0318(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_kneepad_prev;                               // 0x0320(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_kneepads;                                   // 0x0328(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Legs;                                       // 0x0330(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_legs_next;                                  // 0x0338(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_legs_prev;                                  // 0x0340(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_lleg;                                       // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_lleg_next;                                  // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_lleg_prev;                                  // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Loadout1;                                   // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Loadout2;                                   // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Loadout3;                                   // 0x0370(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Loadout4;                                   // 0x0378(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_rleg;                                       // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_rleg_next;                                  // 0x0388(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_rleg_prev_1;                                // 0x0390(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_SaveLoadout1;                               // 0x0398(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_SaveLoadout2;                               // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_SaveLoadout3;                               // 0x03A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_SaveLoadout4;                               // 0x03B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_shemag;                                     // 0x03B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_shemag_next;                                // 0x03C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_shemag_prev;                                // 0x03C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Vest;                                       // 0x03D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_vest_next;                                  // 0x03D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_vest_prev;                                  // 0x03E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_warbelt;                                    // 0x03E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_warbelt_next_1;                             // 0x03F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Warbelt_prev_1;                             // 0x03F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x0400(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_54;                                          // 0x0408(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_main;                               // 0x0410(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<class FName>                           Allowed_Items;                                     // 0x0418(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn)
	class ABP_EquipmentCharacter_C*               Character_Ref;                                     // 0x0428(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FST_LoadoutData                        Current_Loadout;                                   // 0x0430(0x0030)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)
	TArray<int32>                                 Loadout_Index;                                     // 0x0460(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           List_Arms;                                         // 0x0470(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           List_Backpack;                                     // 0x0480(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           List_Belt;                                         // 0x0490(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           List_Boots;                                        // 0x04A0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           List_Head;                                         // 0x04B0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           List_Helmet;                                       // 0x04C0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           List_Kneepads;                                     // 0x04D0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           List_Leg_L;                                        // 0x04E0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           List_Leg_R;                                        // 0x04F0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           List_Legs;                                         // 0x0500(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           List_Shemag;                                       // 0x0510(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           List_Torso;                                        // 0x0520(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           List_Vest;                                         // 0x0530(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class USoundBase*                             Close_Equipment_Sound_Cue;                         // 0x0540(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__WB_EquipmetScreen_Button_8ody_next_K2Node_ComponentBoundEvent_25_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_8ody_prev_K2Node_ComponentBoundEvent_26_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_backpack_next_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_backpack_prev_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_Boots_next_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_Boots_prev_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_face_next_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_face_prev_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_Gloves_next_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_Gloves_prev_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_Helmet_next_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_Helmet_prev_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_kneepad_next_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_kneepad_prev_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_legs_next_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_legs_prev_K2Node_ComponentBoundEvent_22_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_lleg_next_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_lleg_prev_K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_Loadout1_1_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_Loadout1_K2Node_ComponentBoundEvent_31_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_Loadout2_K2Node_ComponentBoundEvent_32_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_Loadout3_K2Node_ComponentBoundEvent_33_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_Loadout4_K2Node_ComponentBoundEvent_34_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_rleg_next_K2Node_ComponentBoundEvent_19_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_rleg_prev_1_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_SaveLoadout1_K2Node_ComponentBoundEvent_27_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_SaveLoadout2_K2Node_ComponentBoundEvent_28_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_SaveLoadout3_K2Node_ComponentBoundEvent_29_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_SaveLoadout4_K2Node_ComponentBoundEvent_30_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_shemag_next_K2Node_ComponentBoundEvent_23_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_shemag_prev_K2Node_ComponentBoundEvent_24_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_vest_next_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_vest_prev_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_warbelt_next_1_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_EquipmetScreen_Button_Warbelt_prev_1_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature();
	void Construct();
	void Destruct();
	void Determine_Current_Loadout_Index();
	void Equip_Next_Item_in_List(E_EquipmentSlots Equipment_Slot, const TArray<class FName>& ID_List);
	void Equip_Previous_Item_in_List(E_EquipmentSlots Equipment_Slot, TArray<class FName>& ID_List);
	void ExecuteUbergraph_WB_EquipmetScreen(int32 EntryPoint);
	void Sort_Equipment();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_EquipmetScreen_C">();
	}
	static class UWB_EquipmetScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_EquipmetScreen_C>();
	}
};
static_assert(alignof(UWB_EquipmetScreen_C) == 0x000008, "Wrong alignment on UWB_EquipmetScreen_C");
static_assert(sizeof(UWB_EquipmetScreen_C) == 0x000548, "Wrong size on UWB_EquipmetScreen_C");
static_assert(offsetof(UWB_EquipmetScreen_C, UberGraphFrame) == 0x000278, "Member 'UWB_EquipmetScreen_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_8ody_next) == 0x000280, "Member 'UWB_EquipmetScreen_C::Button_8ody_next' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_8ody_prev) == 0x000288, "Member 'UWB_EquipmetScreen_C::Button_8ody_prev' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Backpack) == 0x000290, "Member 'UWB_EquipmetScreen_C::Button_Backpack' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_backpack_next) == 0x000298, "Member 'UWB_EquipmetScreen_C::Button_backpack_next' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_backpack_prev) == 0x0002A0, "Member 'UWB_EquipmetScreen_C::Button_backpack_prev' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Body) == 0x0002A8, "Member 'UWB_EquipmetScreen_C::Button_Body' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Boots) == 0x0002B0, "Member 'UWB_EquipmetScreen_C::Button_Boots' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Boots_next) == 0x0002B8, "Member 'UWB_EquipmetScreen_C::Button_Boots_next' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Boots_prev) == 0x0002C0, "Member 'UWB_EquipmetScreen_C::Button_Boots_prev' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_CLOSEMENU) == 0x0002C8, "Member 'UWB_EquipmetScreen_C::Button_CLOSEMENU' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Face) == 0x0002D0, "Member 'UWB_EquipmetScreen_C::Button_Face' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_face_next) == 0x0002D8, "Member 'UWB_EquipmetScreen_C::Button_face_next' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_face_prev) == 0x0002E0, "Member 'UWB_EquipmetScreen_C::Button_face_prev' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Gloves) == 0x0002E8, "Member 'UWB_EquipmetScreen_C::Button_Gloves' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Gloves_next) == 0x0002F0, "Member 'UWB_EquipmetScreen_C::Button_Gloves_next' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Gloves_prev) == 0x0002F8, "Member 'UWB_EquipmetScreen_C::Button_Gloves_prev' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Helmet_2) == 0x000300, "Member 'UWB_EquipmetScreen_C::Button_Helmet_2' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Helmet_next) == 0x000308, "Member 'UWB_EquipmetScreen_C::Button_Helmet_next' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Helmet_prev) == 0x000310, "Member 'UWB_EquipmetScreen_C::Button_Helmet_prev' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_kneepad_next) == 0x000318, "Member 'UWB_EquipmetScreen_C::Button_kneepad_next' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_kneepad_prev) == 0x000320, "Member 'UWB_EquipmetScreen_C::Button_kneepad_prev' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_kneepads) == 0x000328, "Member 'UWB_EquipmetScreen_C::Button_kneepads' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Legs) == 0x000330, "Member 'UWB_EquipmetScreen_C::Button_Legs' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_legs_next) == 0x000338, "Member 'UWB_EquipmetScreen_C::Button_legs_next' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_legs_prev) == 0x000340, "Member 'UWB_EquipmetScreen_C::Button_legs_prev' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_lleg) == 0x000348, "Member 'UWB_EquipmetScreen_C::Button_lleg' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_lleg_next) == 0x000350, "Member 'UWB_EquipmetScreen_C::Button_lleg_next' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_lleg_prev) == 0x000358, "Member 'UWB_EquipmetScreen_C::Button_lleg_prev' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Loadout1) == 0x000360, "Member 'UWB_EquipmetScreen_C::Button_Loadout1' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Loadout2) == 0x000368, "Member 'UWB_EquipmetScreen_C::Button_Loadout2' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Loadout3) == 0x000370, "Member 'UWB_EquipmetScreen_C::Button_Loadout3' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Loadout4) == 0x000378, "Member 'UWB_EquipmetScreen_C::Button_Loadout4' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_rleg) == 0x000380, "Member 'UWB_EquipmetScreen_C::Button_rleg' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_rleg_next) == 0x000388, "Member 'UWB_EquipmetScreen_C::Button_rleg_next' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_rleg_prev_1) == 0x000390, "Member 'UWB_EquipmetScreen_C::Button_rleg_prev_1' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_SaveLoadout1) == 0x000398, "Member 'UWB_EquipmetScreen_C::Button_SaveLoadout1' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_SaveLoadout2) == 0x0003A0, "Member 'UWB_EquipmetScreen_C::Button_SaveLoadout2' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_SaveLoadout3) == 0x0003A8, "Member 'UWB_EquipmetScreen_C::Button_SaveLoadout3' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_SaveLoadout4) == 0x0003B0, "Member 'UWB_EquipmetScreen_C::Button_SaveLoadout4' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_shemag) == 0x0003B8, "Member 'UWB_EquipmetScreen_C::Button_shemag' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_shemag_next) == 0x0003C0, "Member 'UWB_EquipmetScreen_C::Button_shemag_next' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_shemag_prev) == 0x0003C8, "Member 'UWB_EquipmetScreen_C::Button_shemag_prev' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Vest) == 0x0003D0, "Member 'UWB_EquipmetScreen_C::Button_Vest' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_vest_next) == 0x0003D8, "Member 'UWB_EquipmetScreen_C::Button_vest_next' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_vest_prev) == 0x0003E0, "Member 'UWB_EquipmetScreen_C::Button_vest_prev' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_warbelt) == 0x0003E8, "Member 'UWB_EquipmetScreen_C::Button_warbelt' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_warbelt_next_1) == 0x0003F0, "Member 'UWB_EquipmetScreen_C::Button_warbelt_next_1' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Button_Warbelt_prev_1) == 0x0003F8, "Member 'UWB_EquipmetScreen_C::Button_Warbelt_prev_1' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Image) == 0x000400, "Member 'UWB_EquipmetScreen_C::Image' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Image_54) == 0x000408, "Member 'UWB_EquipmetScreen_C::Image_54' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, WidgetSwitcher_main) == 0x000410, "Member 'UWB_EquipmetScreen_C::WidgetSwitcher_main' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Allowed_Items) == 0x000418, "Member 'UWB_EquipmetScreen_C::Allowed_Items' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Character_Ref) == 0x000428, "Member 'UWB_EquipmetScreen_C::Character_Ref' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Current_Loadout) == 0x000430, "Member 'UWB_EquipmetScreen_C::Current_Loadout' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Loadout_Index) == 0x000460, "Member 'UWB_EquipmetScreen_C::Loadout_Index' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, List_Arms) == 0x000470, "Member 'UWB_EquipmetScreen_C::List_Arms' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, List_Backpack) == 0x000480, "Member 'UWB_EquipmetScreen_C::List_Backpack' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, List_Belt) == 0x000490, "Member 'UWB_EquipmetScreen_C::List_Belt' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, List_Boots) == 0x0004A0, "Member 'UWB_EquipmetScreen_C::List_Boots' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, List_Head) == 0x0004B0, "Member 'UWB_EquipmetScreen_C::List_Head' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, List_Helmet) == 0x0004C0, "Member 'UWB_EquipmetScreen_C::List_Helmet' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, List_Kneepads) == 0x0004D0, "Member 'UWB_EquipmetScreen_C::List_Kneepads' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, List_Leg_L) == 0x0004E0, "Member 'UWB_EquipmetScreen_C::List_Leg_L' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, List_Leg_R) == 0x0004F0, "Member 'UWB_EquipmetScreen_C::List_Leg_R' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, List_Legs) == 0x000500, "Member 'UWB_EquipmetScreen_C::List_Legs' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, List_Shemag) == 0x000510, "Member 'UWB_EquipmetScreen_C::List_Shemag' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, List_Torso) == 0x000520, "Member 'UWB_EquipmetScreen_C::List_Torso' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, List_Vest) == 0x000530, "Member 'UWB_EquipmetScreen_C::List_Vest' has a wrong offset!");
static_assert(offsetof(UWB_EquipmetScreen_C, Close_Equipment_Sound_Cue) == 0x000540, "Member 'UWB_EquipmetScreen_C::Close_Equipment_Sound_Cue' has a wrong offset!");

}

