#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_Text_Button

#include "Basic.hpp"

#include "CommonUI_structs.hpp"
#include "S_GlobalColorOption_structs.hpp"
#include "ECommonButtonState_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function WB_Text_Button.WB_Text_Button_C.BndEvt__Text_Button_InputActionWidget_K2Node_ComponentBoundEvent_0_OnInputMethodChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WB_Text_Button_C_BndEvt__Text_Button_InputActionWidget_K2Node_ComponentBoundEvent_0_OnInputMethodChanged__DelegateSignature final
{
public:
	bool                                          bUsingGamepad;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Text_Button_C_BndEvt__Text_Button_InputActionWidget_K2Node_ComponentBoundEvent_0_OnInputMethodChanged__DelegateSignature) == 0x000001, "Wrong alignment on WB_Text_Button_C_BndEvt__Text_Button_InputActionWidget_K2Node_ComponentBoundEvent_0_OnInputMethodChanged__DelegateSignature");
static_assert(sizeof(WB_Text_Button_C_BndEvt__Text_Button_InputActionWidget_K2Node_ComponentBoundEvent_0_OnInputMethodChanged__DelegateSignature) == 0x000001, "Wrong size on WB_Text_Button_C_BndEvt__Text_Button_InputActionWidget_K2Node_ComponentBoundEvent_0_OnInputMethodChanged__DelegateSignature");
static_assert(offsetof(WB_Text_Button_C_BndEvt__Text_Button_InputActionWidget_K2Node_ComponentBoundEvent_0_OnInputMethodChanged__DelegateSignature, bUsingGamepad) == 0x000000, "Member 'WB_Text_Button_C_BndEvt__Text_Button_InputActionWidget_K2Node_ComponentBoundEvent_0_OnInputMethodChanged__DelegateSignature::bUsingGamepad' has a wrong offset!");

// Function WB_Text_Button.WB_Text_Button_C.DisplayInputAction
// 0x000A (0x000A - 0x0000)
struct WB_Text_Button_C_DisplayInputAction final
{
public:
	bool                                          bShow;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsUsingGamepad_ReturnValue;               // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSelected_ReturnValue;                  // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetInputActionWidgetHasInput_ReturnValue; // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Text_Button_C_DisplayInputAction) == 0x000001, "Wrong alignment on WB_Text_Button_C_DisplayInputAction");
static_assert(sizeof(WB_Text_Button_C_DisplayInputAction) == 0x00000A, "Wrong size on WB_Text_Button_C_DisplayInputAction");
static_assert(offsetof(WB_Text_Button_C_DisplayInputAction, bShow) == 0x000000, "Member 'WB_Text_Button_C_DisplayInputAction::bShow' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_DisplayInputAction, Temp_bool_Variable) == 0x000001, "Member 'WB_Text_Button_C_DisplayInputAction::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_DisplayInputAction, Temp_byte_Variable) == 0x000002, "Member 'WB_Text_Button_C_DisplayInputAction::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_DisplayInputAction, Temp_byte_Variable_1) == 0x000003, "Member 'WB_Text_Button_C_DisplayInputAction::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_DisplayInputAction, CallFunc_IsUsingGamepad_ReturnValue) == 0x000004, "Member 'WB_Text_Button_C_DisplayInputAction::CallFunc_IsUsingGamepad_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_DisplayInputAction, K2Node_Select_Default) == 0x000005, "Member 'WB_Text_Button_C_DisplayInputAction::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_DisplayInputAction, CallFunc_GetSelected_ReturnValue) == 0x000006, "Member 'WB_Text_Button_C_DisplayInputAction::CallFunc_GetSelected_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_DisplayInputAction, CallFunc_Not_PreBool_ReturnValue) == 0x000007, "Member 'WB_Text_Button_C_DisplayInputAction::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_DisplayInputAction, CallFunc_Not_PreBool_ReturnValue_1) == 0x000008, "Member 'WB_Text_Button_C_DisplayInputAction::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_DisplayInputAction, CallFunc_GetInputActionWidgetHasInput_ReturnValue) == 0x000009, "Member 'WB_Text_Button_C_DisplayInputAction::CallFunc_GetInputActionWidgetHasInput_ReturnValue' has a wrong offset!");

// Function WB_Text_Button.WB_Text_Button_C.DisplayNewsIndicator
// 0x0005 (0x0005 - 0x0000)
struct WB_Text_Button_C_DisplayNewsIndicator final
{
public:
	bool                                          bDisplayNewsIndicator;                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Text_Button_C_DisplayNewsIndicator) == 0x000001, "Wrong alignment on WB_Text_Button_C_DisplayNewsIndicator");
static_assert(sizeof(WB_Text_Button_C_DisplayNewsIndicator) == 0x000005, "Wrong size on WB_Text_Button_C_DisplayNewsIndicator");
static_assert(offsetof(WB_Text_Button_C_DisplayNewsIndicator, bDisplayNewsIndicator) == 0x000000, "Member 'WB_Text_Button_C_DisplayNewsIndicator::bDisplayNewsIndicator' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_DisplayNewsIndicator, Temp_bool_Variable) == 0x000001, "Member 'WB_Text_Button_C_DisplayNewsIndicator::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_DisplayNewsIndicator, Temp_byte_Variable) == 0x000002, "Member 'WB_Text_Button_C_DisplayNewsIndicator::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_DisplayNewsIndicator, Temp_byte_Variable_1) == 0x000003, "Member 'WB_Text_Button_C_DisplayNewsIndicator::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_DisplayNewsIndicator, K2Node_Select_Default) == 0x000004, "Member 'WB_Text_Button_C_DisplayNewsIndicator::K2Node_Select_Default' has a wrong offset!");

// Function WB_Text_Button.WB_Text_Button_C.ExecuteUbergraph_WB_Text_Button
// 0x0148 (0x0148 - 0x0000)
struct WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3505[0x3];                                     // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3506[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetButtonText_ReturnValue;                // 0x0018(0x0018)()
	TSubclassOf<class UCommonTextStyle>           CallFunc_GetCurrentTextStyleClass_ReturnValue;     // 0x0030(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TSubclassOf<class UCommonTextStyle>           CallFunc_GetCurrentTextStyleClass_ReturnValue_1;   // 0x0038(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TArray<class UWB_Base_Button_C*>              CallFunc_GetAllWidgetsOfClass_FoundWidgets;        // 0x0040(0x0010)(ReferenceParm, ContainsInstancedReference)
	EHorizontalAlignment                          Temp_byte_Variable;                                // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3507[0x3];                                     // 0x0051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3508[0x7];                                     // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x0060(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector2D_X;                          // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector2D_Y;                          // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EHorizontalAlignment                          Temp_byte_Variable_1;                              // 0x0081(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0082(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3509[0x1];                                     // 0x0083(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Temp_struct_Variable;                              // 0x0084(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColorByType_ReturnValue;         // 0x0094(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasColorChanged_ReturnValue;              // 0x00A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_350A[0x3];                                     // 0x00A5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_GetGlobalColorByType_ReturnValue_1;       // 0x00A8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue_1;               // 0x00B8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector2D_X_1;                        // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector2D_Y_1;                        // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x00D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsHovered_ReturnValue;                    // 0x00DA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsHovered_ReturnValue_1;                  // 0x00DB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSelected_ReturnValue;                  // 0x00DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsHovered_ReturnValue_2;                  // 0x00DD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSelected_ReturnValue_1;                // 0x00DE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSelected_ReturnValue_2;                // 0x00DF(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_350B[0x3];                                     // 0x00E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           K2Node_Select_Default;                             // 0x00E4(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bUsingGamepad;          // 0x00F4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_350C[0x3];                                     // 0x00F5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UOverlaySlot*                           CallFunc_SlotAsOverlaySlot_ReturnValue;            // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EHorizontalAlignment                          K2Node_Select_Default_1;                           // 0x0101(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_2;                           // 0x0102(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x0103(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0104(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWB_Base_Button_C*                      CallFunc_Array_Get_Item;                           // 0x0108(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_Select_Default_3;                           // 0x0110(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0121(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_350D[0x6];                                     // 0x0122(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWB_Text_Button_C*                      K2Node_DynamicCast_AsWB_Text_Button;               // 0x0128(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSelected_ReturnValue_3;                // 0x0131(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0132(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_350E[0x1];                                     // 0x0133(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast; // 0x0134(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast; // 0x0138(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast_1; // 0x013C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast_1; // 0x0140(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button) == 0x000008, "Wrong alignment on WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button");
static_assert(sizeof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button) == 0x000148, "Wrong size on WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, EntryPoint) == 0x000000, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::EntryPoint' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, Temp_bool_Variable) == 0x000004, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, Temp_int_Loop_Counter_Variable) == 0x000008, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, K2Node_Event_IsDesignTime) == 0x000010, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_GetButtonText_ReturnValue) == 0x000018, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_GetButtonText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_GetCurrentTextStyleClass_ReturnValue) == 0x000030, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_GetCurrentTextStyleClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_GetCurrentTextStyleClass_ReturnValue_1) == 0x000038, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_GetCurrentTextStyleClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_GetAllWidgetsOfClass_FoundWidgets) == 0x000040, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_GetAllWidgetsOfClass_FoundWidgets' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, Temp_byte_Variable) == 0x000050, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_Array_Length_ReturnValue) == 0x000054, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_Less_IntInt_ReturnValue) == 0x000058, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_MakeVector2D_ReturnValue) == 0x000060, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_BreakVector2D_X) == 0x000070, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_BreakVector2D_X' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_BreakVector2D_Y) == 0x000078, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_BreakVector2D_Y' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_IsValid_ReturnValue) == 0x000080, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, Temp_byte_Variable_1) == 0x000081, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, Temp_bool_Variable_1) == 0x000082, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, Temp_struct_Variable) == 0x000084, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_GetGlobalColorByType_ReturnValue) == 0x000094, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_GetGlobalColorByType_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_HasColorChanged_ReturnValue) == 0x0000A4, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_HasColorChanged_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_GetGlobalColorByType_ReturnValue_1) == 0x0000A8, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_GetGlobalColorByType_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_MakeVector2D_ReturnValue_1) == 0x0000B8, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_MakeVector2D_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_BreakVector2D_X_1) == 0x0000C8, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_BreakVector2D_X_1' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_BreakVector2D_Y_1) == 0x0000D0, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_BreakVector2D_Y_1' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_IsValid_ReturnValue_1) == 0x0000D8, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, Temp_byte_Variable_2) == 0x0000D9, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_IsHovered_ReturnValue) == 0x0000DA, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_IsHovered_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_IsHovered_ReturnValue_1) == 0x0000DB, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_IsHovered_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_GetSelected_ReturnValue) == 0x0000DC, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_GetSelected_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_IsHovered_ReturnValue_2) == 0x0000DD, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_IsHovered_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_GetSelected_ReturnValue_1) == 0x0000DE, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_GetSelected_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_GetSelected_ReturnValue_2) == 0x0000DF, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_GetSelected_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, Temp_bool_Variable_2) == 0x0000E0, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, K2Node_Select_Default) == 0x0000E4, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, K2Node_ComponentBoundEvent_bUsingGamepad) == 0x0000F4, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::K2Node_ComponentBoundEvent_bUsingGamepad' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_SlotAsOverlaySlot_ReturnValue) == 0x0000F8, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_SlotAsOverlaySlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, Temp_byte_Variable_3) == 0x000100, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, K2Node_Select_Default_1) == 0x000101, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, K2Node_Select_Default_2) == 0x000102, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, Temp_bool_Variable_3) == 0x000103, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, Temp_int_Array_Index_Variable) == 0x000104, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_Array_Get_Item) == 0x000108, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, K2Node_Select_Default_3) == 0x000110, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x000120, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_IsValid_ReturnValue_2) == 0x000121, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, K2Node_DynamicCast_AsWB_Text_Button) == 0x000128, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::K2Node_DynamicCast_AsWB_Text_Button' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, K2Node_DynamicCast_bSuccess) == 0x000130, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_GetSelected_ReturnValue_3) == 0x000131, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_GetSelected_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000132, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast) == 0x000134, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast) == 0x000138, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast_1) == 0x00013C, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button, CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast_1) == 0x000140, "Member 'WB_Text_Button_C_ExecuteUbergraph_WB_Text_Button::CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast_1' has a wrong offset!");

// Function WB_Text_Button.WB_Text_Button_C.GetButtonText
// 0x0058 (0x0058 - 0x0000)
struct WB_Text_Button_C_GetButtonText final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	bool                                          Temp_bool_Variable;                                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_350F[0x7];                                     // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetInputAction_DisplayName_DisplayName;   // 0x0020(0x0018)()
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3510[0x7];                                     // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default;                             // 0x0040(0x0018)()
};
static_assert(alignof(WB_Text_Button_C_GetButtonText) == 0x000008, "Wrong alignment on WB_Text_Button_C_GetButtonText");
static_assert(sizeof(WB_Text_Button_C_GetButtonText) == 0x000058, "Wrong size on WB_Text_Button_C_GetButtonText");
static_assert(offsetof(WB_Text_Button_C_GetButtonText, ReturnValue) == 0x000000, "Member 'WB_Text_Button_C_GetButtonText::ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_GetButtonText, Temp_bool_Variable) == 0x000018, "Member 'WB_Text_Button_C_GetButtonText::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_GetButtonText, CallFunc_GetInputAction_DisplayName_DisplayName) == 0x000020, "Member 'WB_Text_Button_C_GetButtonText::CallFunc_GetInputAction_DisplayName_DisplayName' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_GetButtonText, CallFunc_TextIsEmpty_ReturnValue) == 0x000038, "Member 'WB_Text_Button_C_GetButtonText::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_GetButtonText, K2Node_Select_Default) == 0x000040, "Member 'WB_Text_Button_C_GetButtonText::K2Node_Select_Default' has a wrong offset!");

// Function WB_Text_Button.WB_Text_Button_C.GetHasTextOverride
// 0x0003 (0x0003 - 0x0000)
struct WB_Text_Button_C_GetHasTextOverride final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Text_Button_C_GetHasTextOverride) == 0x000001, "Wrong alignment on WB_Text_Button_C_GetHasTextOverride");
static_assert(sizeof(WB_Text_Button_C_GetHasTextOverride) == 0x000003, "Wrong size on WB_Text_Button_C_GetHasTextOverride");
static_assert(offsetof(WB_Text_Button_C_GetHasTextOverride, ReturnValue) == 0x000000, "Member 'WB_Text_Button_C_GetHasTextOverride::ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_GetHasTextOverride, CallFunc_TextIsEmpty_ReturnValue) == 0x000001, "Member 'WB_Text_Button_C_GetHasTextOverride::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_GetHasTextOverride, CallFunc_Not_PreBool_ReturnValue) == 0x000002, "Member 'WB_Text_Button_C_GetHasTextOverride::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");

// Function WB_Text_Button.WB_Text_Button_C.GetHasTriggeringInputAction
// 0x0002 (0x0002 - 0x0000)
struct WB_Text_Button_C_GetHasTriggeringInputAction final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Text_Button_C_GetHasTriggeringInputAction) == 0x000001, "Wrong alignment on WB_Text_Button_C_GetHasTriggeringInputAction");
static_assert(sizeof(WB_Text_Button_C_GetHasTriggeringInputAction) == 0x000002, "Wrong size on WB_Text_Button_C_GetHasTriggeringInputAction");
static_assert(offsetof(WB_Text_Button_C_GetHasTriggeringInputAction, ReturnValue) == 0x000000, "Member 'WB_Text_Button_C_GetHasTriggeringInputAction::ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_GetHasTriggeringInputAction, CallFunc_IsValid_ReturnValue) == 0x000001, "Member 'WB_Text_Button_C_GetHasTriggeringInputAction::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function WB_Text_Button.WB_Text_Button_C.GetInputAction_DisplayName
// 0x03A0 (0x03A0 - 0x0000)
struct WB_Text_Button_C_GetInputAction_DisplayName final
{
public:
	class FText                                   DisplayName;                                       // 0x0000(0x0018)(Parm, OutParm)
	struct FDataTableRowHandle                    CallFunc_GetInputAction_InputActionRow;            // 0x0018(0x0010)(NoDestructor)
	bool                                          CallFunc_GetInputAction_ReturnValue;               // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3511[0x7];                                     // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCommonInputActionDataBase             CallFunc_GetDataTableRowFromName_OutRow;           // 0x0030(0x0360)()
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x0390(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Text_Button_C_GetInputAction_DisplayName) == 0x000010, "Wrong alignment on WB_Text_Button_C_GetInputAction_DisplayName");
static_assert(sizeof(WB_Text_Button_C_GetInputAction_DisplayName) == 0x0003A0, "Wrong size on WB_Text_Button_C_GetInputAction_DisplayName");
static_assert(offsetof(WB_Text_Button_C_GetInputAction_DisplayName, DisplayName) == 0x000000, "Member 'WB_Text_Button_C_GetInputAction_DisplayName::DisplayName' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_GetInputAction_DisplayName, CallFunc_GetInputAction_InputActionRow) == 0x000018, "Member 'WB_Text_Button_C_GetInputAction_DisplayName::CallFunc_GetInputAction_InputActionRow' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_GetInputAction_DisplayName, CallFunc_GetInputAction_ReturnValue) == 0x000028, "Member 'WB_Text_Button_C_GetInputAction_DisplayName::CallFunc_GetInputAction_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_GetInputAction_DisplayName, CallFunc_GetDataTableRowFromName_OutRow) == 0x000030, "Member 'WB_Text_Button_C_GetInputAction_DisplayName::CallFunc_GetDataTableRowFromName_OutRow' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_GetInputAction_DisplayName, CallFunc_GetDataTableRowFromName_ReturnValue) == 0x000390, "Member 'WB_Text_Button_C_GetInputAction_DisplayName::CallFunc_GetDataTableRowFromName_ReturnValue' has a wrong offset!");

// Function WB_Text_Button.WB_Text_Button_C.GetInputActionWidgetHasInput
// 0x00F0 (0x00F0 - 0x0000)
struct WB_Text_Button_C_GetInputActionWidgetHasInput final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3512[0xF];                                     // 0x0001(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            CallFunc_GetIcon_ReturnValue;                      // 0x0010(0x00D0)()
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x00E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Text_Button_C_GetInputActionWidgetHasInput) == 0x000010, "Wrong alignment on WB_Text_Button_C_GetInputActionWidgetHasInput");
static_assert(sizeof(WB_Text_Button_C_GetInputActionWidgetHasInput) == 0x0000F0, "Wrong size on WB_Text_Button_C_GetInputActionWidgetHasInput");
static_assert(offsetof(WB_Text_Button_C_GetInputActionWidgetHasInput, ReturnValue) == 0x000000, "Member 'WB_Text_Button_C_GetInputActionWidgetHasInput::ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_GetInputActionWidgetHasInput, CallFunc_GetIcon_ReturnValue) == 0x000010, "Member 'WB_Text_Button_C_GetInputActionWidgetHasInput::CallFunc_GetIcon_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_GetInputActionWidgetHasInput, CallFunc_IsValid_ReturnValue) == 0x0000E0, "Member 'WB_Text_Button_C_GetInputActionWidgetHasInput::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_GetInputActionWidgetHasInput, CallFunc_Array_IsValidIndex_ReturnValue) == 0x0000E1, "Member 'WB_Text_Button_C_GetInputActionWidgetHasInput::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");

// Function WB_Text_Button.WB_Text_Button_C.OnFocusReceived
// 0x01B8 (0x01B8 - 0x0000)
struct WB_Text_Button_C_OnFocusReceived final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FFocusEvent                            InFocusEvent;                                      // 0x0040(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FEventReply                            ReturnValue;                                       // 0x0048(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_Unhandled_ReturnValue;                    // 0x0100(0x00B8)()
};
static_assert(alignof(WB_Text_Button_C_OnFocusReceived) == 0x000008, "Wrong alignment on WB_Text_Button_C_OnFocusReceived");
static_assert(sizeof(WB_Text_Button_C_OnFocusReceived) == 0x0001B8, "Wrong size on WB_Text_Button_C_OnFocusReceived");
static_assert(offsetof(WB_Text_Button_C_OnFocusReceived, MyGeometry) == 0x000000, "Member 'WB_Text_Button_C_OnFocusReceived::MyGeometry' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_OnFocusReceived, InFocusEvent) == 0x000040, "Member 'WB_Text_Button_C_OnFocusReceived::InFocusEvent' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_OnFocusReceived, ReturnValue) == 0x000048, "Member 'WB_Text_Button_C_OnFocusReceived::ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_OnFocusReceived, CallFunc_Unhandled_ReturnValue) == 0x000100, "Member 'WB_Text_Button_C_OnFocusReceived::CallFunc_Unhandled_ReturnValue' has a wrong offset!");

// Function WB_Text_Button.WB_Text_Button_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WB_Text_Button_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Text_Button_C_PreConstruct) == 0x000001, "Wrong alignment on WB_Text_Button_C_PreConstruct");
static_assert(sizeof(WB_Text_Button_C_PreConstruct) == 0x000001, "Wrong size on WB_Text_Button_C_PreConstruct");
static_assert(offsetof(WB_Text_Button_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WB_Text_Button_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WB_Text_Button.WB_Text_Button_C.SetButtonState
// 0x0038 (0x0038 - 0x0000)
struct WB_Text_Button_C_SetButtonState final
{
public:
	ECommonButtonState                            State;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3513[0x2];                                     // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Temp_struct_Variable;                              // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonButtonState                            Temp_byte_Variable;                                // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FS_GlobalColorOption                   K2Node_Select_Default;                             // 0x0015(0x0002)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3514[0x1];                                     // 0x0017(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_GetGlobalColorByType_ReturnValue;         // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_Select_Default_1;                           // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_Text_Button_C_SetButtonState) == 0x000004, "Wrong alignment on WB_Text_Button_C_SetButtonState");
static_assert(sizeof(WB_Text_Button_C_SetButtonState) == 0x000038, "Wrong size on WB_Text_Button_C_SetButtonState");
static_assert(offsetof(WB_Text_Button_C_SetButtonState, State) == 0x000000, "Member 'WB_Text_Button_C_SetButtonState::State' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_SetButtonState, Temp_bool_Variable) == 0x000001, "Member 'WB_Text_Button_C_SetButtonState::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_SetButtonState, Temp_struct_Variable) == 0x000004, "Member 'WB_Text_Button_C_SetButtonState::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_SetButtonState, Temp_byte_Variable) == 0x000014, "Member 'WB_Text_Button_C_SetButtonState::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_SetButtonState, K2Node_Select_Default) == 0x000015, "Member 'WB_Text_Button_C_SetButtonState::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_SetButtonState, CallFunc_GetGlobalColorByType_ReturnValue) == 0x000018, "Member 'WB_Text_Button_C_SetButtonState::CallFunc_GetGlobalColorByType_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_Text_Button_C_SetButtonState, K2Node_Select_Default_1) == 0x000028, "Member 'WB_Text_Button_C_SetButtonState::K2Node_Select_Default_1' has a wrong offset!");

}

